### ISSUE TITLE
db table locks after the first email and subsequent emails fail

### ISSUE THREAD

**Issue by ajpierson** [sj26/mailcatcher#117]
When I use mailcatcher, it will receive 1 email, then the db table is locked and all other messages are rejected with:

Net::SMTPFatalError: 550 Message rejected

	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:942:in `check_response'
	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:896:in `data'
	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:654:in `sendmail'
	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:843:in `rcptto_list'
	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:654:in `sendmail'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
	from /home/vagrant/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/net/smtp.rb:526:in `start'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mail-2.5.4/lib/mail/message.rb:232:in `deliver'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/actionmailer-3.2.14/lib/action_mailer/base.rb:415:in `deliver_mail'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/activesupport-3.2.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/activesupport-3.2.14/lib/active_support/notifications.rb:123:in `instrument'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/actionmailer-3.2.14/lib/action_mailer/base.rb:413:in `deliver_mail'
	from /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mail-2.5.4/lib/mail/message.rb:232:in `deliver'

The stacktrace from mailcatcher looks like:

==> SMTP: Received message from '<survey@place.com>' (607 bytes)
*** Error receiving message: {:source=>"Date: Wed, 08 Jan 2014 06:52:20 +0000\nFrom: survey@place.com\nReply-To: Support <support@someplace.com>\nTo: asdfasdf@asdfasdf.com\nMessage-ID: <52ccf5a4bac40_1009b4d4134524e2@bptw.localdomain.mail>\nSubject: Subject\nMime-Version: 1.0\nContent-Type: text/html;\n charset=UTF-8\nContent-Transfer-Encoding: 7bit\n\n<p>First Name:Asdf</p>\n<p>Last Name:Asdf</p>\n<p>Full Name:Asdf Asdf</p>\n<p>Formal Name:Mr. Asdf Asdf</p>\n<p>Company Name:Some Company</p>\n<p>URL:&nbsp;<a href=\"http://localhost:3000/surveys/er2014/en\">http://localhost:3000/surveys/er2014/en</a></p>\n<p>&nbsp;</p>", :sender=>"<survey@place.com>", :recipients=>["<asdfasdf@asdfasdf.com>"]}
    Exception: database table is locked
    Backtrace:
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/sqlite3-1.3.8/lib/sqlite3/statement.rb:67:in `step'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/sqlite3-1.3.8/lib/sqlite3/statement.rb:67:in `execute'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:44:in `add_message'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mailcatcher-0.5.12/lib/mail_catcher/smtp.rb:42:in `receive_message'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/em/protocols/smtpserver.rb:535:in `process_data_line'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/em/protocols/smtpserver.rb:196:in `receive_line'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:64:in `receive_data'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mailcatcher-0.5.12/lib/mail_catcher.rb:134:in `run!'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/gems/mailcatcher-0.5.12/bin/mailcatcher:4
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/bin/mailcatcher:23:in `load'
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/bin/mailcatcher:23
       /home/vagrant/.rvm/gems/ree-1.8.7-2012.02@bptw/bin/ruby_executable_hooks:14

Any idea what I'm doing wrong?

**Comment by sj26** [comment]
@sancromeu nice investigation, albeit with frustrating results.

The whole point of prepared statements is to prepare them once then reuse them with varied bound data. This looks like an upstream bug that I can't really address except to remove an optimisation which should work for everybody.

I'm afraid the resolution here is probably to fix the upstream sqlite package in centos, or recompile it, and these things are outside my control so closing this issue.
