### ISSUE TITLE
Failed to build gem native extension on Linux with no explanation

### ISSUE THREAD

**Issue by Faison** [sj26/mailcatcher#144]
Hi There,

I'm using vagrant with Ubuntu 14.04 LTS (Trusty Tahr) and have installed sqlite3-dev. When I try to install mailcatcher, the installation fails and I don't get a nice debug message telling me what went wrong. So I'm posting what happened here in hopes that someone will be able to help me out. Thanks!

Here's what happened with the gem installer

```
vagrant@vvv:~$ sudo gem install mailcatcher
Building native extensions.  This could take a while...
ERROR:  Error installing mailcatcher:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb

Gem files will remain installed in /var/lib/gems/1.9.1/gems/eventmachine-1.0.3 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/ext/gem_make.out
vagrant@vvv:~$ cat /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/ext/gem_make.out 
/usr/bin/ruby1.9.1 extconf.rb
```

Here's what happened when I tried to install from source

```
vagrant@vvv:~/mailcatcher$ gem build mailcatcher.gemspec 
  Successfully built RubyGem
  Name: mailcatcher
  Version: 0.6.0
  File: mailcatcher-0.6.0.gem
vagrant@vvv:~/mailcatcher$ sudo gem install mailcatcher-0.6.0.gem 
Fetching: json-1.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing mailcatcher-0.6.0.gem:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb

Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.8.1/ext/json/ext/generator/gem_make.out
vagrant@vvv:~/mailcatcher$ cat /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/ext/gem_make.out 
/usr/bin/ruby1.9.1 extconf.rb

```

**Comment by hanzixiaoshu** [comment]
thank you every much

**Comment by Nathan-BIGAIGNON** [comment]
You have to install ruby-dev. It's working with the 1.9 version of ruby.
Kind regards,

**Comment by bjellesma** [comment]
Thank you! This has helped me point me in the direction of using RVM to help install ruby on rails on Linux Mint

**Comment by kenorb** [comment]
I can confirm that installing `sudo apt-get install ruby-dev` before `sudo gem install mailcatcher` worked fine.

**Comment by ajahongir** [comment]
install: 
sudo apt-get install libgmp3-dev

**Comment by chlab** [comment]
Thanks @kenorb. This should really be part of the installation steps. I just spent about 45mins compiling ruby 2 and trying to install mailcatcher try & error style. This is the reason we have package managers.

Don't want to complain though, thanks for the great work guys.

**Comment by jorgeorpinel** [comment]
@kenorb 's instructions worked for me:

> installing `sudo apt-get install ruby-dev` before `sudo gem install mailcatcher`

**Comment by martinverdejo** [comment]
> installing sudo `apt-get install ruby-dev` before sudo gem install overcommit

Does that mean `brew install ruby-dev` for osx? It says `No available formula with the name "ruby-dev"`

**Comment by chlab** [comment]
Nope, that's the debian package name, not necessarily the homebrew name.
This might do it for you: https://github.com/rbenv/rbenv

**Comment by kkrieger85** [comment]
`sudo apt-get install ruby-dev ` is working for me too. 

But now I have to update Ruby to Version >= 2.0

```
Fetching: mime-types-data-3.2016.0221.gem (100%)
ERROR:  Error installing mailcatcher:
	mime-types-data requires Ruby version >= 2.0.
```

**Comment by awaistune** [comment]
sudo apt-get install ruby-dev is working for me too. 
This works for me too Thanks . :dancer:

**Comment by tersmitten** [comment]
@kkrieger85 See https://github.com/sj26/mailcatcher/issues/277#issuecomment-202617739

**Comment by vhosakot** [comment]
I saw the error `Failed to build gem native extension` too on CentOS 7.3 and vagrant 1.8.7.

I resolved it after installed ruby-devel and gcc (`yum -y install ruby-devel gcc`)

**Comment by blendsoul** [comment]
Thanks guys. I was traing to install sass using `sudo gem install sass --no-user-install` and I have the same error. I'm doing it on Chrome OS / Chromebook in core linux installed using Crouton. I did what many of you suggest with one more thing.

```
sudo apt-get install ruby-dev libsqlite3-dev gcc man
```

**Comment by anuragagrawal0430** [comment]
Thanks alot guys. I'm also facing the same error with Linux Mint 18.2 and ruby 2.3.1 .`sudo apt-get install ruby-dev libsqlite3-dev gcc man` solved the issue for me

**Comment by ellcs** [comment]
In case someone struggles with OpenSuse:

```bash
# ruby 2.1.x
zypper in gcc make ruby2.1-devel ruby2.1-devel-extra
# or ruby 2.2.x
zypper in gcc make ruby2.2-devel ruby2.2-devel-extra
```

**Comment by ramanvirtual** [comment]
After run the following cmd , it will work fin for me
 sudo apt-get install ruby-full

**Comment by wturrell** [comment]
Ubuntu 14.04.5 LTS (and using the standard "Trusty" package repositories in `/etc/apt/sources.list`)

Fixed with:

```
sudo apt-get install ruby-dev
sudo apt-get install ruby2.0
sudo gem install mailcatcher
```

**Comment by dasj19** [comment]
This is what worked for me:
`apt remove ruby
apt install software-properties-common
apt-add-repository ppa:brightbox/ruby-ng
apt update
apt install ruby2.4 ruby2.4-dev libsqlite3-dev
gem install mailcatcher`

**Comment by danger2k7** [comment]
Hi there,

Make sure you have the rubyX-dev package installed.

All should be good  after that.

Cheers.

**Comment by ShaikhahMaasher** [comment]
Same error happened to me on Ubuntu bash when I'm trying to install any of gem packages, I always get that `ERROR: Failed to build gem native extension.`

Then it solved using 
`sudo apt-get install build-essential dh-autoreconf`

I also installed gcc & ruby-dev

**Comment by MiladRahmani** [comment]
> I can confirm that installing `sudo apt-get install ruby-dev libsqlite3-dev` before `sudo gem install mailcatcher` worked fine.

Thanks  a lot, this solution was useful for me.

**Comment by Erotico** [comment]
> You have gcc?
> Try 'apt-get install build-essential' before installing gem.

This was the only solution that worked for me on 2020. Thank you so much!
