### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by Baysen** [sj26/mailcatcher#147]
Hey there,

before I start, I usually have nothing to do with ruby, so I only have a very crude idea about what's going on here.

I installed mailcatcher onto my development machine which runs Unbuntu Server 12.04 with ruby 2.0.0p247. It runs perfectly, Web interface is visible and a simple test mail from php mail function arrived ok.

Now the problem seems to start when I try to send mails with UTF-8 encoding. PHP error.log giving me the following:

```
/usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/core_extensions/string.rb:14:in 'gsub': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/core_extensions/string.rb:14:in 'to_crlf'
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/message.rb:1983:in 'raw_source='
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/message.rb:2108:in 'init_with_string'
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/message.rb:128:in 'initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/mail.rb:50:in 'new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/mail-2.6.1/lib/mail/mail.rb:50:in 'new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/mailcatcher-0.5.12/bin/catchmail:48:in '<top (required)>'
        from /usr/local/bin/catchmail:23:in 'load'
        from /usr/local/bin/catchmail:23:in '<main>'
```

Without the additional header for encoding everything seems to work. Is there maybe an issue with the version of ruby that is installed?

Can somebody point me in the right direction? I really love the tool.

Thank you!

**Comment by akimad** [comment]
Solved for me adding 2 lines in this file:
/Users/dam/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mailcatcher-0.6.5/bin/catchmail

Just add this 2 lines after the "#!/usr/bin/env ruby" like this:
`#!/usr/bin/env ruby

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

begin
  require 'mail'
rescue LoadError
  require 'rubygems'
  require 'mail'
end
.
.
.`
