### ISSUE TITLE
PHP catchmail not working

### ISSUE THREAD

**Issue by handijk** [sj26/mailcatcher#148]
From the commandline messages are received just fine

`echo -e "From: Mail Catcher <mailcatcher@example.com>\r\nTo: mailcatcher@example.com\r\ne" |catchmail -f mailcatcher@example.com`

But whenever i try from php it is not received by mailcatcher and it fails without an error.
I have used the -f option in the php.ini and i am adding a From header. I have tried to set the sendmail_path in php.ini to the absolute path but it didn't help.
Any ideas?

**Comment by mathijs-soliede** [comment]
I'm having this exact same issue, @handijk  did you solve this?
