### ISSUE TITLE
mailcatcher: command not found

### ISSUE THREAD

**Issue by therobyouknow** [sj26/mailcatcher#151]
followed the instructions
but simply typing mailcatcher gives command not found

Ubuntu 12.04 LTS 64bit in a VM
logged in as root user

here is the log output of the install, followed by issuing mailcatcher

presumably mailcatcher needs to be added to environmental paths so that simply typing mailcatcher at the command line will work, but given that this is not a step in the instructions, I am assuming that it is not normally necessary. Please advise.

[12:39 PM]-[root@packer-virtualbox-iso]-[/home/vagrant] 
# gem install mailcatcher
Fetching: i18n-0.6.11.gem (100%)
Successfully installed i18n-0.6.11
Fetching: multi_json-1.10.1.gem (100%)
Successfully installed multi_json-1.10.1
Fetching: activesupport-3.2.19.gem (100%)
Successfully installed activesupport-3.2.19
Fetching: eventmachine-1.0.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.3
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: mime-types-2.3.gem (100%)
Successfully installed mime-types-2.3
Fetching: mail-2.6.1.gem (100%)
Successfully installed mail-2.6.1
Fetching: rack-1.5.2.gem (100%)
Successfully installed rack-1.5.2
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.5.gem (100%)
Successfully installed sinatra-1.4.5
Fetching: sqlite3-1.3.9.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.9
Fetching: daemons-1.1.9.gem (100%)
Successfully installed daemons-1.1.9
Fetching: thin-1.5.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed thin-1.5.1
Fetching: skinny-0.2.3.gem (100%)
Successfully installed skinny-0.2.3
Fetching: mailcatcher-0.5.12.gem (100%)
Successfully installed mailcatcher-0.5.12
Installing ri documentation for i18n-0.6.11
Installing ri documentation for multi_json-1.10.1
Installing ri documentation for activesupport-3.2.19
Installing ri documentation for eventmachine-1.0.3
Installing ri documentation for tilt-1.4.1
Installing ri documentation for mime-types-2.3
Installing ri documentation for mail-2.6.1
unable to convert "\x89" from ASCII-8BIT to UTF-8 for test/multipart/binary, skipping
Installing ri documentation for rack-1.5.2
Installing ri documentation for rack-protection-1.5.3
Installing ri documentation for sinatra-1.4.5
Enclosing class/module 'mSqlite3' for class Statement not known
Installing ri documentation for sqlite3-1.3.9
Installing ri documentation for daemons-1.1.9
Installing ri documentation for thin-1.5.1
Installing ri documentation for skinny-0.2.3
Installing ri documentation for mailcatcher-0.5.12
15 gems installed

[12:40 PM]-[root@packer-virtualbox-iso]-[/home/vagrant] 
# mailcatcher
mailcatcher: command not found

**Comment by sj26** [comment]
Closing this, make sure you use `rbenv rehash` or whatever your environment configuration requires to find new gem binstubs. :-)

**Comment by maniempire** [comment]
'rbenv rehash' worked for me too.

**Comment by leandromac** [comment]
'rbenv rehash' worked for me too =D

**Comment by colinxchristmas** [comment]
Worked for me 'rbenv rehash' as well. Rails 5 Ruby 2.3.1

**Comment by karangloify** [comment]
'rbenv rehash' worked for me 👍
