### ISSUE TITLE
Using Mailcatcher with Nitrous

### ISSUE THREAD

**Issue by MrSkinny** [sj26/mailcatcher#165]
Having trouble getting this to work with Cloud IDE Nitrous. Any thoughts? I've tried running `mailcatcher --http-ip 0.0.0.0` but I get the error:

```
Starting MailCatcher                                                                                                                                                            
~~> ERROR: Something's using port 1025. Are you already running MailCatcher?
```

This is what I see when I go to the appropriate port on the dev server:

Make sure to bind your server to host 0.0.0.0 (instead of localhost/127.0.0.1).

Please refer to this [support article](http://help.nitrous.io/faq-localhost/) for more details.

**Comment by sj26** [comment]
This is pretty old now so I'll close it. Please re-open if you still have this issue. You might like to try running `lsof -i -n` to see what processes are running on what ports to see if there's a collision.

**Comment by MrSkinny** [comment]
Sorry for very late reply. I didn't realize I needed to do a server reboot to shut the daemon off and change the http-ip settings. Ordinarily you can use the web interface to quit the daemon -- but that's no good if you have no access to it in the first place.  Or is there a CLI option to turn mailcatcher off?

**Comment by sj26** [comment]
Ah, right. You can always `lsof` or `ps` to find the mailcatcher process then `kill` it.
