### ISSUE TITLE
getting error when mail received second time: Exception: database table is locked

### ISSUE THREAD

**Issue by gpaullearn** [sj26/mailcatcher#166]
Exception: database table is locked
    Backtrace:
       /root/.rvm/gems/ruby-1.9.3-p484/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:67:in `step'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/sqlite3-1.3.9/lib/sqlite3/statement.rb:67:in `execute'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/mailcatcher-0.5.12/lib/mail_catcher/mail.rb:44:in `add_message'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/mailcatcher-0.5.12/lib/mail_catcher/smtp.rb:42:in `receive_message'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/smtpserver.rb:535:in `process_data_line'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/smtpserver.rb:196:in `receive_line'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:64:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/mailcatcher-0.5.12/lib/mail_catcher.rb:134:in `run!'
       /root/.rvm/gems/ruby-1.9.3-p484/gems/mailcatcher-0.5.12/bin/mailcatcher:4:in `<top (required)>'
       /root/.rvm/gems/ruby-1.9.3-p484/bin/mailcatcher:23:in `load'
       /root/.rvm/gems/ruby-1.9.3-p484/bin/mailcatcher:23:in `<main>'
       /root/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
       /root/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sj26** [comment]
Closing this issue due to age. Please re-open if you're still experiencing this.
