### ISSUE TITLE
Stop command

### ISSUE THREAD

**Issue by andrhamm** [sj26/mailcatcher#167]
It would be useful to have an easy way to kill an already running instance of mailcatcher. In my case, if I have mailcatcher already running (from a manual start), and I try to run foreman (which runs `mailcatcher -f`) it will cause the full foreman start to fail. Having a simple stop command would allow `mailcatcher stop && mailcatcher -f` in a Procfile.

Please let me know if I am missing an existing way to accomplish this. Thanks!

**Comment by sj26** [comment]
Run mailcatcher from foreman with `mailcatcher --foreground`. The daemonised mode is a convenience. I don't want to build service management semantics in -- that's your operating system's job. :-)

**Comment by numediaweb** [comment]
For windows users, you can stop/kill the mailcatcher by checking all running ruby tasks:
```
tasklist /FI "Imagename eq ruby.exe"
```
This will show a table like:
```
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
ruby.exe                      5252 Console                    2     85,232 K
```
Then kill the ruby process with
```
taskkill /pid 5252 /F
```

**Comment by ThomasLandauer** [comment]
See https://github.com/sj26/mailcatcher/issues/387#issuecomment-785456511 for another way, using curl.
