### ISSUE TITLE
Error while trying to delete single message through API

### ISSUE THREAD

**Issue by btofel** [sj26/mailcatcher#169]
Hi guys!

First of all thanks for great work with creating MailCatcher! It works like a charm, but I'm having problems with deleting single message through the API. I can easily delete all of them, but not a single one. When trying to do that I get the following error:

SQLite3::RangeException at /messages/1
bind or column index out of range
file: statement.rb location: bind_param line: 41

The thing is that the message with id 1 does exist and I can retrieve the body by calling GET http://intranet_hosl/messages/1.json or 1.html or whatever. But DELETE http://intranet_host/messages/1 still fails.

If that helps I can attach whole error message (HTML) returned by Mailcatcher.

Would be greateful for help as I'm using MC with some automated test cases and I need to be able to delete single messages, not all of them.

Cheers,
Bartek

**Comment by sj26** [comment]
This is very strange as I can't replicate this issue. Does it happen all the time, for every message?

**Comment by btofel** [comment]
Yes, all the time and for every message I tried deleting (meaning: not even once deletion of a single message via API succeeded).

Would attaching error page I get when calling API help in any way?

**Comment by sj26** [comment]
I still can't reproduce this.

Please try upgading to 0.6.0 with `gem install mailcatcher`. If you're still having issues please feel free to reopen this issue.
