### ISSUE TITLE
Support for CC, BCC

### ISSUE THREAD

**Issue by danshort** [sj26/mailcatcher#17]
I'd love to see support for CC and BCC. I'm just now picking up a little Ruby, so I'm going to try forking the project to see if it's something I could put together myself, but I figured I'd post it as an issue in case someone gets to it before I do :).

**Comment by archanid** [comment]
+1 cc/bcc support

**Comment by sj26** [comment]
As above, cc and bcc fields are displayed when you view an email. This is already implemented.

**Comment by dominh** [comment]
I have implemented Cc and Bcc recipients splitting.
https://github.com/sj26/mailcatcher/pull/296

**Comment by taiar** [comment]
@sj26  when you are sending a BCC e-mail, you must make sure that this address is not showed up. That said, differ the "recipients" to "bcc recipients" is a feature missing; not implemented.

**Comment by CHEWX** [comment]
Be great to have this support. You cannot debug a BCC issue as you cannot see them. Not even in the source.

**Comment by sj26** [comment]
BCC addresses should never appear in an email's message source, they are _Blind_ Carbon Copy addresses so you don't want to reveal them in the message.

BCC addresses do currently appear in the "To" recipients list in the MailCatcher interface. The "To" list is exactly the email addresses that your message will be delivered to.
