### ISSUE TITLE
Restarting mailCatcher fails after shutdown

### ISSUE THREAD

**Issue by pollyrobin** [sj26/mailcatcher#172]
After running mailCatcher and shutting it down trough the interface i can't restart it again.
When I try to start it with my outbound ip as the -ip syntax
I get the following error:
Starting MailCatcher 
~~> ERROR: Something's using port 1025. Are you alreay running MailCatcher?

This error will not appear if i start mailcatcher with no syntax

Whatever i do it won't come back online.
I have tried : 
Killing MailCatcher
netstat to look for Listening Ports no entrys found for port 1025
Literally nothing found whatsoever that mailcatcher is running.

Is this a bug or is this something else?

I am running mailcatcher 5.12 ruby 1.9.1 and debian 7

**Comment by sj26** [comment]
This is due to #182. Mailcatcher doesn't seem to quit correctly when asked under Ruby 2.1.5.

**Comment by fatuhoku** [comment]
Got the same issue with Ruby 2.2.4 on Mac.

mailcatcher does not stop at all even with `sudo kill <PID>`. `sudo kill -9 <PID>` did work however

**Comment by rhuancarlos** [comment]
funfou here ...

**Comment by rhuancarlos** [comment]
function here ..

**Comment by dspirovski** [comment]
I would like to run Mailcatcher on my computer but I am facing with some problems. I am using Ubunty 20.04. 
I installed Ruby version 2.7. I installed Mailcatcher with the following command: sudo gem install mailcatcher. Now, I should start Mailcatcher with the desired IP address, form example:

mailcatcher --ip 192.168. 1.1,

but I am getting the following message:
mailcatcher: command not found.

Could anyone tell me where is the problem, and how can I solve this?

**Comment by sj26** [comment]
@dspirovski please open as a new issue.

**Comment by grahamb** [comment]
I'm seeing this as well, Mailcatcher 0.8.2, Ruby 2.7 on RedHat Enterprise Linux 7. Mailcatcher is started via systemd, running `/usr/local/bin/mailcatcher --foreground --http-ip=x.x.x.x`. When try to restart mailcatcher via systemd, or stop it and try to run it manually, I get the same error as others here:

```
# systemctl stop mailcatcher
# mailcatcher --foreground --http-ip=x.x.x.x
Starting MailCatcher v0.8.2
~~> ERROR: Something's using port 1025. Are you already running MailCatcher?
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

Mailcacher is not running at this point. The only ruby processes running are our Rails app served by Passenger.

```
# ps -ef | grep mailcatcher
root      32864  32088  0 10:02 pts/0    00:00:00 grep --color=auto mailcatcher
```

Nothing is listening on either ports 1080 or 1025 at this point.

```
# netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:33492         0.0.0.0:*               LISTEN      92132/Passenger Rub
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1032/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1374/master
tcp        0      0 0.0.0.0:56737           0.0.0.0:*               LISTEN      1169/rpc.statd
tcp        0      0 0.0.0.0:514             0.0.0.0:*               LISTEN      1057/rsyslogd
tcp        0      0 0.0.0.0:45380           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      719/rpcbind
tcp        0      0 127.0.0.1:45265         0.0.0.0:*               LISTEN      92112/Passenger Rub
tcp6       0      0 ::1:25                  :::*                    LISTEN      1374/master
tcp6       0      0 :::42108                :::*                    LISTEN      1169/rpc.statd
tcp6       0      0 :::514                  :::*                    LISTEN      1057/rsyslogd
tcp6       0      0 :::111                  :::*                    LISTEN      719/rpcbind
tcp6       0      0 :::80                   :::*                    LISTEN      30448/httpd
tcp6       0      0 :::39282                :::*                    LISTEN      -
```

The only resolution I've found is to reboot.
