### ISSUE TITLE
Mailcatcher not catching mail after update to OSX Yosemite

### ISSUE THREAD

**Issue by Bartjuh4** [sj26/mailcatcher#173]
Hi,

Last week i updated my machine to osx yosemite and since then my mailcatcher does not catch mails anymore. Luckily they are not sended to there original recipient but testing applications is very difficult without the mailcatcher.

I saw this fix: http://forum.railsonmaui.com/t/yak-shaving-troubleshooting-with-mailcatcher/102

But this is not working for me, mailcatcher starts without any problems and the webinterface also works but it just doesn't catch mails. Please help!

Problem found, it is not the mailcatcher that is causing problems. It is MAMP Pro that doest deliver the emails to Mailcatcher. I am now sending mail directly with smtp and mailcatcher works!

**Comment by delwaterman** [comment]
I am having this same problem. Can you please describe your solution in more detail?

**Comment by feelpix** [comment]
I'm having the same problem. When I try to launch into console : 
php -r "mail('caffeinated@example.com', 'Mon Sujet', 'un envoi pour tester');"

I've got this in return : 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:932:in `recv_response'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:555:in `block in do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:942:in `critical'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:555:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:520:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
	from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
	from /Library/Ruby/Gems/2.0.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
	from /Library/Ruby/Gems/2.0.0/gems/mailcatcher-0.5.12/bin/catchmail:50:in `<top (required)>'
	from /usr/bin/catchmail:23:in `load'
	from /usr/bin/catchmail:23:in `<main>'

**Comment by josephecombs** [comment]
A workaround I found in the meantime is to run mailcatcher in the foreground with "mailcatcher -f", after which emails were caught and I would be able to view them on localhost:1080

**Comment by feelpix** [comment]
It's working for me too. Thanks. Please fix it anyway. This tool is very helpfull for me.

**Comment by sj26** [comment]
This seems to be related to #182, please track there.

**Comment by sepehr** [comment]
FTR, running mailcatcher with -f worked for me.
