### ISSUE TITLE
PHP configuration example

### ISSUE THREAD

**Issue by albancrommer** [sj26/mailcatcher#177]
The correct Apache vhost directive -at least for Debian 7- should read
php_admin_value sendmail_path "/usr/bin/env catchmail -f some@from.address"

As "php_value" (note the missing _admin_) doesn't work.

**Comment by sj26** [comment]
Ah, this must be something that has changed recently. I'll update the README.

**Comment by sj26** [comment]
Actually it looks like `php_value` should work: http://php.net/manual/en/configuration.changes.php

Perhaps there's something overriding your configuration? Anyways, this seems like an administrative configuration issue, not an issue with the general guidelines.

**Comment by albancrommer** [comment]
Thanks for the reply.

As much as I'd like to trust you, the PHP doc seems clear about the error.

Refering to http://php.net/manual/en/configuration.changes.php

    "php_value ... Can be used only with PHP_INI_ALL and PHP_INI_PERDIR"

And then this page ( http://php.net/manual/en/ini.list.php ) shows the option is not in this family

    "sendmail_path ...	PHP_INI_SYSTEM"

And, indeed, as a sysadmin I wouldn't like every looney to be able to tweak sendmail_path in a htaccess.

Sorry to be a bit rough, just trying to help, but did you even test before closing the issue ?

**Comment by sj26** [comment]
No I didn't try it, but without the details you've just provided above there didn't seem a need to change something I had previously tried which had worked. Sorry my skim of the PHP docs didn't pick up these changes at first glance. With these details, though, I'm happy to make the change. Thanks!

**Comment by albancrommer** [comment]
Ok cool, more than happy I could help ;)
