### ISSUE TITLE
Mailcatcher not showing attachments with accents in its filename

### ISSUE THREAD

**Issue by marcosgdf** [sj26/mailcatcher#181]
Version: mailcatcher (0.5.12)

Example:

![captura de pantalla 2014-12-18 a las 12 17 43](https://cloud.githubusercontent.com/assets/168744/5487251/f0372da2-86af-11e4-843d-0879efe2c297.png)

But in the source you can see there is one more attachment:

![captura de pantalla 2014-12-18 a las 12 18 28](https://cloud.githubusercontent.com/assets/168744/5487255/02b926f6-86b0-11e4-83f0-e2e3405d7f0a.png)

**Comment by sj26** [comment]
From what I can see of the source you've posted this should work.

Can you provide a full email source (like one from MailCatcher's Download button) which produces this problem?

**Comment by marcosgdf** [comment]
Sure! https://gist.github.com/marcosgdf/c51f5abe3f4d99506865

![captura de pantalla 2015-01-17 a las 16 13 19](https://cloud.githubusercontent.com/assets/168744/5789264/c5604548-9e63-11e4-9297-25ec0dfb1c5e.png)

**Comment by swaps19** [comment]
same thing is happening with me.
I have sent an attachment with the mail; its showing in the mail source but I cant see its link or anything else on UI.

**Comment by sj26** [comment]
I believe this is similar to many other issues about encoding. Your mail library is not correctly encoding these characters as quoted printable or similar. You should fix or update your mail library to get this working.
