### ISSUE TITLE
Add mailcatcher to gem file causes thin to become default webserver

### ISSUE THREAD

**Issue by ryanburnette** [sj26/mailcatcher#185]
Adding `gem "mailcatcher"` to my Gemfile in Rails 4.1.8 causes `thin` to become the default webserver. Is there a way to avoid this unintended consequence?

I realize this might be considered a support request rather than an issue so I created a [StackOverflow question](http://stackoverflow.com/questions/27769049/ignore-group-in-rails-gemfile). The context of my question is more general though.

**Comment by anthonator** [comment]
I posted a response to your SO question but the README specifically states to not put mailcatcher in your Gemfile.

**Comment by ryanburnette** [comment]
I saw that. Thanks.

I wish I was able to add it and have Rails ignore it though. Right now we have to manually remember to install `mailcatcher` as a system Gem. Doesn't seem optimal.

**Comment by rpocklin** [comment]
Same here, I added it as a development dependency.  It simply shouldn't default to thin, why?
