### ISSUE TITLE
Show the display name of the recipient

### ISSUE THREAD

**Issue by wynksaiddestroy** [sj26/mailcatcher#186]
If I send a mail with a recipients display name, mailcatcher will only show the recipients address instead of the display name or a combination of name and address.
For example a mail with the header destination field set to `To: Heffer Wolfe <heffer@aol.com>` is simply displayed as `To: heffer@aol.com` by mailcatcher.
Do I miss something that speaks against showing the display name?

Thanks in advance

**Comment by sj26** [comment]
The To field in the list of messages and the message header is the list of addresses that SMTP delivered to, not the contents of the To header in the actual email.

Check the Source version of your email for the To header.
