### ISSUE TITLE
ruby 2.2 error: warning: circular argument reference

### ISSUE THREAD

**Issue by chrishough** [sj26/mailcatcher#187]
Anyone have ideas on how to fix this in ruby 2.2.0?
```
/Users/chrishough/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

**Comment by leolandotan** [comment]
I'm getting this error and not receiving emails in mailcatcher from Drupal. i just did an:
1. ubuntu 14.04 install and got latest updates
2. lamp-server
3. installed RVM (stable)
4. rvm default@mailcatcher --create do gem install mailcatcher
5. rvm wrapper default@mailcatcher --no-prefix mailcatcher catchmail
6. upadted /etc/php5/apache2/php.ini with sendmail_path = "/home/leotan/.rvm/bin/catchmail"
7. updated /etc/php5/apache2/php.ini with smtp_port = 1025

/home/leotan/.rvm/gems/ruby-2.2.0@mailcatcher/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.

**Comment by thiagogsr** [comment]
+1. The emails coming not using Rails :/

**Comment by goddamnyouryan** [comment]
+1 Using rails 4.1.9 and Ruby 2.2 and mails aren't being delivered.

**Comment by AdaevK** [comment]
+1 mails are not delivered, Ruby 2.2

**Comment by john-denisov** [comment]
Use gem version from github.
In your Gemfile:

    gem 'mailcatcher', :git => 'git://github.com/sj26/mailcatcher.git'

**Comment by sj26** [comment]
Ruby 2.2 won't work yet because eventmachine 1.0.4 has bugs preventing mailcatcher working, and 1.0.3 doesn't support ruby 2.2. Will keep you posted.

**Comment by sj26** [comment]
(Make sure you're installing mailcatcher as a gem, not with bundler, and run mailcatcher with ruby < 2.20.)

**Comment by sj26** [comment]
Please upgrade to version 0.6.0 with `gem install mailcatcher`

**Comment by chrishough** [comment]
![screen shot 2015-01-29 at 9 12 45 am](https://cloud.githubusercontent.com/assets/744056/5962195/03345c42-a797-11e4-9beb-30b64659b660.png)

Confirmed, thank you

**Comment by leolandotan** [comment]
Sorry to ask this but is it the same process still when using RVM? or before doing the steps i should use ruby 1.9?
