### ISSUE TITLE
Improve catchmail to accept same arguments as sendmail

### ISSUE THREAD

**Issue by macinjosh** [sj26/mailcatcher#188]
I am not able to get mailcatcher to work with [Pear Mail](http://pear.php.net/manual/en/package.mail.mail.factory.php) via the sendmail method.

When I have either a `Return-Path` or `From` header I get the following error:

    $ php -a
    php > require_once('Mail.php');
    php > $mail = Mail::factory('sendmail', array('sendmail_path' => '/usr/bin/env catchmail'));
    php > $mail->send('example@example.com', array('Return-Path' => 'no-reply@example.com'), 'Test Message');
    /var/lib/gems/1.9.1/gems/mailcatcher-0.5.12/bin/catchmail:48:in `read': No such file or directory - example@example.com (Errno::ENOENT)
        from /var/lib/gems/1.9.1/gems/mailcatcher-0.5.12/bin/catchmail:48:in `<top (required)>'
        from /usr/local/bin/catchmail:23:in `load'
        from /usr/local/bin/catchmail:23:in `<main>'
    php >

**Comment by macinjosh** [comment]
The syntax Pear Mail uses to call sendmail is like this:

    /usr/bin/env catchmail -i -f'no-reply@example.com' -- 'test@example.com' < email.txt

It seems that mailcatcher is unable to parse this input.

    /var/lib/gems/1.9.1/gems/mailcatcher-0.5.12/bin/catchmail:48:in `read': No such file or directory - test@example.com (Errno::ENOENT)
        from /var/lib/gems/1.9.1/gems/mailcatcher-0.5.12/bin/catchmail:48:in `<top (required)>'
        from /usr/local/bin/catchmail:23:in `load'
        from /usr/local/bin/catchmail:23:in `<main>'

**Comment by sj26** [comment]
Good point. Fixed on master.
