### ISSUE TITLE
Net::ReadTimeout: Net::ReadTimeout

### ISSUE THREAD

**Issue by hoang1417** [sj26/mailcatcher#191]
I'm using ruby `2.0.0p353` and `Rails 4.1.5` with `mailcatcher 0.5.12`.

The error ***Net::ReadTimeout: Net::ReadTimeout*** appears every time I send an email.

My config about mailer in `config/environments/development.rb`:
```ruby
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_url_options = { host: 'localhost:3000' }
  config.action_mailer.perform_deliveries = true

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = { :address => "localhost", :port => 1025 }
```

Full error messages:
```ruby
Net::ReadTimeout: Net::ReadTimeout
from /.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
```

Can someone help figure out the reason? 
Many thanks.

**Comment by danlo** [comment]
#182 ?

**Comment by hoang1417** [comment]
:+1: @danlo. Yes, it is. I thought the issue was different, thanks!

**Comment by hoang1417** [comment]
PS: Both solutions work:

```ruby
mailcatcher -f -v
```

or make sure you're using eventmachine version 1.0.3

```ruby
gem uninstall eventmachine -v 1.0.4
gem install eventmachine -v 1.0.3
```

**Comment by esbanarango** [comment]
:+1:

**Comment by kartikluke** [comment]
Can we have this fixed by setting the dependency on the right version of eventmachine. @sj26

**Comment by sj26** [comment]
Please try mailcatcher 0.6.0pre1 (`gem install mailcatcher --pre`)

**Comment by davity** [comment]
mailcatcher 0.6.0pre1 working fine

**Comment by sj26** [comment]
mailcatcher 0.6.1 is out which works with eventmachine up to 1.0.5, and restricts future upgrades.

**Comment by hoang1417** [comment]
Yes, mailcatcher (0.6.1) works with eventmachine (1.0.5). Thanks @sj26 :+1:

**Comment by rolandoalvarado** [comment]
Thanks @hoang1417  running in foreground solves my issue.

mailcatcher 0.5.12
ruby 2.6.2
rails 5.1.7
