### ISSUE TITLE
1-2 minute delay in mail sending

### ISSUE THREAD

**Issue by Locutus83** [sj26/mailcatcher#192]
I'm trying to nail down something in our automated tests.  We use Behat to test our changes that we make in order to verify we didn't break anything.  However, last week, the tests started to fail because the email system (Mailcatcher) seemed to get the emails 1-3 minutes after our system sent them.

I'm trying to find a way to get them back to 1-5 seconds that it used to take because waiting for them has added too much time to the automated test process; making it difficult to utilize on every commit as we have been doing.

Any help tracking this down would be appreciated.

**Comment by sj26** [comment]
Are you using the mailcatcher web interface in an automated browser, or treating it as an API?

If the web interface, try reloading the page before making your assertions. Maybe the websockets aren't working as expected. If so, let me know when browser you're using.

If you're using it via an API then the email should be available as soon as your app has finished delivering it. I'd suggest watching the mailcatcher logs (the standard output, you might like to run it with `--foreground`) during delivery. There will be a message for every mail received the moment it is fully delivered. If you don't see a message when you expect then your app isn't completing the mail delivery when you expect.

Hope this helps.

**Comment by sj26** [comment]
Please try upgrading to version 0.6.0 with `gem install mailcatcher`

If you're still having issues feel free to reopen the issue.
