### ISSUE TITLE
Mailcatcher does not catch any mails

### ISSUE THREAD

**Issue by john-999** [sj26/mailcatcher#193]
Emails are being sent according to the log file, but Mailcatcher (I've just installed the latest version) does not show anything.

I have restarted my machine, relaunched the web server and Mailcatcher, but the issue persists, with:

- Rails 4.2.0
- Ruby 2.1.2p95

In development.rb, I have set:

    config.action_mailer.smtp_settings = {
      address: 'localhost',
      port: 1025
    }
    config.action_mailer.delivery_method = :smtp

(Also, I haven't included mailcatcher in the Gemfile.)

EDIT:

Although the first "GET http://127.0.0.1:1080/messages   200 OK   5ms" has passed ok, after a few minutes after having launched the Mailcatcher webinterface, Firebug reports an error:

    "Firefox can't establish a connection to the server at ws://127.0.0.1:1080/messages.
    http://127.0.0.1:1080/javascripts/application.js
    Line 385"

**Comment by sj26** [comment]
Have you tried refreshing the page?

**Comment by john-999** [comment]
Yes, but unfortunately it didn't change anything.

**Comment by sj26** [comment]
What do the rails logs show? Have you tried running `mailcatcher --foreground` and watching those logs?

**Comment by sj26** [comment]
Please try upgrading to version 0.6.0 with `gem install mailcatcher`

**Comment by sj26** [comment]
mailcatcher 0.6.1 is out which works with eventmachine up to 1.0.5, and restricts future upgrades.

**Comment by john-999** [comment]
I have installed mailcatcher (0.6.1), but it still doesn't catch any mails.

I have noticed that my eventmachine is at 1.0.6 - if I understand you correctly, that would be the issue here?

**Comment by sj26** [comment]
@john-999 mailcatcher 0.6.1 should only load eventmachine < 1.0.5. Try running with `--foreground` and watch the logs.

**Comment by lancedikson** [comment]
So, I have the same issue :(

Environment: 
 - Rails 4.1.7
 - ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
 - mailcatcher 0.6.1

I send 2 messages async with sidekiq:

```
UserMailer.delay.debt_manager(model.terminal.user_id, model.id)
UserMailer.delay.debt_assistant(model.terminal.user_id, model.id)
```

and it works pretty:

```
2015-02-06T14:49:36.531Z 10008 TID-ox0xokpb0 Sidekiq::Extensions::DelayedMailer JID-9c1255a5873768a6eccc0d25 INFO: start
2015-02-06T14:49:36.539Z 10008 TID-ox0xoo8ao Sidekiq::Extensions::DelayedMailer JID-d655b32f9f366ef6ab7a0dcf INFO: start
2015-02-06T14:49:39.768Z 10008 TID-ox0xokpb0 Sidekiq::Extensions::DelayedMailer JID-9c1255a5873768a6eccc0d25 INFO: done: 3.236 sec
2015-02-06T14:49:40.231Z 10008 TID-ox0xoo8ao Sidekiq::Extensions::DelayedMailer JID-d655b32f9f366ef6ab7a0dcf INFO: done: 3.691 sec
```

But, mailcatcher doesn't catch any mails. Key `--foreground` doesn't help somehow — it doesn't write any errors or info messages:

```
iMac:adrenaline-server lancedikson$ mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

**Comment by IvRRimum** [comment]
+1

```
$ mailcatcher -f -v
Starting MailCatcher
==> smtp://127.0.0.1:1025
/Users/karliscudars/.rvm/gems/ruby-2.5.0@podcastmojo/gems/thin-1.5.1/lib/thin/server.rb:
104: warning: constant ::Fixnum is deprecated
==> http://127.0.0.1:1080
```

Doesn't catch device user confirmation mail.

development.rb
```
  config.action_mailer.default_url_options = { host: '127.0.0.1', port: 1025 }
  config.action_mailer.delivery_method = :smtp
```

**Comment by sj26** [comment]
If you’re not seeing anything in the mailcatcher log when running with foreground then your app is not correctly configured to send messages to the right place. Please check your app configuration and log. Beyond that there’s not much I can do from this end, sorry.

**Comment by IvRRimum** [comment]
Yeah, the weird thing. This is what rails gives me:
```
Traceback (most recent call last):
        1: from (irb):1
Errno::ECONNREFUSED (Connection refused - connect(2) for "localhost" port 25)
```

This is when i try to send an user confirmation mail from rails c

**Comment by IvRRimum** [comment]
This works for rails5

`config/environments/development.rb`:
```
  # Host and port of current system
  # For development enviroment we are using gem called mailcatcher, refer to google for more info
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address:              '127.0.0.1',
    port:                 1025,
  }
```

**Comment by PatrickKing** [comment]
If you're having trouble with Rails and are new to working with email, do remember that it's not enough to create an ActionMailer instance, you also need to call `deliver` with it:

`MyMailer.create_email.deliver`

**Comment by durrellchamorro** [comment]
For some reason it only works for me if I run the emails inline and skip the whole background job processing in redis. Instead of changing all the emails calls from `deliver_later` to `deliver` everywhere in the code and then putting that pack before I push I just did this inside config/initializers/sidekiq.rb

```
if Rails.env.development?
  require 'sidekiq/testing'
  Sidekiq::Testing.inline!
end
```
https://makandracards.com/makandra/28125-perform-sidekiq-jobs-immediately-in-development
