### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by jvanbaarsen** [sj26/mailcatcher#198]
The website mailcatcher.me needs to be updated to reflect the latest version! If its opensource somewhere I would be happy to provide a patch.

**Comment by jvanbaarsen** [comment]
Ah, it might be as simple as just creating a new Git tag of the latest release :)

**Comment by sj26** [comment]
Not quite, but close. I have a little script which scrapes the readme, renders it, and rewrites it a bit. Need to set it up with a git webhook at some point. Or use github pages.

In any case, done.

**Comment by ashleyconnor** [comment]
Looks like it's drifted again http://mailcatcher.me
