### ISSUE TITLE
From in the list and details view not correct (it's the return-path)

### ISSUE THREAD

**Issue by andywenk** [sj26/mailcatcher#199]
Hi,

first of all thanks for awesome `mailcatcher`. I am using it with Rails in development mode and it's a hughe help.

I have set up the return_path in a Rails Mailer. When sending the email and looking at it in mailcatcher at http://localhost:1080/, the field `From` in the list and the `From` field in the detail view is not the `From` address but the `Return-Path` address. If one is looking to the source, it is correct.

I guess this is a little bug.

Find a screenshot at:

https://drive.google.com/open?id=0B2xXhdpvuHcGaE1WM2dxcXlDaDQ&authuser=0

All the best 

Andy

**Comment by sj26** [comment]
Hi Andy,

The "to" and "from" in Mailcatcher shows how your email is actually being sent; who is being sent a copy of your email via SMTP and where your app is claiming the email is from via SMTP. The headers are actually different.

This seems to cause a lot of confusion so I'm going to introduce an SMTP log tab soon showing the SMTP session log, and change these fields to "recipients" and "/sender"

**Comment by andywenk** [comment]
Hi Samuel,

thanks a lot for your fast reply. Yes this is confusing because obviously two different things are named the same way - namely 'From'.

Thanks for your work on this.

Cheers

Andy
