### ISSUE TITLE
Mount MailCatcher in Rails App

### ISSUE THREAD

**Issue by Smolations** [sj26/mailcatcher#200]
Sidekiq is an example of a gem with it's own UI being mountable in an existing rails project:

```ruby
# in routes.rb
require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq-ui'
```

MailCatcher currently requires a completely separate UI served at a completely autonomous address on `localhost`. I would like to request that this "mountable" functionality be added to MailCatcher so that it becomes a utility accessible from the rails app domain instead of it's own URL.

**Comment by pineapplethief** [comment]
+1 for that

**Comment by sj26** [comment]
MailCatcher needs to listen on SMTP too, rack is not enough. This cannot be done.

**Comment by sj26** [comment]
(If you would like something more rails integrated maybe try https://github.com/basecamp/mail_view)

**Comment by sj26** [comment]
(There is probably also room for something which integrates more deeply with rails and hijack's ActionMailer's delivery method in development and serves them via rack without using smtp at all. MailCatcher was designed as a general solution to the problem, though.)
