### ISSUE TITLE
Logging with timestamps

### ISSUE THREAD

**Issue by bergerjac** [sj26/mailcatcher#202]
thoughts about showing a timestamp..? `"==> SMTP: Received message at {timestamp}...`

in [receive_message](https://github.com/sj26/mailcatcher/blob/eff638f9205fe67359dc2/lib/mail_catcher/smtp.rb#L47)

**Comment by sj26** [comment]
Mail messages generally have time inside them, or folks pipe output into logging tools which can time-tag lines if they like. Is there a compelling use-case to do so?

**Comment by bergerjac** [comment]
Good point. Just thought it would be convenient to have the timestamp piped out by default. If I'm doing a lot of testing it's convenient to see it in the terminal.

**Comment by sj26** [comment]
This will be done as part of #298.
