### ISSUE TITLE
Clear doesn't work across instances

### ISSUE THREAD

**Issue by ghengeveld** [sj26/mailcatcher#203]
When you have the app open twice and you clear messages in one, the other doesn't update, leading to unexpected results when new messages arrive:

![schermafbeelding 2015-02-06 om 16 13 43](https://cloud.githubusercontent.com/assets/321738/6081707/ff00afe6-ae1b-11e4-8955-c56597984d70.png)

**Comment by sj26** [comment]
Yeah this is a long standing issue. Individual deletes aren't replicated across instances either. Time to react/relay the whole thing? :P

**Comment by sj26** [comment]
This is solved in the latest version.
