### ISSUE TITLE
UI label shows 'from' but 'sender' is displayed

### ISSUE THREAD

**Issue by bergerjac** [sj26/mailcatcher#204]
UI label shows [`from`](https://github.com/sj26/mailcatcher/blob/master/views/index.erb#L41).

[sender](https://github.com/sj26/mailcatcher/blob/master/assets/javascripts/mailcatcher.js.coffee#L225) displayed

according to the `mail` gem, [from](https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L621) / [sender](https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L1011), may not be the same.

**Comment by sj26** [comment]
By design. MailCatcher is an SMTP tool, so show the SMTP details in the table list. The "From" in the message display is the RFC822 From header.

**Comment by bergerjac** [comment]
true, MailCatcher is an SMTP tool. I just checked out the RFC822 and it shows that `From` and `Sender` are not always the same values.

example from http://www.w3.org/Protocols/rfc822/ A.2.7.

```
       George's secretary sends out a message which was authored
   jointly by all the members of a committee.  Note that the name
   of the committee cannot be specified, since <group> names  are
   not permitted in the From field.

       From:   Jones@Host,
               Smith@Other-Host,
               Doe@Somewhere-Else
       Sender: Secy@SHost
```

Maybe you can help me understand :)

**Comment by sj26** [comment]
`From` and `Sender` are both RFC822 headers, part of the message in the lower pane. SMTP's FROM is provided in the SMTP exchange, per https://tools.ietf.org/html/rfc821#section-3.1. The table is SMTP details, and is how/where the message would be delivered. The message details, like the From header, is how a message will be displayed in a mail client.

**Comment by bergerjac** [comment]
Thanks for your replies and the link to RCF821. I've got enough info to understand better.

**Comment by iandunn** [comment]
IMO, this is really counter-intuitive. I expected the label to match the header being displayed next to it, and I think the vast majority of users would too.

Previously: #199, #133
