### ISSUE TITLE
Update documentation to include init script for linux installations

### ISSUE THREAD

**Issue by barryrld** [sj26/mailcatcher#206]
I wanted to have mailcatcher run on boot so I created the following script (at bottom) in /etc/init.d/mailcatcher, made the executable with:

    # chmod 755 /etc/init.d/mailcatcher

and then run this command to add init script to boot/shutdown system processes:

    # update-rc.d mailcatcher defaults

Here's the script for /etc/init.d/mailcatcher:

```
#! /bin/sh
### BEGIN INIT INFO
# Provides: mailcatcher
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: mailcatcher
# Description: This file starts and stops mailcatcher daemon
# 
### END INIT INFO

MAILCATCHER_EXEC=`which mailcatcher`

case "$1" in
 start)
   MAILCATCHER --http-ip 0.0.0.0
   ;;
 stop)
   killall mailcatcher
   sleep 5
   ;;
 restart)
   killall mailcatcher
   sleep 5
   MAILCATCHER --http-ip 0.0.0.0
   ;;
 *)
   echo "Usage: mailcatcher {start|stop|restart}" >&2
   exit 3
   ;;
esac
```

This has been tested and works on Ubuntu 14.04, although as it's quite simple it will probably work on most linux installations (Debian at least). I'm not sure how you'd do this on OSX, so feedback welcome!

Note that I've added --http-ip 0.0.0.0 to the executable to make it world available- you may want to remove this if you're concerned about security.

Could this be added in the README or docs somewhere?

Thanks for such a great module!

**Comment by zymsys** [comment]
I think this is a great idea. I had to change the lines that execute mailcatcher to use $MAILCATCHER_EXEC instead of just MAILCATCHER, and I tweaked the -http-ip to be -ip for both services, and I used my staging server's IP address so open it up to our private network for devs and QA to access. I ran it on Ubuntu 12.04 just fine.

**Comment by ghuntley** [comment]
Additionally here's a formula to automatically setup mailcatcher via SaltStack:

https://github.com/saltstack-formulas/mailcatcher-formula

**Comment by sj26** [comment]
This only works on systems with sysv init scripts. systemd, upstart and launchd users will need different configurations, among other possibilities. Adding instructions for how to start on every possible configuration would make the readme very long. Instead I'd rather leave people to google "how to run service at system start up" or similar and gain some knowledge about their particular systems.

**Comment by dooblem** [comment]
I had to add PATH for which command to work in init script. (otherwise the init script is working from interactive shell, but not at boot)

Complete script:
```
#! /bin/sh
### BEGIN INIT INFO
# Provides: mailcatcher
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: mailcatcher
# Description: This file starts and stops mailcatcher daemon
# 
### END INIT INFO

PATH=/usr/local/bin:/usr/bin:/bin
MAILCATCHER_EXEC=`which mailcatcher`

case "$1" in
 start)
   MAILCATCHER --http-ip 0.0.0.0
   ;;
 stop)
   killall mailcatcher
   sleep 5
   ;;
 restart)
   killall mailcatcher
   sleep 5
   MAILCATCHER --http-ip 0.0.0.0
   ;;
 *)
   echo "Usage: mailcatcher {start|stop|restart}" >&2
   exit 3
   ;;
esac
```
