### ISSUE TITLE
CentOS6 dependency on i18n

### ISSUE THREAD

**Issue by hdi-kw** [sj26/mailcatcher#213]
Right now I am not able anymore to install mailcatcher on CentOS6 which only has ruby 1.8.7, but which is still the required_ruby_version according to mailcatcher.gemspec.
The problem seems to be i18n. I can install an older version of i18n with "gem install i18n -v 0.6.11", but when I install mailcatcher I get the same error about i18n again:
```shell
$ gem install mailcatcher
ERROR:  Error installing mailcatcher:
  i18n requires Ruby version >= 1.9.3
```
Is it possible to set a dependency in mailcatcher.gemspec for i18n <= 0.6.11 depending on the ruby version?

**Comment by hdi-kw** [comment]
Got it to work in CentOS6 with ruby 1.8.7 with this combination:
```
$ /usr/bin/gem install --no-rdoc mailcatcher:0.5.12 i18n:0.6.11 eventmachine:1.0.3
```
Had to go back to 0.5.12 otherwise it always wanted a i18n that is not compatible, eventmachine was needed for the background operation which was fixed in mailcatcher 0.6.1 (Issue #182).

**Comment by gusdecool** [comment]
tried your solution and got this:

```
gem install --no-rdoc mailcatcher:0.5.12 i18n:0.6.11 eventmachine:1.0.3
ERROR:  Could not find a valid gem 'mailcatcher:0.5.12' (>= 0) in any repository
ERROR:  Could not find a valid gem 'i18n:0.6.11' (>= 0) in any repository
ERROR:  Could not find a valid gem 'eventmachine:1.0.3' (>= 0) in any repository
```

**Comment by hdi-kw** [comment]
I had to put mailcatcher as last argument, otherwise I had to run the command twice, but it works still. I have CentOS6 with:
```
$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
$ gem --version
2.4.6
$ gem uninstall mailcatcher i18n eventmachine
$ gem install --no-rdoc --no-ri i18n:0.6.11 eventmachine:1.0.3 mailcatcher:0.5.12
Fetching: i18n-0.6.11.gem (100%)
Successfully installed i18n-0.6.11
Fetching: eventmachine-1.0.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.3
Fetching: mailcatcher-0.5.12.gem (100%)
Successfully installed mailcatcher-0.5.12
3 gems installed
```
Do you have network connection and internet to fetch them?

**Comment by gusdecool** [comment]
yes i do have internet connection.

In the end, i use RVM with ruby 1.9.x and install mailcatcher 0.6.1.
Now it's working perfectly.
