### ISSUE TITLE
Update sqlite gem

### ISSUE THREAD

**Issue by mehulkar** [sj26/mailcatcher#215]
When I install the mailcatcher gem, I get this message:

```
#######################################################

Hello! The sqlite3-ruby gem has changed it's name to just sqlite3.  Rather than
installing `sqlite3-ruby`, you should install `sqlite3`.  Please update your
dependencies accordingly.

Thanks from the Ruby sqlite3 team!

<3 <3 <3 <3

#######################################################
```

**Comment by mehulkar** [comment]
Errr, that's weird, I added `gem mailcatcher` to my Gemfile, and ran `bundle install` and it installed `0.2.4` for me. Which has the old dependency.. 

Is that a bundler problem for me locally?

**Comment by mehulkar** [comment]
Closing this as it's not actually an issue.

**Comment by sj26** [comment]
https://github.com/sj26/mailcatcher#bundler

**Comment by mehulkar** [comment]
Touché. My fault. Thanks Sam!

On Wednesday, March 11, 2015, Samuel Cochran <notifications@github.com>
wrote:

> https://github.com/sj26/mailcatcher#bundler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sj26/mailcatcher/issues/215#issuecomment-78404783>.
>


-- 

------
Mehul Kar
@mehulkar
