### ISSUE TITLE
RubyGems shows min Ruby as 1.8.7, but ActiveSupport/i18n requires 1.9.3

### ISSUE THREAD

**Issue by rmccue** [sj26/mailcatcher#216]
https://rubygems.org/gems/mailcatcher shows 1.8.7 as the min, but trying to install it with that gives:

> ERROR: Error installing mailcatcher: ==> default: i18n requires Ruby version >= 1.9.3.

(Via Chassis/mailcatcher#2)

**Comment by sj26** [comment]
Fixed in 134a99c9c1a2f75cbe1c94f75cbb58959a0176dc.
