### ISSUE TITLE
Set mail count in title

### ISSUE THREAD

**Issue by lichtamberg** [sj26/mailcatcher#218]
It would be great to show the current amount of mails in the html header/title, sou you can see that new mails have been received, just by looking at the browser tabs name - so you dont have to switch your browser tab to see if there were mails sent...?

Thanks!

**Comment by espen** [comment]
Mailcatcher already does this.

**Comment by lichtamberg** [comment]
I don't know... For me it didn't work in Firefox?
I added a pull request for this some time ago...

https://github.com/sj26/mailcatcher/pull/219

**Comment by espen** [comment]
Sorry, it is already displaying this in favicon - not in title. The favicon works for me in Firefox though.

**Comment by lichtamberg** [comment]
Ah, you are right. Didn't see this before, thanks. But I would prefer this number also in the page title, since its easier to read from my point of view.

**Comment by lichtamberg** [comment]
Also for me it looks like that the favicon solution doesn't work properly. I have f.e. 2 Mails in my inbox and the favicon still shows only one....

![bildschirmfoto 2015-04-17 um 13 01 40](https://cloud.githubusercontent.com/assets/10075/7200898/f062a71a-e501-11e4-8767-effd41cb8488.png)

**Comment by lichtamberg** [comment]
Only when I reload the page completely with clearing the cache, the favicon updates again... Normal reload doesn't update the favicon to the correct mail count.

**Comment by espen** [comment]
What browser version? Works fine for me. Latest FF on OSX.

**Comment by sj26** [comment]
This is working in Safari, Firefox and IE for me. If you can replicate with a patch it would be much appreciated.
