### ISSUE TITLE
native extensions do not build on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by JamesChevalier** [sj26/mailcatcher#220]
A very similar issue was reported over at [ruby-unf](https://github.com/knu/ruby-unf/issues/11), so I'm not sure if this is going to turn out to be a mailcatcher-specific issue or not...

I'm running `rvm default@mailcatcher --create do gem install mailcatcher` and getting this error:

```
Fetching: eventmachine-1.0.5.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing mailcatcher:
  ERROR: Failed to build gem native extension.

    /Users/me/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150413-20149-17idxk2.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
In file included from ./project.h:29:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:439:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/me/.rvm/gems/ruby-2.2.2@mailcatcher/gems/eventmachine-1.0.5 for inspection.
Results logged to /Users/me/.rvm/gems/ruby-2.2.2@mailcatcher/extensions/x86_64-darwin-14/2.2.0/eventmachine-1.0.5/gem_make.out
```

I was able to reproduce the problem with multiple ruby versions: 2.1.5, 2.1.6, 2.2.1, and 2.2.2.

I've tried a few things, so far - none of which have helped or changed anything:

- Installed the latest Command Line Tools
- Reinstalled the apple-gcc42 package in homebrew
- Installed gcc5 via homebrew (a long shot based on other gcc* packages being present)
- Removed all gcc* homebrew packages that were present (another long shot)

**Comment by JamesChevalier** [comment]
I apologize, the failure is actually occurring during the `eventmachine` installation. It doesn't seem directly tied to mailcatcher at all. I've tried installing the latest version of that (1.0.7), but it fails in the same manner. I've also got a coworker on Mac OS X 10.10.3 who was able to install mailcatcher just fine, so I'm not expecting there to be anything you'll be able to do here.

Thanks for a great tool!

**Comment by JamesChevalier** [comment]
OK, I just figured out a fix for my similar issue ... Just in case it's helpful - I had to install `Command Line Tools (OS X 10.10) for Xcode - Xcode 6.2` from the Download for Apple Developers page ... the version for Xcode 6.3 did not work for me.

**Comment by JamesChevalier** [comment]
Quick update for anyone who happens across this now...

Xcode 6.3.1 was released, which fixes this. Also Command Line Tools 6.3 with a release date of Apr 21, 2015 will fix this.

**Comment by henrik** [comment]
@JamesChevalier Thank you! Got the same error and updating Command Line Tools version 6.3 via App Store (id didn't offer me 6.3.1) fixed it.

**Comment by potomak** [comment]
@JamesChevalier Thanks.
