### ISSUE TITLE
Add support for a --pidfile option

### ISSUE THREAD

**Issue by t0xicCode** [sj26/mailcatcher#223]
When starting MailCatcher as a daemon, there is no way to have it write its PID to a file. This would be extremely useful when starting MailCatcher as a daemon, as it would make killing the process by PID easier.

**Comment by Cervajz** [comment]
:+1: Totally agree.

**Comment by sj26** [comment]
No, thank you. I consider this a non-feature of mailcatcher. Process supervision belongs to your operating system. See #46.

To daemonise as a system service which can be sent signals please use something like upstart, systemd, or launchctl, or start-stop-daemon in combination with `mailcatcher --foreground`.
