### ISSUE TITLE
sendmail_path "/usr/bin/env mailcatcher" no longer works after PHP update

### ISSUE THREAD

**Issue by onshop** [sj26/mailcatcher#224]
Our hosting company updated PHP from 5.3.3 to 5.4.0 and catchmail stopped working. Calls to PHP mail() returned false.

When I changed the sendmail_path to:

"/usr/local/rvm/wrappers/default/catchmail"

It started working again. I suspect that the new binary may be using FPM and that this caused a change in behaviour. I thought I let you know in case you think it needs to be flagged up in your documentation. I had to hunt around forums for a fix.

**Comment by mslabko** [comment]
Confirm this issue for my instance 
Ubuntu 14.04.1 LTS, php-fpm 5.6.14

At the same time from cli it working from beginning.

**Comment by sj26** [comment]
This is a problem with the system configuration, not something mailcatcher can fix. If you have this issue, make sure you're using an absolute path to catchmail and that it uses an absolute path to ruby. The [RVM wrapper instructions](https://github.com/sj26/mailcatcher#rvm) should help.
