### ISSUE TITLE
Use relative path for assets

### ISSUE THREAD

**Issue by mathewpeterson** [sj26/mailcatcher#225]
Currently the assets are hard coded for the domain root. E.G. "/assets/mailcatcher.css"

This becomes a problem when we try and put mailcatcher behind a proxy that would proxy requests from "/mailcatcher" to "http://127.0.0.1:1080/"

**Comment by fdrouet** [comment]
I agree that it is a painful limitation

**Comment by sj26** [comment]
Closed in favour of #227.
