### ISSUE TITLE
Mailcatcher prevents using latest version of `thin` web server

### ISSUE THREAD

**Issue by jarmo** [sj26/mailcatcher#226]
Currently `mailcatcher` depends of `skinny`, which has a `thin` dependendy of version `~> 1.5.0`.

This means that we are unable to upgrade `thin` to `1.6`. Unfortunately there is no newer version of `skinny` available as well.

**Comment by m1foley** [comment]
This is the PR over at the Skinny gem: https://github.com/sj26/skinny/pull/3

**Comment by sj26** [comment]
Thin 1.6 breaks mailcatcher exiting cleanly. This will need some more work.

**Comment by sj26** [comment]
Yeah I'm closing this in favour of removing Thin completely as part of #298
