### ISSUE TITLE
UI does not warn when Javascript is disabled

### ISSUE THREAD

**Issue by onshop** [sj26/mailcatcher#233]
Could the UI display a message/warning if JavaScript is disabled please?

**Comment by everblut** [comment]
Something like this?

![example](https://cloud.githubusercontent.com/assets/1256959/19711687/17f1c704-9afd-11e6-9478-789055b5ebdb.png)

**Comment by onshop** [comment]
It was a long time ago so I don't quite recall the circumstances but I wasn't aware that my browser had JS disabled so something more explicit provided by the UI would be great.

**Comment by sj26** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/14028/126023680-69a1a329-34cc-4c86-8032-d7c24802c4f1.png">
