### ISSUE TITLE
Sqlite 3 error

### ISSUE THREAD

**Issue by fede91it** [sj26/mailcatcher#237]
Installing Mailcatcher on Windows goes fine, but when I'm launch with mailcatcher command, this is what che console reports:

C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher/mail.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:20:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/mailcatcher:3:in `<top (required)>'
        from C:/Ruby22-x64/bin/mailcatcher:23:in `load'
        from C:/Ruby22-x64/bin/mailcatcher:23:in `<main>'

**Comment by bezin** [comment]
Same for me. According to some sources, this is due to an incompatability of sqlite and newer Ruby versions. As far as I oversee things, there is no fix available yet except compiling sqlite yourself.

https://github.com/sparklemotion/sqlite3-ruby/issues/150
https://www.ruby-forum.com/topic/6874307

**Comment by kenorb** [comment]
You need to install `libsqlite3`, e.g.:

    sudo apt-get install libsqlite3-dev

See: [#144]

**Comment by sj26** [comment]
@kenorb that is not a solution for windows.

@fede91it, @bezin: it sounds like your ruby and sqlite installations are having some issues, probably best tracked in the sqlite gem. Sounds like that issue has been resolved anyway so maybe try updating the sqlite gem and running mailcatcher again. Otherwise please follow up in the sqlite gem.
