### ISSUE TITLE
Database table is locked

### ISSUE THREAD

**Issue by swati-kpisoft** [sj26/mailcatcher#238]
Hi All,

After starting mailcatcher, first email is received perfectly. After that below exception is coming.

Please help me in resolving.

Exception: database table is locked
    Backtrace:
       /usr/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:67:in `step'
       /usr/lib/ruby/gems/2.2.0/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:67:in `execute'
       /usr/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher/mail.rb:44:in `add_message'
       /usr/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher/smtp.rb:46:in `receive_message'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/smtpserver.rb:539:in `process_data_line'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/smtpserver.rb:196:in `receive_line'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:64:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/em/protocols/linetext2.rb:65:in `receive_data'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run_machine'
       /usr/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.5/lib/eventmachine.rb:187:in `run'
       /usr/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/lib/mail_catcher.rb:155:in `run!'
       /usr/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/mailcatcher:5:in `<top (required)>'
       /usr/bin/mailcatcher:23:in `load'
       /usr/bin/mailcatcher:23:in `<main>'

**Comment by sj26** [comment]
Odd! Sounds like a threading issue. Please try updating mailcatcher and see if it fixes your issues. If not, please comment again.
