### ISSUE TITLE
Links are not opened in another tab/window

### ISSUE THREAD

**Issue by gpirujo-olx** [sj26/mailcatcher#240]
Hi. I upgraded from 0.5.12 to 0.6.1 and links in html bodies are no longer opening in new windows. I noticed that, in moving `/messages/:id.html` code from `web.rb` to `web/application.rb`, the following two lines are gone.

      # Rewrite body to open links in a new window
      body.gsub! /<a\s+/, '<a target="_blank" '

Are they really missing? Or is this being done somewhere else now?

Thanks!

**Comment by sj26** [comment]
They are being done in decoration and this should be fixed.
