### ISSUE TITLE
How can I delete selected emails?

### ISSUE THREAD

**Issue by salmanasiddiqui** [sj26/mailcatcher#241]
Too many emails makes the browser hang while retrieving all emails. infinite scroll + pagination might solve this as then only recent mails will be fetched and rest will be fetched once the user scrolls down.

As Web UI is not usable, I tried to delete the mails from storage, though i wasnt able to find where the mails are actually stored. Would be helpful if this is documented.

**Comment by sj26** [comment]
https://github.com/sj26/mailcatcher#api

```
# delete all messages
curl -X DELETE http://localhost:1080/messages

# delete message 123
curl -X DELETE http://localhost:1080/messages/123
```

If you have that many emails you may want to consider restarting mailcatcher, or clearing the emails occasionally. I'd prefer to keep it simple.

**Comment by salmanasiddiqui** [comment]
@sj26 Thanks.
