### ISSUE TITLE
Catchmail only working via cli

### ISSUE THREAD

**Issue by soniCaH** [sj26/mailcatcher#243]
When I send mails via command line (via "php -a" or "sendmail" command), mailcatcher does its job, but when I try to do the same via a php file in the browser, my mail() command is returning false.

```
┌─[kevin.vanransbeeck]
└─▪ php -a
Interactive shell

php > mail("testuser@test.com", "Subject", "Body", "From: john@doe.com");
```
-> mailcatcher OK

```
┌─[kevin.vanransbeeck]
└─▪ sendmail test@blabla.com < test.txt 
```
-> mailcatcher OK

Browsing to a file called mail.php in browser:
```php
var_dump(mail('testuser@something.com', 'Subject from mail', 'Body from mail', 'From: john@doe.com'));
```
-> returns FALSE, mailcatcher NOT OK

Mailcatcher is installed via gem (latest version).
sendmail_path is correctly set.

When I put the sendmail_path in comment and rely on postfix (I set up a relayhost), the mail is caught by mailcatcher

I'm on OS X El Capitan

**Comment by brichards** [comment]
I'm experiencing the same thing and am also on OS X 11.11. Prior to upgrading (just this last week) Mailcatcher worked perfectly well.

**Comment by brichards** [comment]
Related: #246

**Comment by sj26** [comment]
/usr/local/bin (where gems usually install their scripts) may no longer be in your PATH thanks to OS X. Try using the full patch to catchmail (you can find it using `which catchmail` on your shell) instead of `/usr/bin/env catchmail` in your php configuration. If this doesn't resolve your issue feel free to re-open the issue.

**Comment by soniCaH** [comment]
┌─[kevin.vanransbeeck]
└─▪ which catchmail
/Users/kevin.vanransbeeck/.rvm/rubies/ruby-2.2.1/bin/catchmail

Set this as my sendmail_path, no luck there. Also tried /usr/local/bin/catchmail but same result.

**Comment by sj26** [comment]
Rvm does strange things to gem scripts. Have you tried following the instructions for rvm in the readme?

**Comment by soniCaH** [comment]
I tried about every instruction there one by one :)

**Comment by chickenland** [comment]
I've just installed mailcatcher and I'm getting this issue too.  I've set the following in PHP.ini

sendmail_path = /Users/douglasradburn/.rvm/rubies/ruby-2.4.0/bin/catchmail -f some@from.address

I can send email perfectly fine at CLI (returns TRUE), but it returns FALSE when run in a browser.  Any further suggestions here?

**Comment by sanddevil** [comment]
Googling brought me here. I had the same issue but editing my /etc/php/5.6/fpm/php.ini file to this got me working: 
`sendmail_path = /usr/local/bin/catchmail -f noreply@mydomain.com`

**Comment by equinoxmatt** [comment]
I am also having this issue.  Any ideas? The above doesn't work for me, my path is: /usr/local/rvm/gems/ruby-2.3.1/bin/catchmail -f noreply@mydomain.com

**Comment by equinoxmatt** [comment]
I am also having this issue.  Any ideas? The above doesn't work for me, my path is: /usr/local/rvm/gems/ruby-2.3.1/bin/catchmail -f noreply@mydomain.com

**Comment by equinoxmatt** [comment]
Fixed this by using the wrapper, found via SO:

https://stackoverflow.com/questions/24741681/mailcatcher-php-mail-function-returns-false

sendmail_path = /usr/local/rvm/wrappers/default/catchmail

**Comment by sharfaz** [comment]
@equinoxmatt 

Thanks for the answer. After googling and fixing so many hours this works for me.

**Comment by matthewhaworth** [comment]
I had an issue on Mac OS Sierra, but changing

`sendmail_path = /usr/bin/env catchmail -f catcher@mailcatcher.me`
to 
`sendmail_path = /usr/bin/env /usr/local/bin/catchmail -f catcher@mailcatcher.me`

fixed it..
