### ISSUE TITLE
Clean install El Capitan + MAMP 3.4 + MailCatcher 0.6.1

### ISSUE THREAD

**Issue by rvola** [sj26/mailcatcher#246]
Hi !
After a clean install of **El Capitan**, I noticed that the **mailcatcher** no longer worked.
The problem is probably **SIP** introduced with **El Capitan**

Result in the php.ini Mamp the line, is not catchmail Mailcatcher
`sendmail_path = /usr/bin/env catchmail -f some@from.address`

replace with this and go again;)
`sendmail_path = /usr/local/bin/catchmail -f some@from.address`

**Comment by dmaciejewski** [comment]
:+1:

**Comment by klein0r** [comment]
This saved my life! Thank you so much :+1:

**Comment by JessHyde** [comment]
Thanks a lot, this was driving me crazy!

**Comment by abashirnz** [comment]
Thanks for this man 👍 👍

**Comment by fr-olivier** [comment]
Thank you so much, just spent an hour wondering wtf it doesn't work...

**Comment by robertkent** [comment]
this is the answer - perfect thanks!
