### ISSUE TITLE
MailCatcher not capturing in Rails 4.2.4

### ISSUE THREAD

**Issue by tsherlock86** [sj26/mailcatcher#249]
Using Ruby 2.2.2 

New rails app with postgres db. Scaffolded `UsersController` while calling         `Testsend.test_email(@user).deliver_now` in `users#create` doesn't get captured in MailCatcher.

**Comment by afomi** [comment]
I'm seeing this very recently as well. 

Using `ruby 2.2.3p173`.

**Comment by sj26** [comment]
Thanks, this sounds like a configuration issue. Closing.
