### ISSUE TITLE
Errno::ECONNREFUSED - Connection refused - connect(2) "::" port 1025

### ISSUE THREAD

**Issue by nvreynolds** [sj26/mailcatcher#251]
less of an issue more of an FYI

if you have:

`require "resolv-replace"`

set in your rails app you will not be able to connect to mailcatcher stmp port

```
unless Rails.env.development?
  require "resolv-replace"
end
```

**Comment by sj26** [comment]
Thanks. This sounds like an ipv6 configuration issue.
