### ISSUE TITLE
`eventmachine` v1.0.8 won't compile on OS X

### ISSUE THREAD

**Issue by connorshea** [sj26/mailcatcher#254]
```
Installing eventmachine 1.0.8 (was 1.0.5) with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/connor/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151216-76862-19mx6v6.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... no
checking for accept4() in sys/socket.h... no
checking for SOCK_CLOEXEC in sys/socket.h... no
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
CFLAGS=-O3 -I/Users/haven/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe  -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
CPPFLAGS=-D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT $(DEFS) $(cppflags) -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/connor/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8 for inspection.
Results logged to /Users/connor/.rvm/gems/ruby-2.2.3/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.8/gem_make.out
An error occurred while installing eventmachine (1.0.8), and Bundler cannot continue.
Make sure that `gem install eventmachine -v '1.0.8'` succeeds before bundling.
```

Running `gem install eventmachine -v '1.0.8'` doesn't work either.

Anyone else on OS X experiencing this issue? The previous version of mailcatcher required eventmachine 1.0.5, and I never had problems with that.

I have OpenSSL installed via Homebrew. I'm on `OpenSSL 0.9.8zg 14 July 2015` when I run `openssl` and then `version`.

**Comment by sj26** [comment]
This is because OS X El Capitan doesn't include the OpenSSL headers any more (thanks apple).

If you've got OpenSSL in homebrew, please try:

```
PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" gem install eventmachine -v "1.0.8"
```

**Comment by connorshea** [comment]
Running `brew link openssl --force` fixed the problem for me, not sure if it has any unintended consequences for others though.

**Comment by sj26** [comment]
Linking openssl into a standard library lookup location means the binary libraries could be loaded by another application which hasn't been built with homebrew. This could have unintended consequences.

I'd recommend instead compiling and linking things which need homebrew's ssl explicitly, like with the pkg config incantation.

**Comment by sj26** [comment]
Closing, please comment again if the command I posted above doesn't work for you.

**Comment by obromios** [comment]
When trying `gem install mail catcher` on OSX `13.3.1` M1 MacBook Pro I get similar error, except it failed on `event machine v 1.0.9`
I have tried 
`PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" gem install eventmachine -v "1.0.9"` and
`PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig" gem install eventmachine -v "1.0.8"` but both commands failed. The attached file has the error message:

[temp_mailcatcher.txt](https://github.com/sj26/mailcatcher/files/11360725/temp_mailcatcher.txt)

**Comment by cesc1989** [comment]
As mentioned by @obromios 

eventmachine is failing to install even with previous suggestion. In my case, the error I get is:

```
1 warning generated.
compiling ssl.cpp
linking shared-object rubyeventmachine.bundle
Undefined symbols for architecture arm64:
  "_SSL_get1_peer_certificate", referenced from:
      SslBox_t::GetPeerCert() in ssl.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rubyeventmachine.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/francisco/.gem/ruby/3.0.4/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /Users/francisco/.gem/ruby/3.0.4/extensions/arm64-darwin-22/3.0.0/eventmachine-1.0.9.1/gem_make.out
```

Setup:

- Macos M1 with Ventura 13.2.1
- Ruby 3.0.4 (installed via ruby-install

**Comment by nicholasshirley** [comment]
I was getting the same error as @cesc1989 on an M2 mac. This was what worked for me:
1. make sure openssl is installed
`brew list openssl`
 (then when/if it isn't there)
`brew install openssl`
2. install mailcatcher specifying directory
`gem install mailcatcher -- --with-openssl-dir=$(brew --prefix openssl)`

Not directly related, but this was the SO post and comment that unlocked it for me: https://stackoverflow.com/questions/74196882/cannot-install-jekyll-eventmachine-on-m1-mac#comment131357396_74283428

**Comment by jerimiahmilton** [comment]
I was getting the same error as @cesc1989 as well but was able to resolve it by reinstalling openssl3 and ruby with openssl-dir specified as mentioned here https://github.com/puma/puma/issues/2790#issuecomment-1046264194.

`brew reinstall openssl@3`
`rvm reinstall 3.1.4 --with-openssl-dir=`(brew --prefix openssl)`
`gem install mailcatcher`
