### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by connorshea** [sj26/mailcatcher#261]
Currently the [`mailcatcher.gemspec`](https://github.com/sj26/mailcatcher/blob/master/mailcatcher.gemspec) requires an activesupport version `< 5`. For testing with 5.0.0.beta1, and the eventual release of Rails 5.0.0, changing that to `< 5.1` would be preferable.

Thanks, Connor

**Comment by sj26** [comment]
Mailcatcher does not support rails. We can't guarantee that MailCatcher will simultaneously retain compatibility with all versions of activesupport so it will track dependencies independently.

Please see https://github.com/sj26/mailcatcher#bundler

**Comment by ACPK** [comment]
@sj26 - If it doesn't support rails, why are there instructions on using it with Rails?

**Comment by sj26** [comment]
@ACPK sorry, my wording was a bit confusing!

MailCatcher supports receiving email from rails. But it is an independent gem and should not be included in your Gemfile. Your rails application's dependencies may be entirely different to MailCatcher's, potentially conflicting.

I hope that's clearer. :smile:

**Comment by wadestuart** [comment]
Hi sj26,  wanted to say thank you for all the work you have put into mailcatcher it is a lifesaver.  Sorry to reopen this up but I am in a situation where I am starting to migrate an app to rails 5 in prep for the release and to enable some actioncable functionality.   I understand your point for not supporting rails dependencies directly but I have to point out that the mailcatcher dependencies have either master or releases that have been updated to deconflict with rails 5 versions and mailcatcher's dependencies are locked t versions that enforce conflicts. 

Long story short,  when working on migrating to rails 5 (which happens in development and where mailcatcher is useful) mailcatcher has locked dependency versions that conflict with the versions of gems that are required for rails 5.   For instance there is a newer version of sinatra that resolves rack version dependency issues but mailcatcher still is forcing an older version of sinatra.

It would be nice if the many people working to migrate to rails 5 along with the release could continue to rely on mailcatcher during the rework of their codebase.  Without updating the hard locks on gems the only solutions are really to either personal fork and force versioning or remove the gem and find a different solution for catching mail in dev.

Just looking for a way to allow this gem to continue working for me while on this migration. Let me know if this makes sense.

**Comment by sj26** [comment]
The solution is: don't put MailCatcher in your Gemfile. It is an independent tool. Install MailCatcher with `gem install mailcatcher`

**Comment by aymericbouzy** [comment]
Does anyone have a suggestion on where to put it instead ? When someone new joins the team, I would like to be able to simply tell them "git clone, bundle install, and you're ready to go!". Having to add this step breaks this process ...

Also, it happened that I had to reinstall my ruby version, loosing all my gems in the process. Remembering all the gems that I had installed without a Gemfile was painful, and I promised myself to always include them in a Gemfile from now on.

Thanks for sharing the tips you may have on this matter!

**Comment by sj26** [comment]
For rails you could put it into your [`bin/setup` script](https://robots.thoughtbot.com/bin-setup). Think of MailCatcher like MySQL or Postgres, or your other application dependencies. :-)

**Comment by aymericbouzy** [comment]
Thanks ! I added the following lines : 
```ruby
puts "\n== Installing MailCatcher =="
system! 'gem install mailcatcher'
```

**Comment by masashiyokoi** [comment]
It was helpful. Thank you very much.
