### ISSUE TITLE
Error in response after email has already been recieved

### ISSUE THREAD

**Issue by alexanderfrankel** [sj26/mailcatcher#264]
![mailcatcher_error](https://cloud.githubusercontent.com/assets/6508902/12428177/2e36054e-beb1-11e5-993d-830da7d1f83b.png)

![terminal 2016-01-19 13-31-08](https://cloud.githubusercontent.com/assets/6508902/12428139/f2d261a0-beb0-11e5-9b05-c08cd959d5ad.png)

**Comment by sj26** [comment]
Can you provide an example email, full source, which triggers this error?

**Comment by sj26** [comment]
Please try v0.6.5 and reopen with a source message causing the error and fresh backtrace if you're still having issues.
