### ISSUE TITLE
CORS not handled

### ISSUE THREAD

**Issue by stephaneerard** [sj26/mailcatcher#265]
Hello,

Is it be possible to make the mailcatcher webserver adding CORS header and make it configurable somehow ? :)

Thank you very much

**Comment by sj26** [comment]
You could do this by wrapping mailcatcher in a reverse proxy. I'm not sure I see a use case for putting it in the gem itself. What do you have in mind?

**Comment by stephaneerard** [comment]
Hello, main goal to me is ease of use for developers.

I have published a mailcatcher gem suffixed with -CORS.
Thank you !
