### ISSUE TITLE
`method_missing': undefined method `this' for #<Gem::Specification:0x3fc56a02c2bc activesupport-4.2.5.1> (NoMethodError)

### ISSUE THREAD

**Issue by jayqui** [sj26/mailcatcher#267]
I have installed both mailcatcher versions 0.6.3 and 0.6.1.

When I run the command `mailcatcher`, I get the following error:

```
/Users/jquigl44/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc0e842c3fc activesupport-4.2.5.1> (NoMethodError)
	from /Users/jquigl44/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/jquigl44/.rvm/rubies/ruby-
. . .
	from /Users/jquigl44/.rvm/gems/ruby-2.2.2@avant_basic/bin/ruby_executable_hooks:15:in `<main>'
```

Please help.

**Comment by nvreynolds** [comment]
gotta lock down the requirements in gemspec @sj26 

installing this version of active support fixes the issue
`activesupport  4.0.13`

**Comment by HelenFanZhang** [comment]
It seems like activesupport 4.0.13 works great with mailcatcher. I've just tested it. Avant basic requires activesupport 3.2.22 at the moment.

**Comment by HelenFanZhang** [comment]
Experiencing the same issue as @jayqui. Activesupport 4.0.13 works great with mailcatcher. Just tested and it works. =)

**Comment by wassimk** [comment]
I'm having the same issue. Any tips are appreciated.

**Comment by sj26** [comment]
This looks like a rubygems bug, folks. Not what, I can't replicate it. What version of rubygems are you using? (Post the output of `gem environment`).

**Comment by sj26** [comment]
Can you also please post the full stack trace? The meaningful bit is probably in the middle somewhere.

**Comment by sj26** [comment]
Right. So I've made mailcatcher explicitly activate its gem dependencies. Please install 0.6.4 and see if it solves your issues.

**Comment by wassimk** [comment]
Hi @sj26 , thanks for working on this. I've got v0.6.4 installed and getting this still:

``` bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mailcatcher

/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xcaf724 mailcatcher-0.6.4> (NoMethodError)
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0@unique/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0@unique/bin/mailcatcher:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0@unique/bin/mailcatcher:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0@unique/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0@unique/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kendrikat** [comment]
Same Issue here after `bundle update` ... So workaround for me is using a different (i.e. the old) gemset - Create a separate directory with `.ruby-gemset` and `.ruby-version` and install/launch it there.

**Comment by wassimk** [comment]
@kendrikat can you help me understand? What is different in your old gemset allowing it work?

**Comment by bengolden** [comment]
> $ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1

---

> $ gem install mailcatcher
Successfully installed mailcatcher-0.6.4

---

> $ mailcatcher
/Users/bengolden/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fec7981888c mailcatcher-0.6.4> (NoMethodError)
	from /Users/bengolden/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/bengolden/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/bengolden/.rvm/gems/ruby-2.3.0/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
	from /Users/bengolden/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `load'
	from /Users/bengolden/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `<main>'
	from /Users/bengolden/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bengolden/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by HelenFanZhang** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin14]

**Comment by HelenFanZhang** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
 - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-darwin14]

it looks like both versions are not working for me

**Comment by HelenFanZhang** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-darwin14]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin14]

Both are not working for me =(

**Comment by jslag** [comment]
same / similar bug here:

```
$ mailcatcher
/Users/joe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fec1208eac4 mailcatcher-0.6.4> (NoMethodError)
	from /Users/joe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/joe/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/joe/.rvm/gems/ruby-2.3.0@giftticket/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
	from /Users/joe/.rvm/gems/ruby-2.3.0@giftticket/bin/mailcatcher:23:in `load'
	from /Users/joe/.rvm/gems/ruby-2.3.0@giftticket/bin/mailcatcher:23:in `<main>'
	from /Users/joe/.rvm/gems/ruby-2.3.0@giftticket/bin/ruby_executable_hooks:15:in `eval'
	from /Users/joe/.rvm/gems/ruby-2.3.0@giftticket/bin/ruby_executable_hooks:15:in `<main>'

$ gem --version
2.5.1

```

**Comment by jnamkung** [comment]
I get these same errors when I try to run mailcatcher from my Rails root. Runs ok if I call the direct path to mailcatcher AND I run it from my home directory:

```
ju@Dullhead:~$ which mailcatcher
/Users/ju/.rvm/gems/ruby-2.3.0@tasks/bin/mailcatcher
ju@Dullhead:~$ pwd
/Users/ju
ju@Dullhead:~$ /Users/ju/.rvm/gems/ruby-2.3.0@tasks/bin/mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

**Comment by cameronstanley** [comment]
I ran in to this error when trying to run use the travis gem. Running `gem pristine --all` fixed it for me.

**Comment by wassimk** [comment]
@cameronstanley , that worked for me even when rebuilding the Vagrant VM didn't work. Thanks!

**Comment by godzilla74** [comment]
@jnamkung , that worked for me.  My specs match @bengolden

**Comment by KonstantinReido** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]

:(

**Comment by Pete-Tyldesley** [comment]
I'm getting this error too, cameronstanley's fix didn't work for me.

**Comment by sj26** [comment]
I still can't reproduce this. It might be based on the combination of gems installed. Anybody affected could you please provide as much information as possible: what is your ruby version, how is it installed, the full output of `gem environment` and `gem list`.

**Comment by GuillaumeLegendre** [comment]
Let me know if anything else could help you.
✗ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

✗ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

✗ gem list

*** LOCAL GEMS ***

aasm (4.7.0)
actionmailer (4.2.5)
actionpack (4.2.5)
actionview (4.2.5)
activejob (4.2.5)
activemodel (4.2.5)
activerecord (4.2.5)
activesupport (4.2.5)
acts_as_list (0.7.2)
addressable (2.4.0)
arel (6.0.3)
autoprefixer-rails (6.3.1)
bcrypt (3.1.10)
bigdecimal (1.2.8)
binding_of_caller (0.7.2)
bootstrap-multiselect-rails (0.9.9)
bootstrap-sass (3.3.4.1)
builder (3.2.2)
bundle (0.0.1)
bundler (1.11.2)
bundler-unload (1.0.2)
byebug (8.2.1)
cancancan (1.13.1)
capistrano (2.15.7)
capybara (2.6.0)
climate_control (0.0.3)
cocaine (0.5.8)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
concurrent-ruby (1.0.0)
daemons (1.2.3)
database_cleaner (1.5.1)
debug_inspector (0.0.2)
delayed_job (4.1.1)
delayed_job_active_record (4.1.0)
devise (3.4.1)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
email_spec (2.0.0)
erubis (2.7.0)
eventmachine (1.0.9.1)
exception_notification (4.1.4)
execjs (2.6.0)
executable-hooks (1.3.2)
factory_girl (4.5.0)
factory_girl_rails (4.5.0)
gem-wrappers (1.2.7)
globalid (0.3.6)
highline (1.7.8)
htmlentities (4.3.4)
httparty (0.13.7)
i18n (0.7.0)
io-console (0.4.5)
jbuilder (2.4.0)
jquery-rails (4.1.0)
json (1.8.3)
launchy (2.4.3)
loofah (2.0.3)
mail (2.6.3)
mailcatcher (0.6.4)
mime-types (2.99)
mini_portile2 (2.0.0)
minitest (5.8.4, 5.8.3)
multi_json (1.11.2)
multi_xml (0.5.5)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (3.0.2)
net-ssh-gateway (1.2.0)
net-telnet (0.1.1)
nokogiri (1.6.7.2)
orm_adapter (0.5.0)
paperclip (4.2.4)
pg (0.18.4)
power_assert (0.2.6)
psych (2.0.17)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rails (4.2.5)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.5)
rake (10.5.0, 10.4.2)
rdoc (4.2.1)
responders (2.1.1)
roo (2.0.1)
rspec-core (3.4.1)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-rails (3.4.0)
rspec-support (3.4.1)
rubygems-bundler (1.4.4)
rubyzip (1.1.7)
rvm (1.11.3.9)
rvm-capistrano (1.5.6)
sass (3.4.21)
sass-rails (5.0.4)
sdoc (0.4.1)
sinatra (1.4.7)
skinny (0.2.4)
slim (3.0.6)
spring (1.6.2)
sprockets (3.5.2)
sprockets-rails (3.0.0)
sqlite3 (1.3.11)
temping (3.3.0)
temple (0.7.6)
test-unit (3.1.5)
thin (1.5.1)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.2)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.2)
warden (1.2.4)
web-console (2.2.1)
will_paginate (3.0.7)
will_paginate-bootstrap (1.0.1)
write_xlsx (0.83.0)
xpath (2.0.0)
zip-zip (0.3)

✗ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre
  - USER INSTALLATION DIRECTORY: /Users/guillaumelegendre/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/guillaumelegendre/.rvm/rubies/ruby-2.3.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/bin
  - SPEC CACHE DIRECTORY: /Users/guillaumelegendre/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/guillaumelegendre/.rvm/rubies/ruby-2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre
     - /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@investissement_pierre/bin
     - /Users/guillaumelegendre/.rvm/gems/ruby-2.3.0@global/bin
     - /Users/guillaumelegendre/.rvm/rubies/ruby-2.3.0/bin
     - /Users/guillaumelegendre/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin

**Comment by sj26** [comment]
I've just noticed: everybody seems to be using rvm, and gemsets. Have you tried installing without gemsets?

**Comment by GuillaumeLegendre** [comment]
No I didn't and i'm not on my personnal computer so I don't want to mess around with the config. But it works in other gemsets. I used them currently to use mailcatcher. So the version of ruby changes and the gem list change but rvm is the same.

**Comment by sj26** [comment]
@GuillaumeLegendre I've installed the same version of rvm, ruby, created a gemset, and installed all the same gems and versions, but I don't see the error:

https://gist.github.com/sj26/35dc5e343d45f0177a07

Are your gems distributed between your gemsets?

**Comment by crwhitesides** [comment]
@cameronstanley, that worked for me. Thanks!

**Comment by NielsKSchjoedt** [comment]
+1 not working for me neither

**Comment by charazn** [comment]
This worked for me.
$ gem uninstall mailcatcher (from your local gemset)

As per the instructions on mailcatcher.me, run the following two lines:
$ rvm default@mailcatcher --create do gem install mailcatcher
$ rvm wrapper default@mailcatcher --no-prefix mailcatcher catchmail 

$ mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.

**Comment by jaydorsey** [comment]
For reference, this issue appears related: https://github.com/rubygems/rubygems/issues/1420

There are a few other possible solutions noted

**Comment by sj26** [comment]
@jaydorsey thanks! That sounds exactly like the problem. It only seems to occur in rvm with gemsets. This sounds likely:

https://github.com/rubygems/rubygems/issues/1420#issuecomment-167939914

There is a patch proposed:

https://gist.github.com/mpapis/bac6163f8855e12f7833

I haven't tried reproducing using bundler but I'll give it a go.

**Comment by adambair** [comment]
@charazn - thanks, worked great for me -- most appreciated.

**Comment by pjc** [comment]
I had the same issue and fixed it by re-installing mailcatcher in the way @charazn describes above.

For reference my issue started after upgrading bundler.

**Comment by sj26** [comment]
This is unfortunately a bug in the combiantion of Rubygems/Bundler/RVM. @charazn's instructions per the README are the safest way to install MailCatcher with RVM.

**Comment by NullVoxPopuli** [comment]
why does this seem to only happen with mailcatcher, and no other gem?

**Comment by sj26** [comment]
[It doesn't](https://github.com/search?q=%22method_missing%27+undefined+method+this%22&type=Issues&ref=searchresults).

It seems to happen in a particular edge case with rubygems, rvm and bundler. MailCatcher being an independent gem often used within projects with similar dependencies using bundler seems to hit the edge case more often.

**Comment by amitdotagarwal** [comment]
It's a bug in rubygems, may be below listed help you.
1) Open file  rubygems/specification.rb
     /Users/amitagarwal/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb
2) add method 
 `` def this; self; end 
in the end of file 
3) rvm reload 
4) restart your application

**Comment by rnmccandless** [comment]
I was able to fix this error by upgrading rubygems to the latest version

    gem update --system

**Comment by bilkhan** [comment]
@rnmccandless  isn't this will effect the other apps in the system ?

**Comment by Sohair63** [comment]
@rnmccandless  isn't this will effect the other apps in the system

**Comment by sj26** [comment]
Please try upgrading rubygems and mailcatcher and open a new issue with a fresh backtrace if you're still having issues.
