### ISSUE TITLE
Question: Any interest in providing native desktop app?

### ISSUE THREAD

**Issue by andrewhavens** [sj26/mailcatcher#268]
I am currently using MailCatcher to test emails generated by my Rails app. I started using MailCatcher because the alternatives were too hard to get working. I think this is a great project!

I think that an app like this deserves a native app, for two reasons:
* Make it easier for non-ruby developers to get it installed and running.
* Make it easier to find the app (remember the port number) when you want to view the emails.

I would be willing to help contribute to this. I am familiar with building Mac apps with RubyMotion. I think the first version could simply be a "WebView Wrapper" app. But I think it would be ideal if it could bundle Ruby/MailCatcher so that non-Ruby developers could install it easier.

I don't have any experience building native apps for Windows or Linux, so I would not be able to help with that. However, there may be other cross-platform tools available that could help with this.

Would anyone have interest in a native Mac app? (I don't want to waste my time building something that no one will use)

**Comment by andrewhavens** [comment]
I guess there's also http://electron.atom.io/ for creating cross-platform apps (using Node.js). Might be a better option, even though I prefer RubyMotion.

**Comment by vreemt** [comment]
If it's a webview wrapper you want, I've heard good things about https://github.com/jiahaog/nativefier

**Comment by sj26** [comment]
Not as part of the core project, no. I'd be open to a third party packager?

I'll close this, reopen if you come up with a prototype or ideas.
