### ISSUE TITLE
[API] Message filters

### ISSUE THREAD

**Issue by amenophis** [sj26/mailcatcher#269]
Hi,
For testing purpose, i need to filter messages returned by ```GET /messages``` endpoint.
Actually it seems not possible.
Do you think you can provide a such feature asap ?
If i provide a PR, do you think it can be merged asap ?

Thanks !

**Comment by sj26** [comment]
Can you not filter in your consumer?

**Comment by sj26** [comment]
I'd consider adding this, but would prefer to do so carefully. If you'd like something which works already maybe try [MailHog](https://github.com/mailhog/MailHog) — they seem to have [a search endpoint](https://github.com/mailhog/MailHog/blob/master/docs/APIv2/swagger-2.0.json#L127).

**Comment by amenophis** [comment]
This is my use case,
I just want to know if a known mail gots new mail.

If i can filter by recipient, i can easily count the result.
For the moment, i need to iterate over each messages and put in a list for each recipient, and then count the a specific recipient. Not really friendly ...

Do you see the use case ?

**Comment by sj26** [comment]
Ah, I see the use case. Have you tried something like:

```ruby
HTTParty.get("http://localhost:1080/messages").any? { |message| message["sender"].include? "me@sj26.com" }
# => true
```

**Comment by amenophis** [comment]
So, i did like this in groovy, and the solution is OK ;)

Thanks !
