### ISSUE TITLE
MailCatcher only catching one email and then subsequent emails error 550 Message rejected

### ISSUE THREAD

**Issue by tesmond** [sj26/mailcatcher#274]
The first email sent through mailcatcher after the daemon is started works as expected and the email can be viewed in the UI without issue. All subsequent emails will trigger the following error:

/usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:956:in `check_response': 550 Message rejected (Net::SMTPFatalError)
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:910:in `data'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:662:in `block in send_message'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:857:in `rcptto_list'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:662:in `send_message'
        from /usr/local/rvm/gems/ruby-2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:113:in `block in deliver!'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
        from /usr/local/rvm/gems/ruby-2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
        from /usr/local/rvm/gems/ruby-2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
        from /usr/local/rvm/gems/ruby-2.1.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
        from /usr/local/rvm/gems/ruby-2.1.0/gems/mailcatcher-0.6.1/bin/catchmail:71:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.0/bin/catchmail:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.0/bin/catchmail:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

The only way to send another email successfully is to kill mailcatcher and restart it, the first email then processes correctly but any others trigger the same error above. Any help on resolving this issue is appreciated.

MailCatcher is running on a CentOS release 5.10 (Final) vagrant box.

**Comment by bunam** [comment]
i'm on the same trouble, CentOS 5 two

**Comment by sj26** [comment]
Please try v0.6.5 and reopen with a fresh backtrace if you're still having issues.
