### ISSUE TITLE
Ruby 1.9 no longer supported due to Mailcatcher's dependencies?

### ISSUE THREAD

**Issue by Revisor** [sj26/mailcatcher#277]
Hi, yesterday we stopped being able to install Mailcatcher. During the installation (via `gem install mailcatcher`) the following error comes up:

```
Error installing mailcatcher:
mime-types-data requires Ruby version >= 2.0.
```
We have Ruby 1.9.3p484 installed from the official Ubuntu repository (there is no newer one unfortunately).

Is this the end of the support of Ruby 1.9, or can we do something about it?

**Comment by malford** [comment]
Yes we are having the same issue here. Very unfortunate as I don't see us moving to Ruby 2.0 anytime soon.

**Comment by sj26** [comment]
MailCatcher itself hasn't changed and remains compatible with Ruby 1.9. It seems upstream dependencies of the mail gem have precluded 1.9 and Rubygems isn't smart enough to limit its dependency resolution to the ruby version. :-(

If you manually install a mime-types-data gem version for 1.9 before installing mailcatcher it might work.

**Comment by sj26** [comment]
Try this, which worked for me on ruby 1.9.3-p551 with an empty gemset:

```sh
$ gem install mime-types --version "< 3"
Fetching: mime-types-2.99.1.gem (100%)
Successfully installed mime-types-2.99.1
1 gem installed
$ gem install mailcatcher --conservative
Fetching: i18n-0.7.0.gem (100%)
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
Fetching: thread_safe-0.3.5.gem (100%)
Fetching: tzinfo-1.2.2.gem (100%)
Fetching: minitest-5.8.4.gem (100%)
Fetching: activesupport-4.2.6.gem (100%)
Fetching: eventmachine-1.0.9.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: mail-2.6.4.gem (100%)
Fetching: rack-1.6.4.gem (100%)
Fetching: tilt-2.0.2.gem (100%)
Fetching: rack-protection-1.5.3.gem (100%)
Fetching: sinatra-1.4.7.gem (100%)
Fetching: sqlite3-1.3.11.gem (100%)
Building native extensions.  This could take a while...
Fetching: daemons-1.2.3.gem (100%)
Fetching: thin-1.5.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: skinny-0.2.4.gem (100%)
Fetching: mailcatcher-0.6.4.gem (100%)
Fetching: mime-types-data-3.2016.0221.gem (100%)
ERROR:  Error installing mailcatcher:
	mime-types-data requires Ruby version >= 2.0.
```

Despite this error:

```
$ mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

**Comment by sj26** [comment]
There is already an issue in rubygems: rubygems/rubygems#968

**Comment by matejvelikonja** [comment]
I'm also experiencing the same issue. Hope it's fixed soon.

**Comment by wujku** [comment]
+1

**Comment by tersmitten** [comment]
+1

**Comment by jeeftor** [comment]
+1

**Comment by voku** [comment]
+1

**Comment by sj26** [comment]
MailCatcher still works on Ruby 1.9, see my instructions above. A better solution requires changes within ruby gems, over which I have no control.

Closing because more +1s aren't useful and its outside mailcather's control.

**Comment by sj26** [comment]
To install on Ruby 1.9:

```
gem install mime-types --version "< 3"
gem install MailCatcher
```

You will get an error but it worked; try running `mailcatcher`.

**Comment by rogamoore** [comment]
There should be a link in the docs to this issue or a quick summary of the workaround. :)

**Comment by mhagenbruch** [comment]
Hey there... its a little bit ot but...
I followed sj26's instruction and mailcatcher works. But the 127.0.0.1:1080 is not reachable.
I have all this in Vagrant and in my vagrantfile i have the port_forwarding. But ERR_EMPTY_RESPONSE appears in browser.

**Comment by bascht** [comment]
@mhagenbruch So – it does work from inside the VM but not via the Vagrant Port Forwarding?

**Comment by mhagenbruch** [comment]
Hey, if fixed it. it was the startgin from mailcatcher hat to start it with the ip 0.0.0.0

**Comment by loren-osborn** [comment]
@bryantebeek, is there a way to do this within [your chef recipe](https://github.com/bryantebeek/chef-mailcatcher)? What would this look like? (Sorry, I'm new to chef.)

**Comment by whitehat101** [comment]
I ran into this, and fixed it. https://github.com/whitehat101/mailcatcher-ruby19

Instead of `gem install mailcatcher` try `gem install mailcatcher-ruby19`.

It literally is a no code gem, that simply depends on `mailcatcher` and a version of mime-types that will install on 1.9.

```ruby
  spec.add_dependency "mime-types", "<3"
  spec.add_dependency "mailcatcher", "~>0"
```

This gem, `mailcatcher-ruby19`, also installs without issue on Ruby 2.3.

**Comment by sj26** [comment]
If you have trouble installing mailcatcher on ruby 1.9, please try:

```
gem install mime-types --version "< 3"
gem install --conservative mailcatcher
```

If this doesnt' work, please file a new issue.
