### ISSUE TITLE
Goodie

### ISSUE THREAD

**Issue by kvokka** [sj26/mailcatcher#279]
Actually it is not a bug
But this article may be useful in wiki, or in readme if you like it

https://github.com/kvokka/onotole/blob/master/goodies/mailcatcher_loading_patch.md

**Comment by sj26** [comment]
Default behavior for action mailer in development is not to raise delivery errors. This is included in the default `config/environments/development.rb`:

```
  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false
```

Have you changed this setting?

**Comment by sj26** [comment]
Oh, you mean oh would like a fallback method?

**Comment by kvokka** [comment]
Yes :)
You'll get mail anyway and get error anyway.

Because if you switch off   `raise_delivery_errors` in future you can forget about it and spend a lot of time, thinking that mail delivers.
I just try to prevent my previous fault

**Comment by sj26** [comment]
I've added this to the README under the Rails recommendation.
