### ISSUE TITLE
Multiple instance on different machine not working

### ISSUE THREAD

**Issue by LionbridgeLifeSciences** [sj26/mailcatcher#282]
Hi!

Last time I used MailCatcher (about 8 month ago) I was able to run MailCatcher from my linux machine with the IP assigned and, from my windows machine, open the MailCatccher with this IP and receive the Emails there also.

I am not able to receive email on the MailCatcher instance on the windows machine, But I this receive email on the linux one.

Can you help?

Thank you!

**Comment by sj26** [comment]
Oh no! 😵

What version of linux, which browser are you using, and what is its version?

**Comment by LionbridgeLifeSciences** [comment]
CentOs 6.7 with Firefox 38.6.1 (Running mailCatcher and my Ruby app)
Windows Server 2208 R2 Standart with Explorer 9

and this morning, when I logged in the windows machine, I notice that I did receive the email from yesterday. please help :) 

Thank you!

**Comment by sj26** [comment]
Internet Explorer 9 does not support websockets, but it should still be polling. Have you tried refreshing the page? Are there any javascript errors?

**Comment by LionbridgeLifeSciences** [comment]
I did many refresh and I don't get any JS errors. Still now email. Anything else that could cause a delay of several hours?

**Comment by sj26** [comment]
Can you run `mailcatcher -f` and confirm that the output shows mailcatcher is receiving the message?

**Comment by LionbridgeLifeSciences** [comment]
Meilcatcher is receiving the message, and I do receive the email on the linux machine, but not on the windows machine

**Comment by LionbridgeLifeSciences** [comment]
*UPDATE*

I do receive the emails, but on my windows machine, it take about 30 minutes ... Any Idea why?

**Comment by sj26** [comment]
Just to clarify:

You're running MailCatcher on Linux, sending it email over smtp, viewing the web interface on your Linux computer in Firefox and the messages appear, and viewing the web interface on your Windows machine in Internet explorer but the messages do not appear, even if you refresh the page, except sometimes they appear after some time?

I really am not sure what's going on here, sorry. :-(

Weird browser caching by internet explorer? Have you tried a hard refresh, with Shift+F5?

**Comment by LionbridgeLifeSciences** [comment]
Yes I did the hard refresh. and yes, it's pretty much this situation

Thank you for your time! :+1:

**Comment by sj26** [comment]
Yeah, sorry I'm not sure I can fix this one. If you're able to provide some screenshots/logs from IE showing the failure maybe I can fix it, and reopen this if you do, but otherwise I'm unable to reproduce.
