### ISSUE TITLE
Missing dependency on json gem?

### ISSUE THREAD

**Issue by bradjones1** [sj26/mailcatcher#283]
After installing with `gem install mailcatcher`, I received

```
/usr/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'json' (>= 1.7.7, ~> 1.7) among 22 total gem(s) (Gem::LoadError)
```

Installing with `gem install mailcatcher json`, mailcatcher starts successfully.

**Comment by sj26** [comment]
JSON is included in the ruby standard library, but is 1.8.something now I think. I wonder what is depending on "~> 1.7".

The docker build is actually broken for me because the ruby version is too old and mime-types-data won't install. I'll update the Dockerfile generally.

**Comment by bradjones1** [comment]
Thanks for the prompt reply! It is weird, huh? If you're updating the Dockerfile it might be worth checking out what I ended up with on the above-referenced project... I copied an alpine-based build from a pull request on another image and it's pretty small.

**Comment by sj26** [comment]
I've just used the ruby:2.3 base image and installed the gem. Works a treat!

Thanks for alerting to the issue.

**Comment by sj26** [comment]
(Note we can't use ruby:slim because it doesn't include enough headers for gem compilation, or things like sqlite3. We could probably slim down the image by uninstalling ruby development dependencies once the gems are installed then collapsing FS layers, but it works as-is.)
