### ISSUE TITLE
Pdf attachments are corrupted 

### ISSUE THREAD

**Issue by enpfeff** [sj26/mailcatcher#289]
When sending an email with a pdf attachment the pdf is only 65Kb and is a corrupted file.

**Comment by enpfeff** [comment]
![image](https://cloud.githubusercontent.com/assets/7192978/15545127/6ea2119e-2258-11e6-9b93-59d9ea2b8522.png)

Email has file attached

![image](https://cloud.githubusercontent.com/assets/7192978/15545146/82abd206-2258-11e6-8912-5188f3fcc46e.png)
Downloads successfully

![image](https://cloud.githubusercontent.com/assets/7192978/15545153/8d8acc90-2258-11e6-9b30-957921ee4afa.png)
Corrupted

The actual file is 300+ KB

**Comment by sj26** [comment]
Oh no!

Can you please provide a full example email which triggers this problem? You can just click Download in MailCatcher.

**Comment by sj26** [comment]
Please try v0.6.5 and see if it solves your problem. Otherwise please reopen with a full message source which triggers the error in MailCatcher. Thanks!
