### ISSUE TITLE
Mail text left unescaped in plain text view

### ISSUE THREAD

**Issue by maisumakun** [sj26/mailcatcher#291]
I'm using MailCatcher for testing Rails app. And recently I accidentally received an error mail.

```
An ActionController::InvalidCrossOriginRequest occurred in application#routing_undefined:

  Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
  app/middleware/bad_request_catcher.rb:9:in `call'

(omit the rest)
```

Showing this mail in 'Plain text' view, text is only shown before `<script>`, and JavaScript errors are produced.

Even if this is an application intended mainly for testing, escaping HTML tags should be necessary.

## environment
* MailCatcher 0.6.4
* Firefox 47.0 on Windows 7 x64
* Google Chrome 51.0.2704.103 on Windows 7 x64
* IE 11 on Windows 7 x64

**Comment by sj26** [comment]
Nope, sorry, I consider this out of scope. This tool isn't mean to be Gmail, and doesn't purport to sandbox email because there's no hope we could ever get it right.

**Comment by jonespm** [comment]
I know this is an old issue, but the body of the text can be protected by adding sandbox to the iframe. I've locally modified my index.erb locally to change this. 

```
    <iframe class="body"></iframe>
    <iframe class="body" sandbox></iframe>
```
