### ISSUE TITLE
Current version incompatible with Rails 5

### ISSUE THREAD

**Issue by gregoirenovel** [sj26/mailcatcher#292]
The current dependencies of Mailcatcher make it incompatible with Rails 5: if I force the Rails version to 5, use the Github master version from mailcatcher and run bundler, I get the following error:

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5) was resolved to 5.0.0, which depends on
      actioncable (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
          rack (~> 2.0)

    mailcatcher was resolved to 0.6.4, which depends on
      rack (~> 1.5)

    rails (~> 5) was resolved to 5.0.0, which depends on
      actioncable (= 5.0.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) was resolved to 5.0.0, which depends on
          rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
            rack (>= 1.0)

    mailcatcher was resolved to 0.6.4, which depends on
      thin (~> 1.5.0) was resolved to 1.5.1, which depends on
        rack (>= 1.0.0)
```

So the current restruction on `rack` seems to make the upgrade to Rails 5 impossible.

If I instead do not force the Github master version for mailcatcher but only specify `mailcatcher` in the Gemfile, then Rails 5 will be used, but the installed mailcatcher version will be `0.2.4` instead of `0.6.4` (which might explain why [someone was recently running such an outdated version](https://github.com/sj26/mailcatcher/issues/290)), so that there is no dependencies conflict.

**Comment by lesliev** [comment]
Mailcatcher is not supposed to be in your Gemfile, and you don't run it through `bundle exec`. I'm running v0.6.4 on a Rails 5 project with `gem install mailcatcher` and then `mailcatcher`. 
Have you tried that?

**Comment by gregoirenovel** [comment]
You're right, it's not supposed to be in the Gemfile (which the README states, but that I had missed for some reason). I did as you suggested and it works perfectly well.
