### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by radar** [sj26/mailcatcher#293]
Howdy,

The latest mailcatcher gem version has a dependency on `activesupport ~> 4.0`, which prevents a Rails 5 upgrade. Could you please release a new version based off master?

:heart:

**Comment by radar** [comment]
Before you do that, you might want to look at #294 first.

**Comment by gdubicki** [comment]
Yeah, please release 0.6.5 that will have the UTF-8 issue fixed.

**Comment by sj26** [comment]
Yeah, fair call. I've removed the activesupport dependency entirely which fixed encoding behaviour considerably, and also made mail and websocket handling more resilient so hopefully more of the encoding errors go away or at least give useful feedback. v0.6.5 released, get it while it's hot.
