### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by thany** [sj26/mailcatcher#295]
I've never had this gem installed, but now that I have, it should be a completely clean/virgin installation. Version 0.6.4 has been installed, I assume this is the latest stable version.

So I run it:

```
> mailcatcher
```

And immedaitely it throws an error:

```
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/lib/mail_catcher/mail.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/lib/mail_catcher.rb:29:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
        from C:/Ruby23-x64/bin/mailcatcher:22:in `load'
        from C:/Ruby23-x64/bin/mailcatcher:22:in `<main>'
```

Something missing in the gem requirements or something?

**Comment by thany** [comment]
A bit of time has passed. I found a workaround where compiling sqlite3 manually would fix the problem. Well, the error doesn't occur anymore. In fact, nothing occurs anymore. After running `mailcatcher`, it exists immediately, and sure enough 127.0.0.1:1080 is not reachable.

**Comment by abr4xas** [comment]
I have the same problem with a fresh install

```bash
$ mailcatcher --help
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- concurrent (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.rc1/lib/active_support/logger_thread_safe_level.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.rc1/lib/active_support/logger.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.rc1/lib/active_support.rb:27:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.rc1/lib/active_support/all.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/lib/mail_catcher.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
	from /usr/local/bin/mailcatcher:23:in `load'
	from /usr/local/bin/mailcatcher:23:in `<main>'
```

**Comment by wipflash** [comment]
Same here with fresh install

`C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.11-x64-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/lib/mail_catcher/mail.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/lib/mail_catcher.rb:29:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mailcatcher-0.6.4/bin/mailcatcher:3:in `<top (required)>'
        from C:/Ruby23-x64/bin/mailcatcher:22:in `load'
        from C:/Ruby23-x64/bin/mailcatcher:22:in `<main>'`

**Comment by luka-zitnik** [comment]
@thany, @wipflash, if that's an option for you, start from a Ruby 2.2.X installer, still recommended by rubyinstaller.org, and it should work.

**Comment by sj26** [comment]
Sorry you folks are having trouble. Windows and ruby is always a pain. Please try the latest rubyinstaller. Otherwise make sure you can `ruby -r sqlite3` from a console. You can also run mailcatcher in the foreground to see what it's doing if it seems to die silently with `mailcatcher --foreground`. Reopen this issue with more details from those commands if it's still affecting you.
