### ISSUE TITLE
Test email has been sent (in another project)

### ISSUE THREAD

**Issue by jehon** [sj26/mailcatcher#297]
In the developpement of my projet, I test if an email has been sent.

It would be great if we could have a command line interface to read back emails to test that theses emails has been sent correctly.

**Comment by schmkr** [comment]
You could query the mailcatcher "api" (`http://localhost:1080/messages`) and see if the mail is in the list?
Even clear out the whole list of messages with a `DELETE` request on that same messages url after each test case that triggered sending emails should make sure you always have a clean state to start from.

**Comment by sj26** [comment]
Yeah the API is definitely the best bet. You could write a little mailcatcher cli gem if you like. But I probably won't roll it into mailcatcher core. Thanks!
