### ISSUE TITLE
Won't install with Ruby < 2 because of mime-types-data

### ISSUE THREAD

**Issue by xi-ao** [sj26/mailcatcher#300]
I cannot install this gem anymore with Ruby 1.9.3 (on Ubuntu 14.04), it says that `mime-types-data` requires Ruby >= 2.0.

```
/usr/bin/gem install mailcatcher -q --no-rdoc --no-ri -v "0.6.4"
ERROR:  Error installing mailcatcher:
        mime-types-data requires Ruby version >= 2.0.
```

**Comment by sj26** [comment]
See https://github.com/sj26/mailcatcher/issues/277#issuecomment-209154903. Try:

```
gem install mime-types --version "< 3"
gem install --conservative mailcatcher
```

**Comment by xi-ao** [comment]
It works, thanks. Sorry I did not find the thread you mention when looking for a solution.

**Comment by sj26** [comment]
No worries, it should probably go in the README or something, although I have a longer term fix in the works. ^_^

**Comment by Aasaimani-Arumugam** [comment]
How to update the ruby >2.0
