### ISSUE TITLE
fails to start

### ISSUE THREAD

**Issue by Rubytastic2** [sj26/mailcatcher#303]
Mailcatcher fails to start.
Im running rails 5 it is compatible?
Anyone knows a fix for this really need the mailcatcher functionality 

/Users/jordan/.rvm/gems/ruby-2.3.1@myapp/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require': cannot load such file -- rack/showexceptions (LoadError)
       	from /Users/jordan/.rvm/gems/ruby-2.3.1@myapp/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'

**Comment by Rubytastic2** [comment]
I managed to get this to work using a global gems with older rails version.
But its unconvient , is there any plans to make this compatible with rails5? I think the problem lays there

**Comment by sj26** [comment]
Please don't put MailCatcher in your Gemfile. It is an application in its own right that can't possibly interoperates with every version of rails.

Simply:

```
gem install mailcatcher
mailcatcher
```

You can put the gem install in your `bin/setup` if you like.

Alternately, I just removed activesupport as a dependency in the latest MailCatcher release. You could try upgrading.
