### ISSUE TITLE
Error on startup (OSX Sierra)

### ISSUE THREAD

**Issue by sysadm-prs-de** [sj26/mailcatcher#312]
531$ gem install mailcatcher
Fetching: mailcatcher-0.6.5.gem (100%)
Successfully installed mailcatcher-0.6.5
Parsing documentation for mailcatcher-0.6.5
Installing ri documentation for mailcatcher-0.6.5
Done installing documentation for mailcatcher after 0 seconds
1 gem installed
532$ mailcatcher --help
/Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method`this' for #<Gem::Specification:0x3ffc01447f68 mailcatcher-0.6.5> (NoMethodError)
    from /Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in`require'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/gems/mailcatcher-0.6.5/bin/mailcatcher:3:in `<top (required)>'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in`load'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `<main>'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
533$ mailcatcher
/Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in`method_missing': undefined method `this' for #<Gem::Specification:0x3fc387862c90 mailcatcher-0.6.5> (NoMethodError)
    from /Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in`find_active_stub_by_path'
    from /Users/wolfgang/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/gems/mailcatcher-0.6.5/bin/mailcatcher:3:in`<top (required)>'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `load'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in`<main>'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/wolfgang/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`<main>'

**Comment by rbliss** [comment]
@sysadm-prs-de was running into this same issue. Appears to be a bug in older versions of rubygems: https://github.com/rubygems/rubygems/issues/1420

**Comment by M1chael** [comment]
Confirm. Is there any fix for that?

**Comment by sj26** [comment]
Please upgrade rubygems:

```
gem update --system
```
