### ISSUE TITLE
Some minor usability issues

### ISSUE THREAD

**Issue by hugobyrne** [sj26/mailcatcher#313]
This is a really handy little app. I have a couple of suggestions for minor usability improvements for any future versions.

Could we make the confirmation popup on Clear configurable? 
Its really not needed 99% of the time and just a minor irritation to have to click twice to clear each time.
Ive manually updated the mailcatcher.js file to remove this but others may prefer it too.

Also could we make it a configurable option that when a new mail comes in the focus automatically jumps to that new row with the mail body automatically displayed.
I have manually click on the row each time.

These  are small details but when you are sending through 50 emails in succession for testing all these unnecessary clicks quickly add up.

Thanks!

**Comment by sj26** [comment]
What about if the "Clear" button confirms the first time after page load, then just works silently from that point on?

Your second suggestion I think would be covered by #266

**Comment by sj26** [comment]
The clear suggestion is nice, but I think unneccessary complication for the moment. We could add a "Don't ask me this again" and persist in local storage if we had a custom confirm dialog, but that's unlikely for now.

Following the latest message is tracked in #266, please subscribe there if you wish.
