### ISSUE TITLE
Conflito com o Sinatra 1.0

### ISSUE THREAD

**Issue by PedroPauloML** [sj26/mailcatcher#316]
Olá, pessoa! Estou tentando utilizar o Mailcatcher no meu projeto, mas estou enfrentando um conflito/erro:

`/home/vagrant/.rvm/gems/ruby-2.3.1/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in 'require': cannot load such file -- rack/showexceptions (LoadError)`

Esse erro ocorre quando tento iniciar o Mailcatcher juntamente com a aplicação, com auxílio do Foreman.
Se tento iniciá-lo sozinho, ele fica iniciando o serviço, mas não passa daí.

Alguma dica ou solução para esse problema?

**Comment by chalmagean** [comment]
same thing here

**Comment by sj26** [comment]
Yes, please remove the gem from your gemfile and install with rubygems and run directly instead.
