### ISSUE TITLE
Why is eventmachine locked to 1.0.9.1?

### ISSUE THREAD

**Issue by njt1982** [sj26/mailcatcher#318]
Why is eventmachine locked to 1.0.9.1 (https://github.com/sj26/mailcatcher/commit/79e023ef58532d05c7557dc7af7e7fc163220560)? Is it compatible with the 1.2.x branch?
https://github.com/eventmachine/eventmachine/releases

**Comment by sj26** [comment]
Because bumping minor versions of eventmachine breaks a lot of stuff, historically.

I'll try out 1.2.1 some time and bump it if nothing breaks.

**Comment by njt1982** [comment]
Ahh :) Makes sense. Thanks!
