### ISSUE TITLE
possible to save received mail on restart ?

### ISSUE THREAD

**Issue by saveyour** [sj26/mailcatcher#321]
is there a way to save or export the received mail when mailcatcher restarts? anyone know where the sqlite database is located or anything to that affect? thank you

**Comment by scara** [comment]
Hi @saveyour,
it's actually based on sqlite3 but it is set as _in-memory_: https://github.com/sj26/mailcatcher/blob/2e27c830b1f9c43534dc7dd5bc0ab090404d8226/lib/mail_catcher/mail.rb#L9.

More details in https://www.sqlite.org/inmemorydb.html.

HTH,
Matteo

**Comment by saveyour** [comment]
thanks, this is exactly what i was looking for!

**Comment by scara** [comment]
You're welcome!
Let's make a reference to that pull too: #61.
