### ISSUE TITLE
ruby 1.9.3 support broke

### ISSUE THREAD

**Issue by anothersmith** [sj26/mailcatcher#325]
root@i-01c21a90fc0319045:/home/mike# gem install mailcatcher -v 0.6.4
Fetching: i18n-0.7.0.gem (100%)
Fetching: json-1.8.6.gem (100%)
Building native extensions.  This could take a while...
Fetching: thread_safe-0.3.5.gem (100%)
Fetching: tzinfo-1.2.2.gem (100%)
Fetching: minitest-5.10.1.gem (100%)
Fetching: activesupport-4.2.7.1.gem (100%)
ERROR:  Error installing mailcatcher:
	mime-types-data requires Ruby version >= 2.0.

root@i-01c21a90fc0319045:/home/mike# ruby -v
ruby 1.9.3p484

**Comment by anothersmith** [comment]
root@i-01c21a90fc0319045:/home/mike# ruby -v
ruby 1.9.3p484

**Comment by sj26** [comment]
See https://github.com/sj26/mailcatcher/issues/277#issuecomment-209154903
