### ISSUE TITLE
JavaScript (not from email) showing in "Plain Text" view

### ISSUE THREAD

**Issue by GeorgeDewar** [sj26/mailcatcher#331]
I have sent a plain text email which has been captured by MailCatcher. The Plain Text view in the MailCatcher UI shows some Javascript of unknown origin before the email text.

The "Source" view shows the correct source of the message.

![image](https://cloud.githubusercontent.com/assets/5344417/23238013/d5acaa5e-f9c4-11e6-972f-fd18706df9b9.png)
![image](https://cloud.githubusercontent.com/assets/5344417/23238016/dc1b4206-f9c4-11e6-854e-9ffccdacb3e2.png)

**Comment by sj26** [comment]
Weird! Do you have any browser extensions installed?

**Comment by sj26** [comment]
Ah, `lprequeststart`, `lprequestend` and `lpsubmit` are solid hints — it's LastPass.

**Comment by GeorgeDewar** [comment]
Yes, you're right - I just disabled LastPass and the issue is gone. I wonder why it wants to inject JavaScript in there. It seems to be directly into the body of an iframe, which makes no sense to me...

**Comment by sj26** [comment]
I'm not sure, sorry, but this seems like a LastPass bug. Maybe you can blacklist MailCatcher from within LastPass?

**Comment by GeorgeDewar** [comment]
I'll look into that. Thanks for your help. I should have thought to check
the extensions!
