### ISSUE TITLE
Plain javascript in the Plain Text tab

### ISSUE THREAD

**Issue by marcu87** [sj26/mailcatcher#332]
Hello, 

I just installed mailcatcher, and I have this issue, when I receive an email, in the tab Plain Text, there is this code that appears before the email:

> (function(){var c=0;if("undefined"!==typeof CustomEvent&&"function"===typeof window.dispatchEvent){var a=function(a){try{if("object"===typeof a&&(a=JSON.stringify(a)),"string"===typeof a)return window.dispatchEvent(new CustomEvent("lprequeststart",{detail:{data:a,requestID:++c}})),c}catch(f){}},b=function(a){try{window.dispatchEvent(new CustomEvent("lprequestend",{detail:a}))}catch(f){}};"undefined"!==typeof XMLHttpRequest&&XMLHttpRequest.prototype&&XMLHttpRequest.prototype.send&&(XMLHttpRequest.prototype.send=
function(c){return function(f){var d=this,e=a(f);e&&d.addEventListener("loadend",function(){b({requestID:e,statusCode:d.status})});return c.apply(d,arguments)}}(XMLHttpRequest.prototype.send));"function"===typeof fetch&&(fetch=function(c){return function(f,d){var e=a(d),g=c.apply(this,arguments);if(e){var h=function(a){b({requestID:e,statusCode:a&&a.status})};g.then(h)["catch"](h)}return g}}(fetch))}})();
(function(){if("undefined"!==typeof CustomEvent){var c=function(a){if(a.lpsubmit)return a;var b=function(){try{this.dispatchEvent(new CustomEvent("lpsubmit"))}catch(k){}return a.apply(this,arguments)};b.lpsubmit=!0;return b};window.addEventListener("DOMContentLoaded",function(){if(document&&document.forms&&0arguments);b&&"FORM"===b.nodeName&&b.submit&&(b.submit=c(b.submit));return b}}(document.createElement)}})();

And then my email... At first I tought that I was generating the emails bad, but nopes, the email is generated just fine, I tested with another mailcatcher alternative. Also if I go to the Source tab, in mail catcher, all the code doesn't appear at all. 

I'm on ubuntu 15.10 with ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

Any clue?

thanks

**Comment by sj26** [comment]
This looks like a bug in LastPass (see #331).
