### ISSUE TITLE
Cannot get HTML preview to appear

### ISSUE THREAD

**Issue by jonniedarko** [sj26/mailcatcher#333]
I have tried setting headers `MIME-version` and `Content-Type`
```php
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/html\r\n";
 ```
I even tried changing the case as I read somewhere else a similar program had similar issue
```           
$headers .= "Content-type: text/html\r\n";
```

I am Just using the default mail client in PHP 5.6

**Comment by sj26** [comment]
Sorry, I don't know or use PHP. 😅 Can you _Download_ the message in mailcatcher and paste the contents of the email here?

**Comment by sj26** [comment]
Ah, so email headers finish and the body begins at the first double newline. So your headers at finishing at:

```
Reply-To: mysite 
```

So the MIME and content-type headers are being seen as part of the body, so ignored. Perhaps you need to take a look at how you're calling the PHP mail function, or how you're appending those headers?

**Comment by jonniedarko** [comment]
Oh I see, I was using a snippet that had both `\r` & `\n` . So Was not an issue with mailCatcher. 
Thank you
