### ISSUE TITLE
Warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by bytehead** [sj26/mailcatcher#334]
I get following warning when I start mailcatcher:
`/usr/local/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated`

**Comment by shakycode** [comment]
This is a change in Ruby 2.4.0.  Install mailcatcher with the latest 2.3.x Ruby version to get rid of the deprecation warnings and/or wait until mailcatcher is compatible with 2.4.0

**Comment by bytehead** [comment]
Thank you! Just noticed it - not really high prio to fix 😉

**Comment by mikelkew** [comment]
@sj26 Can you please consider releasing a small update to bump **thin** (and perhaps **eventmachine**) dependencies in both **mailcatcher** and **skinny**?

**Comment by sj26** [comment]
Both have open compatibility issues. and subtly break skinny and mailcatcher.

If somebody wants to do an upgrade and fix the compatibility in a PR that'd be great! I'm more inclined to semi-rewrite MailCatcher eschewing the C extensions for something a bit more portable with completely vendored gems, though. I had a wip a while back. I'm on a plane later today, might give it a crack.

**Comment by sj26** [comment]
(Also note that MailCatcher works fine in ruby 2.4, just issues warnings.)

**Comment by edwardmp** [comment]
@sj26 
Wouldn't it be easier to just swap Thin for Puma? I can definitely submit a PR for that.

**Comment by sj26** [comment]
Puma doesn’t use eventmachine so doesn’t fit in event loop for smtp and websockets.
