### ISSUE TITLE
From header not resolved in list view

### ISSUE THREAD

**Issue by jbouzekri** [sj26/mailcatcher#338]
I am sending an email with this `From` header : 

```
From: Name <name@domain.com>
```

However, in the list view, I am only seeing `<name@domain.com> size=33023`.

How can I verify that my `From` header is correctly interpreted ?

**Comment by sj26** [comment]
The _From_ is the supplied `FROM` address supplied when the mail is sent via SMTP, not the value from the RFC822 `From` header (but the address component is usually the same). If you want to double-check the From header take a look inside the `Source` tab. :-)

**Comment by jbouzekri** [comment]
Hi, Thanks for you feedback. Yes, I saw it in the `Source` tab but I was hoping to preview in the list as it would be displayed in a imap/pop client. But I understand that you want to stay focused on the `SMTP` part of things.
