### ISSUE TITLE
Emails sent from a long/never ending script do not show up in the web interface until the script terminates.

### ISSUE THREAD

**Issue by samdjstevens** [sj26/mailcatcher#340]
Apologies if this is not clear/related to Mailcatcher!

I'm running a RabbitMQ consumer (a long running PHP script) that receives jobs from the queue to send emails out using Swiftmailer (a PHP emailing package). I've found that the consumer will happily send the emails as the messages are fetched from RabbitMQ, but they will only appear (all at once, instantly) when the consumer/long running script is terminated. The problem is, is that this script is designed to "never" be terminated, and to run indefinitely.

Ideally, I would like to get the emails appearing in the web UI as soon as they are sent, not all together when the script terminates.

**Comment by sj26** [comment]
Hi @samdjstevens! Sadly that sounds like it might be your script or mail library might be buffering the messages somehow. MailCatcher should display messages as soon as they are received over the SMTP connection.

**Comment by samdjstevens** [comment]
That's exactly what is happening :man_facepalming: 

Symfony (the framework I'm using with this) has an option to spool all emails sent in memory until the kernel/script terminates, and this is turned on in the default configuration shipped with the standard distribution. Disabling this spooling fires the emails over straight away.

Cheers for the look in!

**Comment by sj26** [comment]
Ah, glad you got it sorted out! :-)
