### ISSUE TITLE
Misleading error message on privileged ports

### ISSUE THREAD

**Issue by dampfklon** [sj26/mailcatcher#347]
If you try to run mailcatcher on an privileged port without root you get the error message
`~~> ERROR: Something's using port 25. Are you already running MailCatcher?`
even if no other programm uses the port.

**Comment by sj26** [comment]
Sadly there is no way to know. The underlying error message is:

```
#<RuntimeError: no acceptor (port is in use or requires root privileges)>
```

If you can figure it out then patches are welcomed! :-)

**Comment by dampfklon** [comment]
you could simpy check if the given port is <=1024
