### ISSUE TITLE
Escape angle brackets in plaintext email bodies

### ISSUE THREAD

**Issue by jwadhams** [sj26/mailcatcher#356]
I'm using MailCatcher in a project where one of our major integrations sends emails with XML bodies ([Auto-Lead Data Format](http://adfxml.info/))

The "plaintext" tab in the MailCatcher GUI doesn't show any of the XML tags.
The "source" tab shows all my XML tags, but it also includes all the "quoted-printable" formatting, like [everyone's favorite =3D](https://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html) on all my XML attributes.

Is there a config setting, or would you be open to a patch, that could get me the mail body with QP decoded, but with angle brackets escaped so the browser doesn't get confused?

Thanks!

**Comment by sj26** [comment]
Oh dear, that's no good — sorry!

Do you have a full message body which when sent to MailCatcher triggers this behaviour? I need to reproduce it to fix it. :-)

**Comment by Adirelle** [comment]
Almost the same there: as mailcatcher does not escape HTML tags for plain/text, they are interpreted by the browser instead of being displayed, which prevents from catching some-HTML-sneaked-in-the-text/plain-template bugs.

**Comment by sj26** [comment]
This is tracked in a new issue #446, please follow there.
