### ISSUE TITLE
coredump accessing web interface when listening on all-ipv6-addresses

### ISSUE THREAD

**Issue by Supermathie** [sj26/mailcatcher#360]
When running mailcatcher and listening on all IPv6 addresses, I get a coredump when trying to access the web interface.

```
→ mailcatcher --ip :: -f
Starting MailCatcher
==> smtp://:::1025
==> http://:::1080
*** stack smashing detected ***: ruby /home/michael/.rvm/gems/ruby-2.3.4/bin/mailcatcher --ip :: -f terminated
```

Gem version: 0.6.5
Tried with both ruby 2.3.4 and 2.4.1, same result.

Works normally with an IPv4 IP (e.g. 127.0.0.1 or 192.168.1.100)

**Comment by sj26** [comment]
Sorry, I have no idea! Maybe it's an eventmachine bug? Patches accepted if you can figure it out. :-)

**Comment by olemd** [comment]
If it's any help, it works with ruby 2.5.1, eventmachine 1.0.9.1 and mailcatcher 0.6.5

**Comment by sj26** [comment]
Closing this in lieu of activity.
