### ISSUE TITLE
Weird Plain Text view behaviour

### ISSUE THREAD

**Issue by sd65** [sj26/mailcatcher#368]
Hi,

On a plain text mail, Plain Text tab displays HTML.
On a HTML mail, Plain Text tab displays HTML and HTML tab displays plain text.

This is just weird and should be easy to fix I guess. :smiley:

**Comment by sj26** [comment]
Hi @sd65 — thanks for your report!

I'm afraid I can't replicate this. It would be a pretty obvious problem! But if I run something like using the latest version of mailcatcher and the example emails in this repository it all behaves as expected:

```
mailcatcher
catchmail < examples/plainmail
catchmail < examples/htmlmail
catchmail < examples/multipartmail
```

![screen shot 2018-02-27 at 10 17 58 am](https://user-images.githubusercontent.com/14028/36701638-4729497a-1ba8-11e8-959d-a6447929f455.png)

![screen shot 2018-02-27 at 10 18 00 am](https://user-images.githubusercontent.com/14028/36701643-494715b6-1ba8-11e8-8a49-3565555b26ed.png)

![screen shot 2018-02-27 at 10 18 03 am](https://user-images.githubusercontent.com/14028/36701645-4b3ef032-1ba8-11e8-8a29-620113b42d0d.png)

![screen shot 2018-02-27 at 10 18 07 am](https://user-images.githubusercontent.com/14028/36701650-4df4e0de-1ba8-11e8-901e-068c1595d7d2.png)

Can you please provide complete example message bodies and show some screenshots with the issue? Also, what version of mailcatcher are you using (`mailcatcher --version`)?

**Comment by sd65** [comment]
Hi,

Thanks for the quick response. I'm using mailcatcher 0.6.5.

Since your post, I can precise my astonishment. In fact, links are concerted in hyperlinks automatically when using plain text view.
Furthermore,  HTML tags are interpreted in plain text.
Here's some screenshots:

![m1](https://user-images.githubusercontent.com/4440388/36721623-b9653b4a-1bab-11e8-917a-6fe50061aabe.png)

![m2](https://user-images.githubusercontent.com/4440388/36721631-bbc83a68-1bab-11e8-85c5-ca58160be85b.png)

Is it an expected behavior? To me, auto hyperlinks are OK and great but interpreting HTML tags is wrong and should be just ignored. What do you think?
Thanks!

**Comment by sj26** [comment]
Ah, sounds related to #356 introduced by #97. I'm tempted just to revert #97 completely.

**Comment by barrettkingram** [comment]
Any update on this issue? I've been encountering it lately.

**Comment by sj26** [comment]
This is tracked in a new issue #446, please follow there.
