### ISSUE TITLE
Mailcatcher not Working in High Sierra

### ISSUE THREAD

**Issue by leopinzon** [sj26/mailcatcher#372]
Hi guys, first of all thanks for the amazing work you've done with Mailcatcher. 

I recently upgraded to MacOS High Sierra and Mailcatcher stopped working with the following error at starting it up: 

`sh: /usr/local/bin/catchmail: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory`

After reading multiple threads about similar issues with other ruby based applications, I installed rbenv and ruby 2.5 with Homebrew in order to work with an alternative Ruby version than the 2.3 pre-installed version built in High Sierra.

Anyway, I reinstalled Mailcatcher without issues but now when I run it, it isn't receiving/catching the emails. 

If it is of any help, when running it, I get some message that wasn't appearing before: 

`$ mailcatcher 
Starting MailCatcher
==> smtp://127.0.0.1:1025
/Users/[myuser]/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
`

I'd appreciate your help, thanks a lot!

**Comment by sj26** [comment]
Try: `gem upgrade mailcatcher`

**Comment by leopinzon** [comment]
Thanks @sj26 , no luck: 
```
$ gem upgrade mailcatcher
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command upgrade
```

**Comment by sj26** [comment]
Sorry, that should be: `gem update mailcatcher`

**Comment by leopinzon** [comment]
Thanks again @sj26 , no luck either. I have "Nothing to update". My Mailcatcher version is: 
`mailcatcher (0.6.5)`

**Comment by sj26** [comment]
Sorry, I'm not sure what's going on :-(

It sounds a bit like maybe you're running old versions of ruby, shared libraries, or gems which aren't updated for High Sierra. Maybe try a `gem pristine --all`

Are you using Homebrew? Maybe try a `brew doctor`

There was also an [issue with fork](https://bugs.ruby-lang.org/issues/14009) introduced in High Sierra. Have you tried updating the version of ruby you're using?

**Comment by linusnyberg** [comment]
I had the same problem, and using `gem install mailcatcher` to reinstall it solved the problem. I also performed `gem pristine --all` first, but that didn't solve anything, so not sure it's relevant.

**Comment by sj26** [comment]
Heavens heard any more, hopefully one of the solutions above has worked for you.

**Comment by leopinzon** [comment]
It is a shame but, no guys, no luck. Tried doing pristine, uninstall, install, update, etc. Same error each time. 
`/Users/leopinzon/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated`

@sj26 I can't upgrade native MacOS Ruby since it isn't recommended and, as far as I read around, it is used for other system's process. Therefore that woudn't be a feasible option.

**Comment by sj26** [comment]
Again, that Fixnum message is a warning, not an error.

When happens when you run:

```
mailcatcher --foreground
```

**Comment by leopinzon** [comment]
It didn't work through the sendmail driver, but it did through the smtp host+port! 
Thanks a lot.

**Comment by steady-daddy** [comment]
> ```
> mailcatcher --foreground
> ```

This worked for me. Thank you so much! 🙂
