### ISSUE TITLE
Return-Path header is not added to received emails

### ISSUE THREAD

**Issue by fmeeuw** [sj26/mailcatcher#373]
I was trying to test if the return-path was added correctly with mailcatcher, but I think the smtp-server did not add the Envelope From sender as return-path header when receiving the mail. Might be a nice feature to add this header, as I think most smtp-servers are expected to do so.

**Comment by sj26** [comment]
Mailcatcher does not modify the headers or body of email messages at all by design, it just catches the literal message body received over smtp and stores it for you. The envelope details are as in the _From_ field in the interface, and are also available via the api.

**Comment by sj26** [comment]
(The received from header is added for MUAs which don’t have access to envelope details, but mailcatcher does.)
