### ISSUE TITLE
Upgrade to Sinatra 2.0

### ISSUE THREAD

**Issue by yegor256** [sj26/mailcatcher#383]
Would be great to upgrade to Sinatra 2.0. The version 1.2 you depend on right now is too old.

**Comment by swifthand** [comment]
Slight assumption of what @yegor256 meant, but for installation of `mailcatcher` alongside other gems within a project, Sinatra >= 2.0 might required by other dependencies that mount little rack servers. The dependency on Rack 1.5 has a similar effect in projects that might also require higher versions (e.g. Rack >= 2.0).

I am not as familiar with Sinatra versions, but I have a loose awareness that Rack 2.0 contains substantial changes, and thus might not be a drop-in replacement? It might not even been an intended feature to be able to run Mailcatcher alongside/within other Rack apps?

At work, one project that uses Mailcatcher that has some orchestration to isolate it in a little vendored directory, and to use a separate Gemfile from the main project (and thus separate dependency resolution). If I recall correctly it was done this was precisely for this reason, i.e. the main project is a Rails 5 application, which requires Rack 2.0, and thus Mailcatcher cannot be installed (even within a `:development` group).

**Comment by sj26** [comment]
Please don’t include mailcatcher in your Gemfile.

https://github.com/sj26/mailcatcher/blob/master/README.md#bundler
