### ISSUE TITLE
Can't exit mailcatcher on a server

### ISSUE THREAD

**Issue by M1ke** [sj26/mailcatcher#387]
How to reproduce?

1. Start mailcatcher
2. `ps aux | grep mailcatcher`
3. `sudo kill PID` (PID from above command)
4. `ps aux | grep mailcatcher` - will still be running

Without a browser (e.g. running on a CI server) mailcatcher can't be stopped. Genuinely impressive how persistent it is, and that's without the no-quit option. But does mean it's a bit annoying working out how to get rid of it. It would be good to have a command line operation to do the same as the browser quit button.

**Comment by sj26** [comment]
Hi @M1ke,

Sorry, I can't reproduce this — killing works fine for me:

```
% ps aux | grep mailcatcher
sj26             92286   0.0  0.0  4268036    796 s006  R+    3:43pm   0:00.00 grep mailcatcher
sj26             92278   0.0  0.0  4384836    496   ??  S     3:43pm   0:00.01 .../ruby .../mailcatcher
% kill 92278
% ps aux | grep mailcatcher
sj26             92292   0.0  0.0  4277252    808 s006  R+    3:43pm   0:00.00 grep mailcatcher
```

Could you provide a little more information — what version of ruby are you using (`ruby --version`)? what version of mailcatcher (`mailcatcher --version`)? what gems are on your system (`gem list`)?

Cheers,
Sam

**Comment by M1ke** [comment]
Thanks, here's the output:

```
m1ke@xxx:~$ ps aux | grep mailcatcher
root     22988  0.7  3.1 187576 32164 ?        Ssl  10:03   0:00 /usr/bin/ruby1.9.1 /usr/local/bin/mailcatcher --foreground
m1ke     23826  0.0  0.0  14136  1016 pts/0    S+   10:05   0:00 grep --color=auto mailcatcher
m1ke@xxx:~$ sudo kill 22988
m1ke@xxx:~$ ps aux | grep mailcatcher
root     23982 54.0  2.8 112512 29472 ?        Ssl  10:05   0:00 /usr/bin/ruby1.9.1 /usr/local/bin/mailcatcher --foreground
m1ke     23988  0.0  0.0  14132  1016 pts/0    S+   10:05   0:00 grep --color=auto mailcatcher
m1ke@xxx:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
m1ke@xxx:~$ mailcatcher --version
mailcatcher 0.6.5
m1ke@xxx:~$ gem list

*** LOCAL GEMS ***

activesupport (4.2.6)
daemons (1.2.3)
eventmachine (1.0.9.1)
i18n (0.7.0)
json (1.8.3)
mail (2.6.4)
mailcatcher (0.6.5, 0.6.4)
mime-types (2.99.2)
mini_mime (1.0.1)
minitest (5.9.0)
rack (1.6.4)
rack-protection (1.5.3)
sinatra (1.4.7)
skinny (0.2.4)
sqlite3 (1.3.11)
thin (1.5.1)
thread_safe (0.3.5)
tilt (2.0.4)
tzinfo (1.2.2)
```

(note the change of PID after the `kill` command)

**Comment by zarelit** [comment]
The fact that it is running as root and with a prefixed ruby interpreter leads me to think that you're launching it through the init system and that it's the supervisor/init system that is respawning it with a different pid.
How are you making it run?

**Comment by sj26** [comment]
Yes, this sounds like mailcatcher is being run by your init system and is being restarted when it exits. Please check your systemd/upstart/sysv configuration, it's in there somewhere. For example, on ubuntu use something like `systemctl status` or `sudo systemctl status` and look for `mailcatcher`.

**Comment by M1ke** [comment]
@sj26 sure, happy to accept it probably is that but it's an odd one. I completely uninstalled it and so was able to get it to stop running. I then reinstalled it and the problem is now slightly different - I can stop it with "kill" but cannot find what's starting it. Systemctl says it's no longer a service, can't see it in init.d, upstart or similar. From a fresh install would you expect it to set itself to start on boot?

**Comment by M1ke** [comment]
Found it was in `/etc/rc.local` - imagine that was a long ago attempt on the system to get it running before putting it into upstart/systemd and so it was just lingering there.

**Comment by ThomasLandauer** [comment]
Instead of fiddling around with the process id, you can just use curl to mimic what MailCatcher does itself:
```bash
curl -X DELETE http://127.0.0.1:1080/
```
I opened a PR to include this in the start message after "Go to the web interface to quit": https://github.com/sj26/mailcatcher/pull/448
