### ISSUE TITLE
Support for GPG Mails?

### ISSUE THREAD

**Issue by typoworx-de** [sj26/mailcatcher#389]
I'm currently working on a project (with local development) that requires to send mails with GPG. It would be very handy being able to make Mailcatcher use Test-Keys for GPG Decryption.

Is there something like that planned or is it possible to use any browser plugin (chrome/firefox) to make this work out of the webview used by Mailcatcher?

**Comment by sj26** [comment]
Hi @typoworx-de! :wave: GPG is pretty complicated and requires a few moving pieces so is unlikely to be built into MailCatcher itself. But if you download the message using the download button you can then open it in your mail client or verify the gpg message on the command line? You could also build a browser extension which did the same with fancy annotations or something.
