### ISSUE TITLE
Clear button doesn't work

### ISSUE THREAD

**Issue by sau226** [sj26/mailcatcher#391]
When I press the clear button in mailcatcher no request is sent to any endpoint and the messages do not clear.

This occurs on ruby 2.6.1 (rbenv install) with mailcatcher and its dependencies installed.

I can confirm that if I execute the ajax request manually in browser dev console (such as the code below) the request does send and there are no issues.

`$.ajax({ url: "/messages", type: 'DELETE' })`

I have no browser plugins that are capable of intercepting the request. This means that this must be a JS or similar error on mailcatcher's end.

**Repro:**
1. Install mailcatcher using a rbenv install of ruby 2.6.1
2. Start mailcatcher bound to all ip's (`--http-ip=0.0.0.0`)
3. On a Windows PC access your mailcatcher instance via latest, stable Google Chrome
4. Send any email to the mailcatcher instance and ensure that it appears
5. Use the clear button and press OK on the pop up

**Expected result:** Chrome sends a DELETE request to "your-mailcatcher-instance/messages" and the messages are gone

**Current result:** Nothing happens whatsoever

**Comment by RedfinDiver** [comment]
Can confirm the issue. This ist the error message in the console after hitting the "clear" button:

`Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at HTMLAnchorElement.<anonymous> (mailcatcher.js:4)
    at HTMLDocument.n (mailcatcher.js:1)
    at HTMLDocument.handle (mailcatcher.js:1)
    at HTMLDocument.u (mailcatcher.js:1)`

**Comment by sj26** [comment]
Sorry folks, this was a bug introduced in 0.7.0. I've pushed a fix and released 0.7.1.

Try an update:

```
gem update mailcatcher
```

**Comment by sau226** [comment]
**Note to self and others using mailcatcher with Chrome:**  This fix may need a empty cache and hard reload (open chrome dev tools, right click on refresh button and click empty cache and hard reload). If that doesn't work reboot the server and try the process again. The `Last-Modified` header for `mailcatcher.js` should be `Mon, 04 Mar 2019 06:53:11 GMT`
