### ISSUE TITLE
Please update rack dependency

### ISSUE THREAD

**Issue by dennisvandehoef** [sj26/mailcatcher#393]
Hi,

We are still stuck on version 0.2.4.

Today I tried to update the gem and can't update because of the rack (~> 1.5) dependency that is new (compared to v 0.2 😉 )

We use other gems that have a rack (~> 2.0) dependency.
Is there any option you can upgrade the dependency here?

Kind regards,
Dennis

**Comment by sj26** [comment]
Mailcatcher requires skinny requires thin requires rack, and it doesn’t support 2.0. Try “gem upgrade mailcatcher”

**Comment by dennisvandehoef** [comment]
I see we made a mistake in the past, it is in our gemfile :(

`Please don't put mailcatcher into your Gemfile. It will conflict with your applications gems at some point.`

Thanks for you time :)

**Comment by Gurrium** [comment]
FYI, I separated container using this [Dockerfile](https://hub.docker.com/r/schickling/mailcatcher/dockerfile).
