### ISSUE TITLE
Mailbox size

### ISSUE THREAD

**Issue by knyttl** [sj26/mailcatcher#395]
Is there a way to limit the mailbox size and drop old emails? I would like to prevent mailcatcher to consume all available disk space.

**Comment by lbenedetto** [comment]
Looks like its been sitting in a pull request for a year.
https://github.com/sj26/mailcatcher/pull/375

**Comment by sj26** [comment]
#375 was merged in a while ago. Please try the beta:

‘‘‘
gem install --pre mailcatcher
‘‘'
