### ISSUE TITLE
Names associated to sender and recipients emails are not displayed + email size is appended to sender text.

### ISSUE THREAD

**Issue by souliane** [sj26/mailcatcher#399]
Hi,
I get these display issues:

- Name of sender and recipients are not displayed, i.e. "Test Name &lt;test@test.com&gt;"  is only displayed as "&lt;test@test.com&gt;"
- The size of the message is appended to the "from" text, as you can see on the picture.

![mailcatcher_issue](https://user-images.githubusercontent.com/21343492/61625913-2b117f80-ac7c-11e9-93ce-c6a1782f4a76.png)

The emails that are sent via normal SMTP server are OK. I don't use mailcatcher directly but via https://github.com/jgiannuzzi/docker-mailcatcher, but this is just dockerizing mailcatcher and I don't see how it could be responsible for these issues.

Cheers,
Adrien

**Comment by sj26** [comment]
Correct, the From and To at the top of the screen are the SMTP sender and recipient which usually do not contain names, but do reflect how the message would be routed. The mail message body may have To and From headers which usually do have names, and usually have matching addresses, and they will be displayed in the bottom part.

**Comment by souliane** [comment]
OK, I won't discuss about that :-)

But what about the size information which is appended to the From address?

**Comment by sj26** [comment]
That I can’t account for, maybe a bug in your client? Can you provide a message which replicates the issue?

**Comment by stevecondylios** [comment]
Hi there, awesome software!

I know this is a two-part issue, but on the first part (displaying the sender name), I also think it would be very useful/sensible to display it if possible. The reason being, it wouldn't detract from current use, but it would also give the developer a better idea of how their users will experience the email in the context of using their website/software. 

To highlight why this is important, certain software (e.g. rails) doesn't use a gsuite/google workspace sender name, but instead overrides it with a title case version of the part of the email before the `@`. Which is kinda weird, but it necessitates the developer looking at [how to change that default name](https://stackoverflow.com/questions/20811353/how-can-we-set-the-name-of-the-email-sender-in-rails-mailer) and it would be great to be able to test locally using mailcatcher :)

**Comment by jeremyZX** [comment]
SIZE=XXXXX in the "from" field happens for us as well, via [MailKit](https://github.com/jstedfast/MailKit) as the client. From my incredibly limited understanding of SMTP and MailKit's codebase, I believe it's following [RFC1870's size declaration](https://datatracker.ietf.org/doc/html/rfc1870#section-8), and is detecting something on Mailcatcher's end which makes it believe that it accepts and understands the size extension.

**Comment by sj26** [comment]
Thanks @jeremyZX, I've been able to replicate 👍

**Comment by sj26** [comment]
Actually let's open a separate issue
