### ISSUE TITLE
I don't see the "source" field in the JSON API response

### ISSUE THREAD

**Issue by magickreeator** [sj26/mailcatcher#401]
I execute 
echo "body of your email" | mail -s "This is a Subject" "testemail@mailinator.com"

Actual result
![image](https://user-images.githubusercontent.com/10911885/63510203-afa72600-c4e6-11e9-9f5a-5d4b992dff3f.png)
`{
  "id": 2,
  "sender": "<vagrant@gate2025.localdomain>",
  "recipients": [
    "<testemail@mailinator.com>"
  ],
  "subject": "This is a Subject",
  "size": "479",
  "type": "text/plain",
  "created_at": "2019-08-22T10:57:52+00:00",
  "formats": [
    "source",
    "plain"
  ],
  "attachments": [
    
  ]
}`

Expected result
Something like this
`{
  "id":1,
  "sender":"",
  "recipients":[""],
  "subject":"R\u00e4ksm\u00f6rg\u00e5s!",
  "source":"From: Testing \nTo: receiver@localhost.local\nDate: Mon, 18 Aug 2014 17:51:26 +0200\nMessage-ID: <53f220fe58644dfb827100d80a00020f@localhost.local>\nSubject: =?UTF-8?B?UsOka3Ntw7ZyZ8OlcyE=?=\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nH\ufffd\ufffdll\ufffd\ufffd t\ufffd\ufffdsting r\ufffd\ufffdksm\ufffd\ufffdrg\ufffd\ufffds!\n\n\n\n",
  "size":"348",
  "type":"text/plain",
  "created_at":"2014-08-18T15:51:26+00:00",
  "formats":["source","plain"],
  "attachments":[]
}`

I don't understand why I don't get this field there. Should it be there?

**Comment by sj26** [comment]
No, the source is served as a separate content type. Try a `.eml` extension instead of `.json`, like `http://127.0.0.1:1080/messages/2.eml`.

**Comment by magickreeator** [comment]
Ok, thank you. My mistake was that I used an old version of module for codeception https://github.com/captbaritone/codeception-mailcatcher-module

**Comment by Synida** [comment]
I just googled for 2 days, just to find out that I have the same issue xD
This information saved a lot more time, thank ya'!
