### ISSUE TITLE
Support HTTP delivery methods

### ISSUE THREAD

**Issue by SokratisVidros** [sj26/mailcatcher#406]
Hi there,

Since most of mail gateway vendors currently support HTTP deliveries using JSON APIs (e.g. https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-via-api) are there any plans to support that?

Thanks in advance!

**Comment by sj26** [comment]
No plans, no. They all vary so much, and keeping up with changes would be pretty trick, so I don't think I'd want to try and take it on, sorry!
