### ISSUE TITLE
Multiple Mailcatcher Instances

### ISSUE THREAD

**Issue by YevgenyGopher** [sj26/mailcatcher#408]
i'm trying to run the mailcatcher with unicorn because I need multiple instances to handle a lot of traffic.
Is it even possible? I have added and configured the gem but can't run the project as a rails app maybe I should run it as Rack?

**Comment by sj26** [comment]
No, MailCatcher is not a rack application, it is a process which encapsulates both http and smtp. The default process should handle a fairly high degree of load with high concurrency. It uses the [thin](https://github.com/macournoyer/thin) web server and evented smtp connection handling via eventmachine.

If you need to run multiple instances then you can start them on different ports (see `mailcatcher --help`).
