### ISSUE TITLE
New Mailcatcher gem 

### ISSUE THREAD

**Issue by YevgenyGopher** [sj26/mailcatcher#409]
Hi Samuel,

when will there be a new gem with the included support for --messages-limit COUNT option?

Thanks! it came at the right time :)

**Comment by sj26** [comment]
Please try [v0.8.0.beta1](https://github.com/sj26/mailcatcher/releases/tag/v0.8.0.beta1) via `gem install --pre mailcatcher` and let me know how you go. :-)

**Comment by Manawyrm** [comment]
The new message limit seems to work, but it looks like the 0.8.0beta introduced another bug: 
When clicking on an email, you get a completely different email displayed then what you clicked on. 

![](https://screenshot.tbspace.de/zwcumdqhifo.png)
![](https://screenshot.tbspace.de/ibycewlqprf.png)

Q&D PHP Script to reproduce the issue:
```
<?php 

for ($i = 0; $i < 100; $i++)
{
$smtp = "EHLO test.example.com
MAIL FROM:test$i@test.com
RCPT TO:test@test.com
DATA
Subject: Test $i

This the body of Test $i

.
QUIT";

$fp = fsockopen("localhost", 1025, $errno, $errstr, 30);
fwrite($fp, $smtp);
fclose($fp); 

}
```

I'm running mailcatcher with `mailcatcher -f --ip 127.0.0.1 --messages-limit 1000`

Thanks for your time :)

**Comment by sj26** [comment]
Thanks for the report @Manawyrm. I'm having trouble replicating. The only way I can replicate is if I start mailcatcher, send some messages into it, load the web interface, then stop and restart the mailcatcher process, send some more messages, then click around in the already loaded web interface. This is expected — the web interface would be displaying stale results, and there's not a great way to resolve that.

**Comment by Manawyrm** [comment]
Hm, I had to play around a little bit more. 

I think I can reproduce it reliably now: 
```php
<?php 

for ($i = 0; $i < (100 + rand(0,20)); $i++)
{
$smtp = "EHLO test.example.com
MAIL FROM:test$i@test.com
RCPT TO:test@test.com
DATA
Subject: Test $i

This the body of Test $i

.
QUIT";

    $fp = fsockopen("localhost", 1025, $errno, $errstr, 30);
        fwrite($fp, $smtp);
        fclose($fp); // To close the connection

}
```

Message-limit set to 1000. 
Run this script until you have 1000 mails and some are dropped, then press "Clear" in the webinterface.
When you now run the script again twice, you get the wrong mails displayed. (I'm always pressing F5 in between, my setup doesn't allow for websockets to be used)

Thanks!

**Comment by sj26** [comment]
Sorry, I still can't replicate this — doing what you've described with your script works as expected for me.

I've just released another beta which includes some small javascript tweaks I made to fix an unrelated bug, maybe maybe it also fixes this one — give it a go?

```
gem install mailcatcher --pre
```

**Comment by afomi** [comment]
https://github.com/sj26/mailcatcher/issues/290#issuecomment-230357983
