### ISSUE TITLE
How can I make it start automatically on reboot?

### ISSUE THREAD

**Issue by sphereweb83** [sj26/mailcatcher#410]
Hello, I love this app and i would like to know how to make it start automatically on boot using Ubuntu 16.04.

Thank you!

**Comment by sj26** [comment]
Sorry I don't use Ubuntu 16.04 as a desktop so I'm not sure, but I'd guess using systemd would be your best bet. Something like this, maybe:

https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd
