### ISSUE TITLE
Latest version on website out of date

### ISSUE THREAD

**Issue by goalaleo** [sj26/mailcatcher#413]
https://mailcatcher.me/

<img width="746" alt="Screenshot 2020-02-20 09 17 45" src="https://user-images.githubusercontent.com/3275302/74909888-ea204b80-53c1-11ea-92cc-197508ff2593.png">

**Comment by sj26** [comment]
Thanks, covered by https://github.com/sj26/mailcatcher/issues/404

**Comment by sj26** [comment]
(Also manually fixed, now.)
