### ISSUE TITLE
Can't install - "You have to install development tools first"

### ISSUE THREAD

**Issue by Eddcapone** [sj26/mailcatcher#418]
I get "**yOu hAvE tO iNsTaLl dEvElOpMeNt tOoLs fIrSt**" even though I installed them via `apt-get install ruby-dev` before `gem install mailcatcher`

**Comment by sj26** [comment]
Cool. Maybe install the development tools? Like `apt-get install build-essential` or whatever is required on your system?

**Comment by Eddcapone** [comment]
Now I get

> ERROR:  Error installing mailcatcher:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /var/lib/gems/2.5.0/gems/sqlite3-1.4.2/ext/sqlite3
> /usr/bin/ruby2.5 -r ./siteconf20200428-3047-ka50ai.rb extconf.rb
> checking for sqlite3.h... no
> sqlite3.h is missing. Try 'brew install sqlite3',
> 'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
> and check your shared library search path (the
> location where your sqlite3 shared library is located).
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.

The log file contains:

> package configuration for sqlite3 is not found
> find_header: checking for sqlite3.h... -------------------- no
> 
> "gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.5.0 -I/usr/include/ruby-2.5.0/ruby/backward -I/usr/include/ruby-2.5.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.5-FmXXMa/ruby2.5-2.5.5=. -fstack->
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2:
> 3: int main(int argc, char **argv)
> 4: {
> 5:   return 0;
> 6: }
> /* end */
> 
> "gcc -E -I/usr/include/x86_64-linux-gnu/ruby-2.5.0 -I/usr/include/ruby-2.5.0/ruby/backward -I/usr/include/ruby-2.5.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.5-FmXXMa/ruby2.5-2.5.5=. -fstack-protector>
> conftest.c:3:10: fatal error: sqlite3.h: No such file or directory
>     3 | #include <sqlite3.h>
>       |          ^~~~~~~~~~~
> compilation terminated.
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2:
> 3: #include <sqlite3.h>
> /* end */
> 
> --------------------
>

**Comment by sj26** [comment]
Sounds like you need the sqlite3 headers, however they are packaged on Ubuntu :-)

**Comment by sj26** [comment]
The output you posted contains your solution: `apt-get install libsqlite3-dev`

**Comment by Eddcapone** [comment]
Thank you! I totally missed it... Now it works :)
