### ISSUE TITLE
Can you only open the webinterface from the local machine? ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Eddcapone** [sj26/mailcatcher#419]
I installed and started mailcatcher on a Ubuntu 19.10 system to which I always connect remotely from my home via SSH.

I tried to open the webinterface from home with http://SERVER_IP:1080, but I get "ERR_CONNECTION_REFUSED" even after allowing the port in the firewall with `ufw allow 1080` 

Does it only work localy?

**Comment by sj26** [comment]
MailCatcher listens on the local interface only by default for security. If you want to open it up, checkout `mailcatcher --help` for options. You probably want `mailcatcher --ip 0.0.0.0` (listen on all interfaces). But keep in mind this means *anyone* can access mailcatcher if they can access the host it's running on. Use firewalls, etc.
