### ISSUE TITLE
Support using Mailcatcher in a subdirectory path

### ISSUE THREAD

**Issue by ottok** [sj26/mailcatcher#421]
I would like to run Mailcatcher on real servers (not production, but test and dev servers). Instead of running Mailcatcher on a dedicated domain such as `mailcatcher.example.com` I'd like to run it in a subdirectory such as `example.com/debug/mailcatcher/`.

Right now this is not possible because Mailcatcher always assumes it is run on the top-level path. References to assets is always via `/assets/mailcatcher.js`. They are not relative and thus do not load anything from `example.com/debug/mailcatcher/assets/mailcatcher.js`, which it should, to be able to run in a subdirectory.

Would you be OK with this idea? Any pointers what sections of code I need to modify to get this going? I am happy to make a PR for you if you give some pointers.

**Comment by sj26** [comment]
This is supported in the latest mailcatcher beta using `--http-path=/debug` for example. Try `gem install --pre mailcatcher` and give it a go.

**Comment by ottok** [comment]
Sorry for the delay. I confirm this indeed works with latest 0.8.0.beta2:

![image](https://user-images.githubusercontent.com/668724/83389346-bf9a5180-a3f8-11ea-94b3-3032f083af0d.png)


Thanks! :smiley:

**Comment by ottok** [comment]
I hope you would release 0.8.0 soon.. The beta version has worked fine for me.

**Comment by joso9001** [comment]
I'm using this too! Works well.

**Comment by JockeTF** [comment]
I'm using this too! Works well.
