### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by sylvainbx** [sj26/mailcatcher#423]
Hi there,
The docker image was built 2 years ago for the last time. Maybe this is time for an update? :)

**Comment by sylvainbx** [comment]
For those interested, I've made a fork using the last release (0.8.0.beta2) and alpine linux.
Check out at [sleede/mailcatcher](https://hub.docker.com/repository/docker/sleede/mailcatcher/)

**Comment by sj26** [comment]
Sorry, I thought they were auto building. I’ve just configured them to do so, and have manually kicked off a rebuild,

**Comment by sj26** [comment]
The docker image has been updated to use alpine, and now clocks in at ~25MB total, only 5.85MB (compressed) of that is a unique layer for mailcatcher.

https://hub.docker.com/layers/sj26/mailcatcher/latest/images/sha256-ea9cc63aaceb360b5bc3c5d3a090e0d69905b2b5e3eaf2d4e7b311bed9cfbe0e?context=repo

I've also pushed both linux/arm64 and linux/amd64 images.
