### ISSUE TITLE
Latest release version number in mailcatcher.me

### ISSUE THREAD

**Issue by Rafi993** [sj26/mailcatcher#424]
The https://mailcatcher.me/ website says the latest released version is in Feb 2016 (version 0.6.4) but the there have been quite few releases after that.

![mailcatcher](https://user-images.githubusercontent.com/8092120/84291680-11fb1100-ab63-11ea-8099-26a9728e6a18.png)

**Comment by sj26** [comment]
Thanks, covered by #404
