### ISSUE TITLE
Feature Request: Vertical Layout

### ISSUE THREAD

**Issue by rajeshisnepali** [sj26/mailcatcher#425]
![image](https://user-images.githubusercontent.com/23610013/87781743-fd402600-c850-11ea-9fc3-d2c2d7783433.png)

Recently, I switched from Mailtrap to here and it is cool. Can we get a vertical layout just like in Mailtrap?

**Comment by sj26** [comment]
Hmm, probably not, sorry - I like to keep mailcatcher simple and don’t want to introduce and manage alternative layouts.
