### ISSUE TITLE
MailCatcher crash

### ISSUE THREAD

**Issue by Narf-stack** [sj26/mailcatcher#426]
Hi all, 

Here what I have done:

- Start mailcatcher on the command line via mailcatcher
- Visit http://localhost:1080
- Page loads, but server crashes with this error:

`Starting MailCatcher
==> smtp://127.0.0.1:1025
/Users/utilisateur/.rvm/gems/ruby-2.6.3/gems/thin-1.5.1/lib/thin/server.rb:104: warning: constant ::Fixnum is deprecated
==> http://127.0.0.1:1080/`

I'm using Rails 5.2.3, Ruby 2.6.3-p62 (x86_64-darwin17) and mailcatcher (0.7.1)

Does anyone have any ideas what might have happened here ?

Thanks for your help.

**Comment by sj26** [comment]
Hmm, that warning is not abnormal, and will not be the cause of your crash.

You mention running rails. You are not [including mailcatcher in your Gemfile](https://github.com/sj26/mailcatcher), I hope?

**Comment by Narf-stack** [comment]
Yes actually ! At first I did. Then, when it crashed, I took it out and did a " gem install mailcatcher" from the terminal.  Both ended up to the same outcome though.

**Comment by sj26** [comment]
Weird!

Can you try running mailcatcher in the foreground, like:

```
mailcatcher --foreground
```

Then access the web interface, and see if you get any additional output?

Could you also provide the output of:

```
gem list
```

**Comment by Narf-stack** [comment]
I did run mailcatcher in the foreground,and the server did not crash this time. I am surprised that it was enough for it to works, but eh!


here is the output of the `gem list `command :

`*** LOCAL GEMS ***

actioncable (5.2.3)
actionmailer (5.2.3)
actionpack (5.2.3)
actionview (5.2.3)
activejob (5.2.3)
activemodel (5.2.3)
activerecord (5.2.3)
activestorage (5.2.3)
activesupport (5.2.3)
addressable (2.7.0)
arel (9.0.0)
autoprefixer-rails (9.8.5, 9.6.1.1)
aws_cf_signer (0.1.3)
bcrypt (3.1.15, 3.1.13)
bigdecimal (default: 1.4.1)
bindex (0.8.1)
bootsnap (1.4.7, 1.4.4)
builder (3.2.4, 3.2.3)
bundler (2.1.4, default: 1.17.3)
bundler-unload (1.0.2)
byebug (11.1.3, 11.0.1)
cloudinary (1.12.0)
cmath (default: 1.0.0)
cocoon (1.2.14)
coderay (1.1.3, 1.1.2)
coffee-rails (5.0.0, 4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.1.6, 1.1.5)
connection_pool (2.2.3, 2.2.2)
crass (1.0.6, 1.0.4)
csv (default: 3.0.9)
d3-rails (5.9.2)
daemons (1.3.1)
date (default: 2.0.0)
dbm (default: 1.0.0)
devise (4.7.2, 4.7.0)
devise-i18n (1.9.1, 1.8.1)
did_you_mean (1.3.0)
domain_name (0.5.20190701)
dotenv (2.7.6, 2.7.5)
dotenv-rails (2.7.6, 2.7.5)
e2mmap (default: 0.1.0)
erubi (1.9.0, 1.8.0)
etc (default: 1.0.1)
eventmachine (1.2.7, 1.0.9.1)
execjs (2.7.0)
executable-hooks (1.6.0)
fcntl (default: 1.0.0)
ffi (1.13.1, 1.11.1)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
flatpickr (4.6.3.1, 4.5.7.0)
font-awesome-sass (5.6.1)
forwardable (default: 1.2.0)
gem-wrappers (1.4.0)
globalid (0.4.2)
haml (5.1.2)
http-accept (1.7.0)
http-cookie (1.0.3)
i18n (1.8.5, 1.6.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jbuilder (2.10.0, 2.9.1)
json (2.3.1, 2.2.0, default: 2.1.0)
launchy (2.5.0, 2.4.3)
letter_opener (1.7.0)
listen (3.0.8)
logger (default: 1.3.0)
loofah (2.6.0, 2.2.3)
mail (2.7.1)
mailcatcher (0.7.1)
marcel (0.3.3)
matrix (default: 0.1.0)
method_source (1.0.0, 0.9.2)
mime-types (3.3.1, 3.2.2)
mime-types-data (3.2020.0512, 3.2019.0331)
mimemagic (0.3.5, 0.3.3)
mini_mime (1.0.2)
mini_portile2 (2.4.0)
minitest (5.14.1, 5.11.3)
msgpack (1.3.3, 1.3.1)
mustermann (1.1.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
nio4r (2.5.2, 2.4.0)
nokogiri (1.10.10, 1.10.4)
openssl (default: 2.1.2)
orm_adapter (0.5.0)
ostruct (default: 0.1.0)
pg (1.2.3, 0.21.0)
postmark (1.21.1, 1.15.0)
postmark-rails (0.20.0, 0.19.0)
power_assert (1.1.3)
prime (default: 0.1.0)
pry (0.13.1, 0.12.2)
pry-byebug (3.9.0, 3.7.0)
pry-rails (0.3.9)
psych (default: 3.1.0)
public_suffix (4.0.5, 4.0.1)
puma (4.3.5, 4.1.0)
rack (2.2.3, 2.0.7, 1.6.13)
rack-protection (2.0.8.1, 2.0.7, 1.5.5)
rack-proxy (0.6.5)
rack-test (1.1.0)
rails (5.2.3)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.3.0, 1.2.0)
rails-i18n (5.1.3)
railties (5.2.3)
rake (13.0.1, 12.3.3, 12.3.2)
rb-fsevent (0.10.4, 0.10.3)
rb-inotify (0.10.1, 0.10.0)
rdoc (default: 6.1.0)
redis (4.2.1, 4.1.2)
responders (3.0.1, 3.0.0)
rest-client (2.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
ruby2_keywords (0.0.2)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
sass (3.7.4)
sass-listen (4.0.0)
sass-rails (5.1.0)
sassc (2.4.0, 2.1.0)
sassc-rails (2.1.2)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
semantic_range (2.3.0)
shell (default: 0.7)
sidekiq (6.1.1, 6.0.0)
sidekiq-failures (1.0.0)
simple_form (5.0.2, 4.1.0)
sinatra (2.0.8.1, 2.0.7, 1.4.8)
skinny (0.2.4, 0.2.2)
spring (2.1.0)
spring-watcher-listen (2.0.1)
sprockets (4.0.2, 3.7.2)
sprockets-rails (3.2.1)
sqlite3 (1.4.2)
sqlite3-ruby (1.3.3)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
temple (0.8.2)
test-unit (3.2.9)
thin (1.7.2, 1.5.1)
thor (1.0.1, 0.20.3)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tilt (2.0.10, 2.0.9)
tracer (default: 0.1.0)
tzinfo (1.2.7, 1.2.5)
uglifier (4.2.0, 4.1.20)
unf (0.1.4)
unf_ext (0.0.7.7)
warden (1.2.8)
web-console (3.7.0)
webpacker (5.1.1, 4.0.7)
webrick (default: 1.4.2)
websocket-driver (0.7.3, 0.7.1)
websocket-extensions (0.1.5, 0.1.4)
wicked_pdf (2.1.0, 1.4.0)
wkhtmltopdf-binary (0.12.4)
xmlrpc (0.3.0)`

**Comment by sj26** [comment]
Tricky! Must be something about the daemonisation. And your gem list looks fine. Without any crash output I don't think I can offer much more other than a recommendation to run in foreground, sorry.

**Comment by Narf-stack** [comment]
Yeah, probably that. Thanks for the help though!
