### ISSUE TITLE
Maybe remove the porn link from the bottom of the documentation. (or mark nsfw)

### ISSUE THREAD

**Issue by bumpusfrancus** [sj26/mailcatcher#427]

**Comment by thaJeztah** [comment]
Guess you mean the links that were removed in https://github.com/sj26/mailcatcher/commit/aff5ab7a61c976863257708e77d283db3f757b49

@sj26 looks like the website was not rebuilt after that?

**Comment by sj26** [comment]
Woah, what porn link?? There definitely shouldn't be one!

**Comment by sj26** [comment]
Ah, I see. Seems like the fun video game I linked to has bit rotted and the domain has been hijacked. I'll remove the link ASAP.

Sorry, and thank you for letting me know.

**Comment by bumpusfrancus** [comment]
Thanks :)

**Comment by sj26** [comment]
Looks like it was already removed from the README.md, but was still on [the website](https://mailcatcher.me). I've updated the website to the latest version of the README which no longer has the link.

Sorry again, definitely not intentional. 😔

**Comment by thaJeztah** [comment]
Thanks @sj26!
