### ISSUE TITLE
Installation Fails on Catalina

### ISSUE THREAD

**Issue by fny** [sj26/mailcatcher#430]
Currently, thin doesn't install while installing mailcatcher on macOS Catallina. This is related to https://github.com/macournoyer/thin/issues/365.

```
Building native extensions. This could take a while...
ERROR:  Error installing mailcatcher:
	ERROR: Failed to build gem native extension.

    current directory: /Users/faraz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thin-1.5.1/ext/thin_parser
/Users/faraz/.asdf/installs/ruby/2.7.1/bin/ruby -I /Users/faraz/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0 -r ./siteconf20200924-11494-letgol.rb extconf.rb
checking for main() in -lc... yes
creating Makefile

current directory: /Users/faraz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thin-1.5.1/ext/thin_parser
make "DESTDIR=" clean

current directory: /Users/faraz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thin-1.5.1/ext/thin_parser
make "DESTDIR="
compiling parser.c
parser.rl:112:17: warning: comparison of integers of different signs: 'long' and 'unsigned long' [-Wsign-compare]
  assert(pe - p == len - off && "pointers aren't same distance");
         ~~~~~~ ^  ~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
parser.rl:142:7: error: implicit declaration of function 'thin_http_parser_has_error' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (thin_http_parser_has_error(parser) ) {
      ^
parser.rl:142:7: note: did you mean 'http_parser_has_error'?
./parser.h:44:5: note: 'http_parser_has_error' declared here
int http_parser_has_error(http_parser *parser);
    ^
parser.rl:144:14: error: implicit declaration of function 'thin_http_parser_is_finished' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  } else if (thin_http_parser_is_finished(parser) ) {
             ^
1 warning and 2 errors generated.
make: *** [parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/faraz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thin-1.5.1 for inspection.
```

**Comment by mr-sigma** [comment]
Got mine working by running:
```
gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
gem install mailcatcher
```

**Comment by thomasvanholder** [comment]
Running this comment only worked for me.
```batch
gem install mailcatcher -- --with-cflags="-Wno-error=implicit-function-declaration"
```

**Comment by Qwertie-** [comment]
It looks like this issue is fixed in version 1.8.0 of thin. The cflags fix works but it would be nice if we could get the thin version updated for mailcatcher.

**Comment by mansoor-wal** [comment]
> gem install mailcatcher



> Got mine working by running:
> 
> ```
> gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
> gem install mailcatcher
> ```

This worked for me.

**Comment by abaldwin88** [comment]
> Got mine working by running:
> 
> ```
> gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
> gem install mailcatcher
> ```

I had to run this on ruby 3.0.1 to get mailcatcher to install

**Comment by 88patota** [comment]
> Got mine working by running:
> 
> ```
> gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
> gem install mailcatcher
> ```
This worked for me. I'm using MacBook Air m1 chip.

**Comment by TCCDevelopment** [comment]
With macOS Monterey, I had to run this to get mine working: 

```
gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
gem install mailcatcher -- --with-cppflags=-I/usr/local/opt/openssl/include   
```

**Comment by salsasource** [comment]
> Got mine working by running:
> 
> ```
> gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"
> gem install mailcatcher
> ```

This worked for me.

**Comment by K4sku** [comment]
To anyone here looking for answer: Until version 0.9.0 is released You can use `gem install mailcatcher --pre`

**Comment by dilip49** [comment]
> To anyone here looking for answer: Until version 0.9.0 is released You can use `gem install mailcatcher --pre` Thin dependency is updated to 1.8.0 In 0.9.0.beta2

@K4sku worked for me. Thanks!
