### ISSUE TITLE
zsh: /usr/local/bin/mailcatcher: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory

### ISSUE THREAD

**Issue by emtiazzahid** [sj26/mailcatcher#433]
After upgrading to macOS to catalina getting `zsh: /usr/local/bin/mailcatcher: bad interpreter: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: no such file or directory` this error on mailcatcher

**Comment by sj26** [comment]
You may need to try reinstalling the gem if your version of tiny has changed (macOS upgrade).
