### ISSUE TITLE
Suggestion: Show MailCatcher version

### ISSUE THREAD

**Issue by ThomasLandauer** [sj26/mailcatcher#436]
Just tried to find out which version of MailCatcher I have - but couldn't find it anywhere...

So I'm suggesting to display it:
* In the terminal, after starting:
  > Starting MailCatcher 0.7.1
* In the web interface after the name (top left corner): <a>MailCatcher</a> 0.7.1

**Comment by sj26** [comment]
Run:

```
$ mailcatcher --version
mailcatcher 0.7.1
```

But it could be in more places. `--version` is missing from the args list in help. Help could also include the version, although I don't have a lot of control over optparser. The starting message could include it. I'm not convinced it belongs in the web interface. Perhaps in a pop up, when clicking the logo. I've always wanted to include an up-to-date check in the web interface somewhere.

**Comment by sj26** [comment]
MailCatcher now outputs the version on the terminal when started, per your suggestion:
https://github.com/sj26/mailcatcher/commit/e84f4b6ea68eaa7b274bcaf0cc83c9f8ac6efa7e
```
$ mailcatcher
Starting MailCatcher v0.8.0.beta3
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080/
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

**Comment by ThomasLandauer** [comment]
Closing in favor of https://github.com/sj26/mailcatcher/issues/479
