### ISSUE TITLE
not able to install mailcatcher

### ISSUE THREAD

**Issue by yayas87** [sj26/mailcatcher#438]
i am using ubuntu 18 in windows as wsl
i am not able to install mailcatcher. this is was working before.
getting this error
` sudo gem install mailcatcher
ERROR:  Could not find a valid gem 'skinny' (~> 0.2.3), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)`

My Env

>$ gem environment
/usr/lib/ruby/2.5.0/rubygems/commands/environment_command.rb:154: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/jaseer/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.5
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/jaseer/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.5.0
     - /home/jaseer/.gem/ruby/2.5.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2020.824.0_x64__79rhkp1fndgsc
     - /mnt/c/WINDOWS/system32
     - /mnt/c/WINDOWS
     - /mnt/c/WINDOWS/System32/Wbem
     - /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
     - /mnt/c/WINDOWS/System32/OpenSSH/
     - /mnt/c/Users/Dell/AppData/Roaming/Composer/vendor/drush/drush
     - /mnt/c/ProgramData/ComposerSetup/bin
     - /mnt/c/Program Files/Git/cmd
     - /mnt/c/Program Files/nodejs/
     - /mnt/c/Program Files/Docker/Docker/resources/bin
     - /mnt/c/ProgramData/DockerDesktop/version-bin
     - /mnt/c/Users/Dell/AppData/Local/Microsoft/WindowsApps
     - /mnt/c/Users/Dell/AppData/Roaming/Composer/vendor/bin
     - /mnt/c/Program Files/JetBrains/PhpStorm 2019.2.4/bin
     - /mnt/c/Users/Dell/AppData/Roaming/npm
     - /snap/bin

**Comment by sj26** [comment]
Sorry this sounds like a problem with your network, not mailcatcher.
