### ISSUE TITLE
Upgrade docker image to latest release

### ISSUE THREAD

**Issue by nodiscc** [sj26/mailcatcher#439]
The latest release is `v0.7.1` but https://hub.docker.com/r/sj26/mailcatcher on tag `:latest` is still on 0.6.5

This makes it impossible to use newer options such as `--http-path` (https://github.com/sj26/mailcatcher/issues/227) form the official Docker image.

Please consider releasing images for each releases with appropriate tags, and/or rebuild the `:latest` image from `master`

**Comment by sj26** [comment]
Fixed by #444.
