### ISSUE TITLE
Support forwording the email to Gotify Notifications

### ISSUE THREAD

**Issue by SalehAlolayan** [sj26/mailcatcher#441]
Dear,
Good day,

I was wondering if you would support and instruct in how we could forward the email to Gotify Notifications, in my use case i would configure all my services in my homelab to send there email to mailcatcher as a centralized email centre, but i will be grate if i'm able to get a notification of the received email while I'm out of home, i found gotify can ease this task. alot of homelab users would love this addition.

to make it clear:

Service -> mailcatcher -> Gotify

Thanks,

**Comment by sj26** [comment]
Sorry, this is not something MailCatcher is designed to do. You might be interesting in trying [MailHog](https://github.com/mailhog/MailHog) — it has a more comprehensive API and forwarding capabilities.
