### ISSUE TITLE
Mailcatcher executes Javascript in body of the email

### ISSUE THREAD

**Issue by S-DICKSON** [sj26/mailcatcher#442]
Hi, when email content includes JS it executes the script when selecting the tab ``Plain Text`` when viewing email.

**Example Email Body**
```<script>alert("YOu juST beEn hackED ( ͡° ͜ʖ ͡°) ")</script>```

**Screenshot**
![image](https://user-images.githubusercontent.com/52682455/106766789-1c0dda80-6632-11eb-96b1-1b06c986c898.png)

**Comment by j-dohnalek** [comment]
This could be tried a bit different, and perhaps throught the staging environment which is exactly the same as production but different database. This would allow to sent email with JavaScript for testing.

**Comment by j-dohnalek** [comment]
Maybe not https://www.thoughtco.com/javascript-and-emails-2037682

**Comment by sj26** [comment]
Yeah the plain text tab doesn't do a good job escaping html tags, since a contributed change a while back to autolink urls in text.

**Comment by sj26** [comment]
This is tracked in a new issue #446, please follow there.
