### ISSUE TITLE
Using Rack 2

### ISSUE THREAD

**Issue by empeje** [sj26/mailcatcher#453]
Hi Team, I enjoyed mailcatcher a lot and I'm currently developing app using Rails 6 and Ruby 3. Somehow, in my list of Gem, there's already Rack 2 used and mailcatcher still uses Rack 1.x. Any plan in the future to use newer version of Rack?

**Comment by sj26** [comment]
Not in the short term sorry, no. The dependency tree through eventmachine, thin and skinny are blocking upgrades, and nobody has yet looked at the problem holistically.

Please make sure you're not including mailcatcher in your Gemfile:

https://github.com/sj26/mailcatcher#bundler

Or is the problem Ruby 3? I haven't tried it there.

**Comment by empeje** [comment]
Thanks for the response @sj26 

I found that the issue, the issue is because I include `mailcatcher` in the Gemfile, my plan is to use `foreman` to run any dev service locally.

However, I found a better solution, I can include `mailcatcher` in a `docker compose` so that when I need it I just need to run `mailcatcher `docker locally.

**Comment by Intrepidd** [comment]
@empeje just so you know, you can just `gem install mailcatcher` and use it in your Procfile, it will work flawlessly and no need to spin a container ;)

**Comment by empeje** [comment]
Thanks @Intrepidd
