### ISSUE TITLE
Encoding::UndefinedConversionError - "\xF0" from ASCII-8BIT to UTF-8:

### ISSUE THREAD

**Issue by vedmant** [sj26/mailcatcher#456]
Hi, I have following error:

mailcatcher_1  | *** Error sending message through websocket: {...

mailcatcher_1  |     Exception: "\xF0" from ASCII-8BIT to UTF-8
mailcatcher_1  |     Backtrace:
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `encode'
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
mailcatcher_1  |        mailcatcher (0.6.5) lib/mail_catcher/web/application.rb:69:in `block (3 levels) in <class:Application>'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (3 levels) in push'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block (2 levels) in push'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `each'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `block in push'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:256:in `schedule'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/em/channel.rb:43:in `push'
mailcatcher_1  |        mailcatcher (0.6.5) lib/mail_catcher/mail.rb:57:in `block in add_message'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:981:in `block in run_deferred_callbacks'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `times'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:978:in `run_deferred_callbacks'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
mailcatcher_1  |        eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
mailcatcher_1  |        mailcatcher (0.6.5) lib/mail_catcher.rb:173:in `run!'
mailcatcher_1  |        mailcatcher (0.6.5) bin/mailcatcher:5:in `<top (required)>'
mailcatcher_1  |        /usr/local/bundle/bin/mailcatcher:23:in `load'
mailcatcher_1  |        /usr/local/bundle/bin/mailcatcher:23:in `<main>'
mailcatcher_1  |     Please submit this as an issue at http://github.com/sj26/mailcatcher/issues
app_1          | [17/Apr/2021 11:48:43] "POST /api/v1/login HTTP/1.1" 200 16
mailcatcher_1  | 2021-04-17 11:48:45 - Encoding::UndefinedConversionError - "\xF0" from ASCII-8BIT to UTF-8:
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `encode'
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
mailcatcher_1  |        /usr/local/lib/ruby/2.4.0/json/common.rb:224:in `generate'
mailcatcher_1  |        /usr/local/bundle/gems/mailcatcher-0.6.5/lib/mail_catcher/web/application.rb:94:in `block in <class:Application>'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
mailcatcher_1  |        /usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/urlmap.rb:66:in `block in call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `each'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/rack-1.6.10/lib/rack/builder.rb:153:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/mailcatcher-0.6.5/lib/mail_catcher/web.rb:19:in `call'
mailcatcher_1  |        /usr/local/bundle/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
mailcatcher_1  |        /usr/local/bundle/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
mailcatcher_1  |        /usr/local/bundle/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
mailcatcher_1  |        /usr/local/bundle/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
mailcatcher_1  |        /usr/local/bundle/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
mailcatcher_1  |        /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
mailcatcher_1  |        /usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
mailcatcher_1  |        /usr/local/bundle/gems/mailcatcher-0.6.5/lib/mail_catcher.rb:173:in `run!'
mailcatcher_1  |        /usr/local/bundle/gems/mailcatcher-0.6.5/bin/mailcatcher:5:in `<top (required)>'
mailcatcher_1  |        /usr/local/bundle/bin/mailcatcher:23:in `load'
mailcatcher_1  |        /usr/local/bundle/bin/mailcatcher:23:in `<main>'

**Comment by pjar** [comment]
For now the only thing that explains it is the ruby upgrade - we started getting this after going from ruby 2.2.x to 2.5.9

**Comment by sj26** [comment]
This should be fixed by #467.

**Comment by sj26** [comment]
Your SMTP client and mail library should be correctly encoding mail message bodies to only contain 7-bit ASCII characters, per [RFC5321](https://datatracker.ietf.org/doc/html/rfc5321). Wider characters can be supplied in smtp by using quoted strings, and in mail bodies by using encodings like quoted printable, and most smtp clients and mail libraries will handle this transparently. I suggest checking that your SMTP client and mail library are conforming to standards. Many SMTP servers are quite lenient with these sorts of issues, so you might be fine. But you might also have trouble sending email over the wider Internet.
