### ISSUE TITLE
Support multiple "endpoints"

### ISSUE THREAD

**Issue by Bertg** [sj26/mailcatcher#459]
Mailcatcher is pretty great. I'd love to use it as part of my end to end tests suite. For that test suite to run properly it would be nice that I can clear it on every test, without it affecting my development emails.

Sure, I can run multiple instances of Mailcatcher, and that works ok, but it would be nice if Mailcatcher had some built in support. I would call it `many-mailcacher-mode`. It has a ring to it no?

Goals:

* Provide "opt in" multiple "endpoints"
* Keep current API's and URL's working as is

Proposal:

* Support multiple "endpoints" through the SMTP username. Not using a username, equals to using "default".
* All web and API routes get an "endpoints" prefix. This prefix is optional, and defaults to "default" if not provided.

Would there be interest in this feature? If I created a PR for it, would it be accepted?

**Comment by Bertg** [comment]
@sj26 I know you want to keep the scope of this project minmal, so I'd really like to have your 2 cents here :)

**Comment by sj26** [comment]
Sorry @Bertg, it's a nice suggestion, but I think this is out of scope.
