### ISSUE TITLE
Handling large amounts of messages

### ISSUE THREAD

**Issue by adamsilkcm** [sj26/mailcatcher#464]
With a large number of messages, the web interface becomes effectively unresponsive as the number of new messages continues to tick up.  They can be cleared or read from the API (though getting individual messages requires guessing their ID or otherwise ingesting JSON into something else), but I'd request that the web interface stop loading old messages after a certain amount unless requested via a "Load Next 1000 messages" or similar button (continuing to add new ones should be fine, though).

Please let me know if further information is needed.

**Comment by sj26** [comment]
MailCatcher isn't designed to keep large amounts of messages. I'd suggest clearing your messages more frequently.

**Comment by sj26** [comment]
There are some improvements in the latest beta which should make it slightly better. The message body is no longer included in the API responses when listing messages.

To try it out in the latest beta:

```
gem install --pre mailcatcher
```
