### ISSUE TITLE
Encoded attachments if email is formatted as HTML

### ISSUE THREAD

**Issue by veelenga** [sj26/mailcatcher#468]
When email is sent as a text/plain, the attachments are properly added to email and downloadable in mailcatcher:

![image](https://user-images.githubusercontent.com/3624712/125266226-4a44c400-e30e-11eb-9c63-46d1cb3f3e77.png)

However, when the email is sent in html format, attachments are displayed as part of the body and converted to Base64:

![image](https://user-images.githubusercontent.com/3624712/125266387-73655480-e30e-11eb-995e-bc22b1d0b3fd.png)

Is there any way to make it attached be downloadable as an in the first example?

**Comment by sj26** [comment]
Weird! Do you have an example email which reproduces the issue?

**Comment by veelenga** [comment]
Sorry, i think that was problem on my end. The mail was sent with explicit content type:
