### ISSUE TITLE
mailcatcher 0.8.x doesn't support ruby 2.x as claimed

### ISSUE THREAD

**Issue by daggaz** [sj26/mailcatcher#482]
This commit:
https://github.com/sj26/mailcatcher/commit/626a7b7a651151dd4222962d0d8d7b12c619be3c

Introduces syntax that is incompatible with ruby 2:
```
mail_catcher/smtp.rb:48:in `receive_data_chunk': undefined method `+@' for "":String (NoMethodError)
```

But [rubygems](https://rubygems.org/gems/mailcatcher/) still claims:
> REQUIRED RUBY VERSION:
> \>= 2.0.0

**Comment by sj26** [comment]
Yeah, sorry, the required ruby version wasn't correct in the gemspec. I've updated it to reflect 2.6+ which is the oldest maintained ruby version:
https://github.com/sj26/mailcatcher/commit/adac49c3b5a4c1bbd78de331d8b8828ab0efac09
