### ISSUE TITLE
Thin is too old

### ISSUE THREAD

**Issue by SaimonL** [sj26/mailcatcher#487]
Please change 

```ruby
s.add_dependency "thin", "~> 1.5.0"
```

TO

```ruby
s.add_dependency "thin", "~> 1.8.1"
```

To prevent warning

```
warning: constant ::Fixnum is deprecated
```

**Comment by sj26** [comment]
No, sorry, thin is pinned to an old version for reason. We're migrating away from it in the long term. For now, the warning is annoying but harmless.

**Comment by bensaufley** [comment]
FYI as of Ruby 3.2.0, [this is no longer harmless](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/) as Fixnum has been entirely removed
