### ISSUE TITLE
Invalid Option -f -- foreground

### ISSUE THREAD

**Issue by devweb-concept** [sj26/mailcatcher#491]
Hello,

I'm using Mailcatcher 0.8.1 and i'm not able to use it with the foreground option.

`# mailcatcher -f`

        W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:156:in 'block in parse!': invalid option: -f (OptionParser::InvalidOption)
                from <internal:kernel>:90:in 'tap'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:89:in 'parse!'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:164:in 'run!'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/bin/mailcatcher:6:in '<top (required)>'
                from W:/Ruby30-x64/bin/mailcatcher:23:in 'load'
                from W:/Ruby30-x64/bin/mailcatcher:23:in '<main>'

        W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:156:in 'block in parse!': invalid option: f (OptionParser::InvalidOption)
                from <internal:kernel>:90:in 'tap'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:89:in 'parse!'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/lib/mail_catcher.rb:164:in 'run!'
                from W:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mailcatcher-0.8.1/bin/mailcatcher:6:in '<top (required)>'
                from W:/Ruby30-x64/bin/mailcatcher:23:in 'load'
                from W:/Ruby30-x64/bin/mailcatcher:23:in '<main>'

The help doesn't list the foreground neither ...

`# mailcatcher --version`
        MailCatcher v0.8.1
        

`# mailcatcher --help`
        Usage: mailcatcher [options]
        MailCatcher v0.8.1
        

        --ip IP                      Set the ip address of both servers
        --smtp-ip IP                 Set the ip address of the smtp server
        --smtp-port PORT             Set the port of the smtp server
        --http-ip IP                 Set the ip address of the http server
        --http-port PORT             Set the port address of the http server
        --messages-limit COUNT       Only keep up to COUNT most recent messages
        --http-path PATH             Add a prefix to all HTTP paths
        --no-quit                    Don't allow quitting the process
    -b, --browse                     Open web browser
    -v, --verbose                    Be more verbose
    -h, --help                       Display this help information
        --version                    Display the current version

**Comment by sj26** [comment]
It looks like you're using mailcatcher on windows. Windows does not support running in the background, so mailcatcher always runs in the foreground, and the option is not available.
