### ISSUE TITLE
Mailcatcher 0.8.2 is not published to Docker Hub

### ISSUE THREAD

**Issue by lnhrdt** [sj26/mailcatcher#497]
The latest version on Docker Hub is 0.8.1. Could you update your published image with the latest release?

https://hub.docker.com/r/sj26/mailcatcher

**Comment by lnhrdt** [comment]
Appreciate you maintaining a version for the community @spaquet! I prefer to use an official image for my use case though.

@sj26 any chance of updating this? Or is there a way I could help get it done?

**Comment by sj26** [comment]
MailCatcher v0.8.2 is now [available on Docker Hub](https://hub.docker.com/layers/mailcatcher/sj26/mailcatcher/v0.8.2/images/sha256-a544701d2d5939144c781d80b13f6f93568f4753af5bb715a81380167703b8b5).

I'm interested in automating the building of images. They would need to be built based on the rubygem being pushed I guess? Although I do also upload the gem binary as github releases. Perhaps the Docker image could be built from the github release event and attached gem binary? Something to look at in a separate issue/PR.
