### ISSUE TITLE
Implement catchmail -t?

### ISSUE THREAD

**Issue by hanoii** [sj26/mailcatcher#500]
Could we make it so that the `From:` header is used as the from sender instead of `-f`, similar to how `sendmail -t` does it?

**Comment by sj26** [comment]
I'm not familiar with `sendmail -t`, but `catchmail` is intentionally kept pretty simple so I'm hesitant to add more options. You can use sendmail with an smtp transport pointed at mailcatcher if you need increased compatibility.
