### ISSUE TITLE
Plain text tab doesn't display HTML after I upgraded to Ubuntu 22.04

### ISSUE THREAD

**Issue by nd3w** [sj26/mailcatcher#507]
After I upgraded to Ubuntu 22.04 (Xubuntu precisely), mailcatcher doesn't display HTML at the 'Plain Text' tab, it displays its source instead.

**Comment by sj26** [comment]
Sorry that's happening for you. I haven't heard of this problem happening for anybody else.

Can you download the message source you're expecting to show a plain text tab and paste it here?

**Comment by sj26** [comment]
Please reopen with more details if you are still having this issue.

**Comment by nd3w** [comment]
Sorry it took a long time to reply your post before. Here's the screenshot:
![mailcatcher](https://user-images.githubusercontent.com/2328329/177466266-7cd7711a-e0da-43b2-a685-966261401e97.jpg)

**Comment by sj26** [comment]
> Can you download the message source you're expecting to show a plain text tab and paste it here?

**Comment by nd3w** [comment]
> 

Sorry took sometime to reply your message. This is the email I downloaded (with some text altered):

`Return-Path: <test@local.dev>
Date: Mon, 11 Jul 2022 14:07:02 +0700
To: myemailaddresssomewh@gmail.com
Message-ID: <62cbcc1613cc8_623b46039750@dweb-laptop.mail>
Subject: Verifikasi Email Pembelian Formulir Something Cool
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><title>Verifikasi Email di Daft Something Cool=
</title><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3D=
UTF-8" /><meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge" /><me=
ta name=3D"viewport" content=3D"width=3Ddevice-width, initial-scale=3D1.0=
 " /></head><body style=3D"margin: 0; font-family: 'Cabin', 'Helvetica Ne=
ue', 'Helvetica', 'Arial', 'sans-serif';color: #6e7b8a;"><div style=3D"ba=
ckground: #fff; margin: 0 auto; max-width: 550px;"><p style=3D"font-size:=
 1.25rem; font-weight: 200; line-height: 1.5rem;">Silakan konfirmasi emai=
l Anda</p><p>Kepada YTH:</p><p>Bapak/Ibu Orangtua Calon Siswa di Somethin=
Cool,</p><p>Dengan hormat,</p><p>Anda mendapatkan email ini setelah menda=
ndaftar untuk melakukan pendaftaran pengisian data pribadi dan lainanda d=
i Something Cool, yang bernama:</p><p><strong>John Smith Passerby</strong=
></p><p>Selanjutnya silakan melakukan verifikasi email yang anda isi deng=
an menekan tombol di bawah ini untuk pergi ke alamat:</p><p style=3D"text=
-align:center;"><a href=3D"http://somethingco.web/?a=3Dverifikasi&v=3De27=
6a34f57d7a6ce4b266152&m=3Dmyemailaddresssomewh@gmail.com" style=3D"backgr=
ound: #CBA1DF;padding: 10px 20px 10px 30px;margin-bottom: 20px;color: #ff=
f;font-size: .85rem;text-decoration: none;display: inline-block;text-alig=
n: center;cursor: pointer;border-radius: 5px;">Verifikasi Email</a><p>Tau=
tan/link ini berlaku hanya untuk sekali saja.</p><p>Demikian disampaikan,=
 atas perhatian dan kerjasama Bapak/Ibu, kami ucapkan =

terima kasih.</p><p>NB: Bila Anda tidak meminta email ini, silakan mengab=
aikan email ini.</p><p>---<br>Panitia Penerimaan Pendaftara,<br>Something=
 cool</p></div></body></html>
`

**Comment by sj26** [comment]
That is a plain text email, so it is being displayed correctly. Notice the header at the top:

```
Content-Type: text/plain;
 charset=UTF-8
```

You should send your emails as html if you'd like them displayed as HTMl.
