### ISSUE TITLE
Change Default HTTP IP?

### ISSUE THREAD

**Issue by davekerber** [sj26/mailcatcher#51]
I'm curious if it would cause a problem to change the default http ip to '0.0.0.0' ?  It should still work the same and it would them work out of the box for people like me who develop in headless vagrant virtual machines and need to forward the port.

I'd be happy to do the pull request if you like.

I love the gem by the way.

**Comment by jarofgreen** [comment]
For anyone finding this later, this didn't work for me - I had to put the actual IP of the machine. Then it was fine. (Mailcatcher was running on Mac OX 10.10 and I was trying to reach it from a VM in Virtualbox)

Given the rise of Virtual Machine environments for dev work, these options should maybe be mentioned on http://mailcatcher.me/ ? I do agree these are the best defaults for security reasons tho.

Thanks for the software - it's great!
