### ISSUE TITLE
Update gem `thin` to version >`1.8.0` to resolve installation issues

### ISSUE THREAD

**Issue by jai-x** [sj26/mailcatcher#512]
Gem `thin` is required by `mailcatcher` and is specified within a minor version of `v1.5.0`:
https://github.com/sj26/mailcatcher/blob/30b10049b806a64d1c12419574334f6bd1634223/mailcatcher.gemspec#L42

The installation of gem `thin` requires a workaround that is documented in the readme:

> If you encounter issues installing [thin](https://rubygems.org/gems/thin), try:
> ```gem install thin -v 1.5.1 -- --with-cflags="-Wno-error=implicit-function-declaration"```

These issues have since been resolved in https://github.com/macournoyer/thin/pull/364 and the fix is available since version `v1.8.0`. 

Is it possible to upgrade the `thin` dependency or are there any blocking requirements to keep the version as is?

**Comment by sj26** [comment]
Yes there were/are a few issues preventing the upgrade. They are being worked through. Please use the documented workaround in the meantime.

**Comment by jai-x** [comment]
Thanks for the response.
Of the remaining work required to upgrade, is any of it documented anywhere such that people can contribute towards helping?

**Comment by sj26** [comment]
No, it is not.

If you'd like to help, please try the latest pre-release version which has swapped out the websocket library which was preventing upgrade:

```
gem install --pre mailcatcher
```

If you find any issues please report them.

**Comment by alistairholt** [comment]
`gem install --pre mailcatcher` => mailcatcher-0.9.0.beta1

@sj26 this appers to have the same problem?

**Comment by sj26** [comment]
@alistairholt could you please be more specific?

The beta doesn't upgrade thin, it upgrades the websocket integration. I'd like to see that stable before committing to upgrading thin.

**Comment by alistairholt** [comment]
@sj26 sure. When I tried the beta I still got the same error from thin on install.

**Comment by mlensment** [comment]
I was struggling with installing thin for an entire night, finally I figured out I had to add "-fdeclspec" flag.
I'm still running Mac OS Catalina with xcode 12.2, ruby 3.1.0 installed via rbenv.

Maybe someone finds it useful.
`gem install thin -v 1.5.1 -- --with-cflags="-Wno-error=implicit-function-declaration -fdeclspec"`
`gem install mailcatcher -N`

Inspiration:
https://github.com/nginx/unit/issues/653

**Comment by ivopavlov87** [comment]
Had this issue. Did not need the `-fdeclspec` flag.

Just had to do:
`gem install thin -v '1.5.1' -- --with-cflags="-Wno-error=implicit-function-declaration"`
then was able to do:
`gem install mailcatcher`

[Qiita Source](https://qiita.com/kazacky/items/ffdc80528e0064447d52). This is a Japanese site; I used Google Translate to read. I did not need to use `sudo`.
[Translated Qiita Source](https://qiita-com.translate.goog/kazacky/items/ffdc80528e0064447d52?_x_tr_sl=en&_x_tr_tl=bg&_x_tr_hl=en&_x_tr_pto=wapp).

[StackOverflow Source](https://stackoverflow.com/questions/64662290/gem-install-mailcatcher-fails-with-error-error-installing-mailcatcher-error).

System details:
MacBook Pro
16-inch 2021
Apple M1 Max
32 GB Memory
macOS Ventura 13.2

**Comment by sj26** [comment]
I have pushed another pre-release, [v0.9.0.beta2](https://github.com/sj26/mailcatcher/releases/tag/v0.9.0.beta2), which relaxes the thin requirement and should support ruby 3.2. Please try it:

```
gem install mailcatcher --pre
```
