### ISSUE TITLE
Forbidden 403 On SQLite

### ISSUE THREAD

**Issue by hadley8899** [sj26/mailcatcher#518]
Hi, I'm not sure if this is actually an issue with Mailcatcher or not, But I cannot currently install it due to the following error

gem install mailcatcher
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/sqlite3-1.5.0-x64-unknown.gemspec.rz)
    
I don't see any reports of RubyGems being down etc, So I'm not to sure about where to ask about this issue

**Comment by sj26** [comment]
Hm, I don't think that's a mailcatcher issue, it looks like Ruby might not understand your platform — the "unknown" bit is odd. Have you tried upgrading ruby, and rubygems?

**Comment by hadley8899** [comment]
Nailed it, I ran

sudo gem install rubygems-update
sudo update_rubygems

and now it installs. I take it the one from ubuntu's apt install is a little out of date (22.04)

**Comment by sj26** [comment]
Nice!
