### ISSUE TITLE
mailcatcher dependency on sqlite3 fails

### ISSUE THREAD

**Issue by rai-streamline** [sj26/mailcatcher#520]
command:
`sudo gem install mailcatcher`

error: 
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/sqlite3-1.5.3-x64-unknown.gemspec.rz)
```

environments tested:
```Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-163-generic x86_64)```

**Comment by rai-streamline** [comment]
for now, i tried forcing sqlite to use the lower version

`sudo gem install sqlite3 -v 1.3.11`

before mailcatcher installation.

**Comment by IsabelleLePivain** [comment]
Hi Rai!

It is the first time I am asking a question in relation with a GitHub issue. 
I am unsure if this feed is the best place to do it, but I am not familiar with GitHub yet. Feel free to let me know if there is a better place for it.

First, thank you for your workaround! It helped me get unstuck and have mailcatcher running.

However, I am brand new to development and do not really understand what is going wrong here.
My error message is slightly different than yours:
`cannot load such file -- sqlite3/sqlite3_native (LoadError)`
but also mentions an error relative to sqlite3 version.

I am running a standalone Docker container using the ruby:2.7-buster official image.
Just like you, I need to force the sqlite version before I can run mailcatcher. I would like to understand why.

Do you know why we need this additional step?

Thank you,

Isabelle
