### ISSUE TITLE
Dependencies conflict on Latest version and Rails 7

### ISSUE THREAD

**Issue by bvicenzo** [sj26/mailcatcher#524]
Hi everyone!

I'm trying to use the mailcatcher on Rails 7.
However, the newest version seems to have an incompatible version of Rack with Rails.

<img width="583" alt="Captura de Tela 2022-11-14 às 10 22 23" src="https://user-images.githubusercontent.com/173159/201670896-fd9e0575-6e4a-4408-8485-9cf2d27e1fdc.png">

```sh
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 7.0.1, >= 7.0.1) was resolved to 7.0.1, which depends on
      actionpack (= 7.0.1) was resolved to 7.0.1, which depends on
        rack (>= 2.2.0, ~> 2.0)

    mailcatcher (~> 0.8.2) was resolved to 0.8.2, which depends on
      rack (~> 1.5)
```

The oldest version I could install was `0.2.4`. However, this version seems to have this error: https://github.com/sj26/mailcatcher/issues/62

is there any solution or workaround for this?

Thanks, and Best regards!

**Comment by sj26** [comment]
Please don't put mailcatcher in your Gemfile:
https://github.com/sj26/mailcatcher#bundler
