### ISSUE TITLE
Unable to run current versions of mailcatcher with Rails 7

### ISSUE THREAD

**Issue by scott-knight** [sj26/mailcatcher#527]
I recently installed mailcatcher in my Rails 7 project as I was having issues with letter_opener and WSL. The current stable version appears to be `0.8.2`. However, this version has a dependency of `rack 1.5`. Rails 7 requires `rack 2.0+`. The version of mailcatcher that installs on Rails 7 is `0.2.4` which was released back in 2011. This version of mailcatcher installs some fairly old and unsupported gems. Updating the gem to support Rails 7 with currently managed and supported versions of dependencies would be great.

**Comment by sj26** [comment]
Please do not include MailCatcher in your Gemfile:

https://github.com/sj26/mailcatcher#bundler
