### ISSUE TITLE
mailcatcher - PHP 8.0./8.1

### ISSUE THREAD

**Issue by benlumia007** [sj26/mailcatcher#529]
does mailcatcher work with PHP 8.0 or PHP 8.1.. i tried using it and doesn't work.

**Comment by benlumia007** [comment]
so the way i have setup is 
/etc/php/8.0/mods-available/mailcatcher.ini
```
sendmail_path=/usr/local/bin/catchmail
```
this works with php7.4, so do i need to add anything after catchmail if its using PHP 8.0 or higher.

**Comment by benlumia007** [comment]
yeah when you install using `gem install mailcatcher` the catchmail and mailcatcher is all located at `/usr/local/bin` i could try `/usr/bin/env catchmail` to see if that makes any difference

**Comment by sj26** [comment]
Yeah, it should work. This isn't a mailcatcher issue per se, so I'll close this issue.

**Comment by benlumia007** [comment]
either way, i moved away. i can't get it to work on PHP 8.0 and PHP 8.1 so is cool.
