### ISSUE TITLE
ruby-3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1490:in `event_callback': undefined method `close' for 9:Integer (NoMethodError)

### ISSUE THREAD

**Issue by bhartee-sahare** [sj26/mailcatcher#535]
ruby-3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1490:in `event_callback': undefined method `close' for 9:Integer (NoMethodError)

I used the ruby-3.0.0
Rails 7.0.4.3
mailcatcher (0.2.4)

**Comment by bhartee-sahare** [comment]
ruby-3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1490:in `event_callback': undefined method `close' for 9:Integer (NoMethodError)

**Comment by CringeDeveloper** [comment]
This https://github.com/sj26/mailcatcher/issues/62

And this
https://github.com/sj26/mailcatcher#bundler

So you just need to remove mailcatcher from gemfile (for some reason it break everything) 

And run 

`gem install mailcatcher`

**Comment by sj26** [comment]
That version of mailcatcher is very old. It will be limited by interdependencies with your own application.

@CringeDeveloper is spot on — please remove mailcatcher from your Gemfile and install it using `gem install mailcatcher`.
