### ISSUE TITLE
Add clarity about message delivery in the readme

### ISSUE THREAD

**Issue by Scrambles56** [sj26/mailcatcher#538]
While going through the readme of this tool, it was unclear whether MailCatcher intercepted and stopped emails, or if it then sent them on to the intended recipient after intercepting. This was further confused by digging and finding issue #4, where it sounded like a desire to send the emails. 

I think it'd be worthwhile having a section in the readme that states "MailCatcher will not deliver emails to their email address" or something in that manner.

**Comment by sj26** [comment]
Sorry that wasn't clear! I don't think this has ever come up before, though, and is covered by the opening sentence in the README:

> MailCatcher runs a super simple SMTP server which catches any message sent to it to display in a web interface. 

I appreciate your reaching out, but I don't think a change is necessary at this time.
