### ISSUE TITLE
can not start mailcatcher

### ISSUE THREAD

**Issue by aurammh** [sj26/mailcatcher#539]
myominhtet@SIAN:/mnt/c/MyDatas/kids$ mailcatcher
Starting MailCatcher v0.8.2
==> smtp://127.0.0.1:1025
/home/myominhtet/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thin-1.5.1/lib/thin/server.rb:104:in `block in initialize': uninitialized constant Thin::Server::Fixnum (NameError)

        when Fixnum, /^\d+$/ then port    = arg.to_i
             ^^^^^^

Could you help me!

**Comment by alagos** [comment]
That's because the last stable version (0.8.2) uses a thin version uncompatible with ruby 3.x
Anyway, this has been solved in the last beta versions. Try with:
```bash
gem install mailcatcher --version=0.9.0.beta2
```

**Comment by kishaningithub** [comment]
Can a release be published?

**Comment by sj26** [comment]
v0.9.0 is out -- please give it a go:

```
gem install mailcatcher
```

Re-open if you continue having issues.

**Comment by noctivityinc** [comment]
@sj26 this seems to have an issue with sidekiq:

```
Because sidekiq >= 7.0.0.beta1 depends on rack >= 2.2.4
  and mailcatcher >= 0.6.4, < 0.10.0.alpha1 depends on rack ~> 1.5,
  sidekiq >= 7.0.0.beta1 is incompatible with mailcatcher >= 0.6.4, < 0.10.0.alpha1.
So, because Gemfile depends on mailcatcher ~> 0.9.0
  and Gemfile depends on sidekiq ~> 7.2,
  version solving has failed.
```
