### ISSUE TITLE
Fixnum is uninitialized

### ISSUE THREAD

**Issue by NabinOjha** [sj26/mailcatcher#545]
When you try to install mailcatcher with ruby 3.2.0 you will get Fixnum is not initialized inside server.rb . Please fix this using Integer instead

**Comment by tagliala** [comment]
This has been fixed on master and released in a beta version

Please try https://github.com/sj26/mailcatcher/issues/539#issuecomment-1562346020

**Comment by sj26** [comment]
v0.9.0 is out -- please give it a go:

```
gem install mailcatcher
```

Re-open if you continue having issues.
