### ISSUE TITLE
Update gem spec minimum versions

### ISSUE THREAD

**Issue by benebrice** [sj26/mailcatcher#551]
Hi guys,

I'm currently upgrading my Gemfile and I have conflicts with rake minimum version which involve Sinatra for this case. 

I've fork the latest version of Mailcatcher and update the `mailcatcher.gemspec`

I have change those:

```ruby
s.add_dependency "rack", "~> 2.1"
s.add_dependency "sinatra", "~> 2"
```

Does anybody know if there are possible side effects. If there is none, I can open the PR. 🙂

**Comment by sj26** [comment]
There are potential side effects.

Please don't include mailcatcher in your Gemfile:

https://github.com/sj26/mailcatcher#bundler

**Comment by benebrice** [comment]
Thanks @sj26 !
I've never read this note before. I'll extract if from my Gemfile. 👌🏻

**Comment by sj26** [comment]
Thanks @benebrice :pray:
