### ISSUE TITLE
0.9.1.beta2 does not work with Ruby 3.3

### ISSUE THREAD

**Issue by tagliala** [sj26/mailcatcher#553]
```
$ mailcatcher -f -v --http-ip=0.0.0.0
Starting MailCatcher v0.9.1.beta2
==> smtp://127.0.0.1:1025
==> http://0.0.0.0:1080
```

<img width="294" alt="image" src="https://github.com/sj26/mailcatcher/assets/556268/b0e29263-47b7-44fa-ba8f-baa867e800aa">

Unfortunately I cannot run specs on my machine, it looks like that there are issues with `base64` (no longer a default gem) and maybe more

**Comment by matt-whiteley** [comment]
This issue is affecting 0.9.0 release on ruby 3.3.0

If the fix is just upgrading the dependencies then this needs to be merged and released because mailcatcher is unusable for anyone who is running ruby 3.3 currently.

**Comment by FinnIckler** [comment]
Also just noticed this investigating a failing healthcheck for mailcatcher. Here's a minimal repo:
```
docker run -it ruby:3.3.0 /bin/bash
gem install mailcatcher
mailcatcher --http-ip=0.0.0.0 --no-quit
curl localhost:1080 -> Internal server error
```

**Comment by markymc** [comment]
I'm also seeing this issue on Ruby 3.3.0. Is there a workaround?

**Comment by matt-whiteley** [comment]
> I'm also seeing this issue on Ruby 3.3.0. Is there a workaround?

Use rbenv or rvm, and `cd` into a folder configured to use an older ruby version before starting mailcatcher.

**Comment by dorianmariecom** [comment]
e.g.:

```
> mkdir mailcatcher
> cd mailcatcher
> echo "3.2.2" > .ruby-version
> echo "ruby 3.2.2" > .tools-versions
> asdf install
> gem install mailcatcher
> mailcatcher --foreground
Starting MailCatcher v0.9.0
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
```

**Comment by sj26** [comment]
Pushed to rubygems — please try it out:

```
gem install mailcatcher --pre
```

After a couple of good reports I will promote this to `v0.10.0`.

**Comment by andreynering** [comment]
@sj26 It works for me! 😄

**Comment by tagliala** [comment]
```
15:51:32 mailcatcher.1    | Starting MailCatcher v0.10.0.alpha1
15:51:32 mailcatcher.1    | ==> smtp://127.0.0.1:1025
15:51:32 mailcatcher.1    | ==> http://0.0.0.0:1080
15:52:34 mailcatcher.1    | ==> SMTP: Received message from '<from@example.com>' (271 bytes)
```

Works for me too

**Comment by ansonhoyt** [comment]
Works for me with Ruby 3.3.0 and Rails 7.1.

**Comment by mockdeep** [comment]
Works for me!
