### ISSUE TITLE
Issue with Displaying Logs in MailCatcher

### ISSUE THREAD

**Issue by naoto-ysd** [sj26/mailcatcher#555]
I'm currently experiencing an issue with MailCatcher where I am unable to view logs when running it in the foreground.
I have tried the mailcatcher --foreground command, but no logs are being displayed in the console.

Environment:

Operating System: MacOS 14.2.1
Ruby version: 3.3.0
MailCatcher version: 0.9.0

Ensured that MailCatcher is not already running in the background.
Checked that MailCatcher is properly installed and the environment settings are correct.
Attempted to run mailcatcher --foreground with no additional parameters.
Tried using different ports for SMTP and HTTP.
Despite these efforts, the console shows no output from MailCatcher. There are no error messages or logs appearing, which makes it difficult to diagnose any issues.

Could you please provide any insights or suggestions on what might be causing this issue and how to resolve it? Is there a way to increase the log verbosity that I might be missing?

**Comment by CharlesPlantePulsar** [comment]
Same problem here did you found a solution ?

**Comment by sj26** [comment]
Can you please try again with the latest version?

```
gem install mailcatcher -v 0.10.0
mailcatcher --foreground
```

**Comment by CharlesPlantePulsar** [comment]
> Can you please try again with the latest version?
> 
> ```
> gem install mailcatcher -v 0.10.0
> mailcatcher --foreground
> ```

I confirm that version update fixed it
Thank you !
