### ISSUE TITLE
Permanent storage

### ISSUE THREAD

**Issue by 4d4ch4u32** [sj26/mailcatcher#561]
Currently, the mails are stored in a in-memory database (SQLite3).

I use the mailcatcher in docker for local development and staging environments. When a deploy is done, all docker containers will be restarted. The mails which are already catched are lost then.

Is it possible to use a permanent storage?

**Comment by sj26** [comment]
Not possible at the moment. Mail catcher is meant to be pretty lightweight and ephemeral, and persistence has always felt like more trouble than it’s worth.

[MailHog](https://github.com/mailhog/MailHog) is great if you want more options.

Please follow #2 if you’re keen.
