### ISSUE TITLE
Refreshing mailcatcher

### ISSUE THREAD

**Issue by surzycki** [sj26/mailcatcher#57]
When refreshing the web interface

``` bash
root@staging:/home/ubuntu# mailcatcher --ip 10.0.2.15 -f
Starting MailCatcher
==> smtp://10.0.2.15:1025
==> http://10.0.2.15:1080
/usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:1441:in `event_callback': undefined method `close' for 11:Fixnum (NoMethodError)
        from /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
        from /usr/local/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/mailcatcher-0.5.9/lib/mail_catcher.rb:134:in `run!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/mailcatcher-0.5.9/bin/mailcatcher:4:in `<top (required)>'
        from /usr/local/bin/mailcatcher:19:in `load'
        from /usr/local/bin/mailcatcher:19:in `<main>'
root@staging:/home/ubuntu# 
```

``` bash
root@staging:/home/ubuntu# gem list | grep mailcatcher
mailcatcher (0.5.9)
root@staging:/home/ubuntu# 
```

**Comment by ChiangChu** [comment]
Hello Guys,

I have still the an similar Problem. It is crashing as soon as I refresh the browser window in Chrome.
In Firefox it works.

`<PathToGemset>/gems/eventmachine-1.2.7/lib/eventmachine.rb:1490:in `event_callback': undefined method `close' for 14:Integer (NoMethodError)
Did you mean?  clone
	from <PathToGemset>/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	from <PathToGemset>/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	from <PathToGemset>/gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
	from <PathToGemset>/gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
	from <PathToGemset>/bin/mailcatcher:23:in `load'
	from <PathToGemset>/bin/mailcatcher:23:in `<main>'
	from<PathToGemset>/bin/ruby_executable_hooks:15:in `eval'
	from <PathToGemset>/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by sj26** [comment]
Your stack trace includes:

> mailcatcher-0.2.4

That's a very old version of mailcatcher. Please try upgrading.
