### ISSUE TITLE
Mailcatcher crashing

### ISSUE THREAD

**Issue by thomasfedb** [sj26/mailcatcher#76]
I noticed that mailcatcher was crashing reasonably frequently.

Ran it in the foreground with verbose output and got this:

```
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
==> SMTP: Received message from '<contact@synaptor.com.au>' (1232 bytes)
==> SMTP: Received message from '<contact@synaptor.com.au>' (1101 bytes)
==> SMTP: Received message from '<contact@synaptor.com.au>' (1098 bytes)
==> SMTP: Received message from '<contact@synaptor.com.au>' (1103 bytes)
/home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/gems/eventmachine-1.0.0/lib/eventmachine.rb:1441:in `event_callback': undefined method `close' for 15:Fixnum (NoMethodError)
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/gems/mailcatcher-0.5.9/lib/mail_catcher.rb:134:in `run!'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/gems/mailcatcher-0.5.9/bin/mailcatcher:4:in `<top (required)>'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/bin/mailcatcher:19:in `load'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/bin/mailcatcher:19:in `<main>'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/thomasfedb/.rvm/gems/ruby-1.9.3-p0@synaptor-observations/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by stefanahman** [comment]
Crashes for me as well using version 0.2.4
```
gems/eventmachine-1.0.4/lib/eventmachine.rb:1455:in `event_callback': undefined method `close' for 11:Fixnum (NoMethodError)
```

**Comment by sj26** [comment]
@stefanahman that's a very old version of mailcatcher, please upgrade

**Comment by SachinRJadhav** [comment]
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
Haml::TempleEngine: Option :outvar is invalid
/home/sodel/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:1489:in `event_callback': undefined method `close' for 18:Fixnum (NoMethodError)
Did you mean?  clone
	from /home/sodel/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	from /home/sodel/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	from /home/sodel/.rvm/gems/ruby-2.3.0/gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
	from /home/sodel/.rvm/gems/ruby-2.3.0/gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
	from /home/sodel/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `load'
	from /home/sodel/.rvm/gems/ruby-2.3.0/bin/mailcatcher:23:in `<main>'
	from /home/sodel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/sodel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mcris-roberto** [comment]
Hi,

I'm getting the same error when accessing the http://127.0.0.1:1080

` bundle exec mailcatcher
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
Haml::TempleEngine: Option :outvar is invalid
bundler: failed to load command: mailcatcher (/Users/username/.rbenv/versions/2.3.1/bin/mailcatcher)
NoMethodError: undefined method `close' for 14:Fixnum
Did you mean?  clone
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1489:in `event_callback'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailcatcher-0.2.4/lib/mail_catcher.rb:21:in `run'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mailcatcher-0.2.4/bin/mailcatcher:44:in `<top (required)>'
  /Users/username/.rbenv/versions/2.3.1/bin/mailcatcher:23:in `load'
  /Users/username/.rbenv/versions/2.3.1/bin/mailcatcher:23:in `<top (required)>'`

I am using mailcatcher-0.6.5

**Comment by mcris-roberto** [comment]
I was able to fix this by not including mailcatcher in the gemfile as suggested in https://github.com/sj26/mailcatcher/issues/290. I also used executed it using `mailcather` instead of `bundle exec mailcatcher`

**Comment by sj26** [comment]
@mcris-roberto please [do not put mailcatcher in your Gemfile](https://github.com/sj26/mailcatcher/blob/master/README.md#bundler). You are using mailcatcher 0.2.4, as stated in your backtrace, due to bundler's dependency resolution mechanisms falling back to an older version, and that version does not support eventmachine 1.2.5, which bundler has chosen to install. Instead, `gem install mailcatcher` and `mailcatcher`.

**Comment by sj26** [comment]
@mcris-roberto Nice timing! 😂

**Comment by sj26** [comment]
@SachinRJadhav you're having the same issue — please use mailcatcher directly, not within a Gemfile.

I'm locking this issue. If you get the above error make sure you're [not using mailcatcher in a Gemfile](https://github.com/sj26/mailcatcher/blob/master/README.md#bundler), and that you're using the latest version (`gem update mailcatcher`).
