### ISSUE TITLE
Dependency on thin makes running on JRuby impossible

### ISSUE THREAD

**Issue by tomtaylor** [sj26/mailcatcher#86]
The dependency on thin makes it impossible to run mailcatcher on JRuby.

Would it be a good approach to avoid being dependent on any specific server, perhaps picking from a few options at runtime? Or maybe just using a pure Ruby equivalent, such as Webrick?

**Comment by sj26** [comment]
Closing this. We probably won't support jruby explicitly if thin requires it. The magic of mailcatcher is that it's a single process doing everything which requires eventmachine, and the easiest way to do web in eventmachine is thin.
